
#+TITLE: config.org
#+AUTHOR: Deftpunk
#+STARTUP: content
#+OPTIONS: toc:4 :num:nil ^:nil

* About 

** Emacs

The big, beautiful, thermonuclear, editing reactor.

#+begin_quote
“Emacs outshines all other editing software in approximately the same
way that the noonday sun does the stars. It is not just bigger and
brighter; it simply makes everything else vanish.”

“Emacs is written in Lisp, which is the only computer language that is
beautiful.”

--Neal Stephenson
#+end_quote

** My Configuration

My configuration is based on [[https://orgmode.org/][Orgmode]] and optimization/perfomance lessons gleaned from
reviewing [[https://github.com/hlissner/doom-emacs][doom-emacs]] and other configuration's source. - see Credits section.

*** Some brief highlights

- lots & lots of [[https://github.com/emacs-evil/evil][Evil]]; it keeps my hands pain-free.

- I don't make use of custom.el, I prefer to be explicit about the things that I am changing.

- All of the extraneous Emacs files/dirs are kept under =.local/= & =.emacs.d/etc/=
  I tried out [[https://github.com/tarsius/no-littering][no-littering]] but found that it didn't work quite as I would have liked.

- Package management is handled by [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/Malabarba/paradox/][Paradox]]

- I autoload as many of the functions that I use as possible.  Avoid =require= and =load/load-file= as much as possible.

*** Versions of Emacs for MacOSX

I do most of my work on MacOSX these days and have tried several different builds
of Emacs on that Operating System.

**** Install via homebrew

I am currently using the Emacs you install via Homebrew with several extensions.
See the External Dependencies below before installing/using.

=brew install emacs --with-cocoa --with-modules --with-gnutls --with-imagemagick@6=

**** The railwaycat version

Wed Aug 23 11:54:20 2017 - Tried the [[https://github.com/railwaycat/homebrew-emacsmacport][railwaycat emacsmacport]] port.  Ultimately decided
not to use it.

- didn't solve my ansi-term/zsh problem with full configuration
- the Command key is now Alt; I liked having Alt & Super keys
- looks really, really nice
- the devicons package did not work out of the box, nor did the flycheck, etc. images

**** The emacs-plus version

Tried [[https://github.com/d12frosted/homebrew-emacs-plus][Emacs Plus]] as well, had similar problems as the railwaycat port - Emacs 25

*** External Dependencies

I rely on a few external programs to work with my Emacs installation.  Install
these =first= before installing/running Emacs.

   1. Install xcode
   2. Install the following packages via =brew install=
      - gls
      - coreutils
      - cask
      - ripgrep
      - aspell
      - zstd
   3. Install Node.js & the vmd module - =npm install -g vmd=
   4. Install libvterm
   5. Download latest org-mode
   6. Install the losveka font - https://github.com/be5invis/iosevka
      =brew tap homebrew/cask-fonts && brew cask install font-iosevka && brew cask install font-iosevka-slab=

clone evil-unimpaired to src/
clone bookmark-plus to src/

** Credits

Most of the basic settings and initial configuration are done in the
=core/core*.el= files that are a heavy copy of [[https://github.com/hlissner/doom-emacs][doom-emacs]] and how it configures
Emacs.  The result is a pretty fast initial startup given the amount of stuff.
I also copy some ideas and code from [[http://spacemacs.org/][spacemacs]], [[https://seagle0128.github.io/.emacs.d/][centaur emacs]] and others - full
props and credit to the authors of those fantastic configurations.

* Libraries

#+begin_src emacs-lisp :name crux
(use-package crux)
#+end_src

* UI

** all-the-icons

[[https://github.com/domtronn/all-the-icons.el][all-the-icons]] - Make Emacs pretty.
Don't forget to run =M-x all-the-icons-install-fonts= if this is a new install.

#+begin_src emacs-lisp :name all_the_icons
(use-package all-the-icons)
#+end_src

** doom modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] - A really nice and performant modeline broken out of [[https://github.com/hlissner/doom-emacs][doom-emacs]] by its author.

#+begin_src emacs-lisp :name doom_modeline
  (use-package doom-modeline
    :init
    (setq doom-modeline-minor-modes t
          doom-modeline-window-width-limit 80
          doom-modeline-buffer-file-name-style 'truncate-upto-project
          doom-modeline-modal-icon t
          doom-modeline-major-mode-color-icon t
          doom-modeline-major-mode-icon t
          doom-modeline-major-mode-color-icon t
          doom-modeline-buffer-modification-icon t
          doom-modeline-lsp t
          doom-modeline-vcs-max-length 14
          doom-modeline-gnus nil
          doom-modeline-gnus-timer 0
          doom-modeline-buffer-modification-icon t
          doom-modeline-project-detection 'projectile
          doom-modeline-icon (display-graphic-p))
    :hook (after-init . doom-modeline-mode))
#+end_src

** Extra highlights

*** cl-lib

[[https://github.com/skeeto/cl-lib-highlight][cl-lib]] Syntax highlighting for cl-lib, so that =cl-loop=, =cl-defun=,
=cl-defstruct= and the like get highlighted

#+begin_src emacs-lisp :name cl-lib
(use-package cl-lib-highlight
  :defer t
  :config
  (cl-lib-highlight-initialize))
#+end_src

*** highlight defined

https://github.com/Fanael/highlight-defined
Highlights defined Emacs Lisp symbols in source code.
Currently it recognizes Lisp function, built-in function, macro, faceand variable names.

#+BEGIN_SRC emacs-lisp :name highlight-defined
(use-package highlight-defined
  :defer t
  :config
  (add-hook 'emacs-lisp-mode-hook 'highlight-defined-mode))
#+END_SRC

*** highlight escape sequences

[[https://github.com/dgutov/highlight-escape-sequences/blob/master/highlight-escape-sequences.el][highlight-escape-sequences]] highlight escape sequences with the builtin face.

#+begin_src emacs-lisp :name highlight-escape-sequences
(use-package highlight-escape-sequences
  :defer t
  :commands hes-mode
  :init
  (add-hook 'prog-mode-hook 'hes-mode)
  :config
  (put 'hes-escape-backslash-face 'face-alias 'font-lock-builtin-face)
  (put 'hes-escape-sequence-face 'face-alias 'font-lock-builtin-face))
#+end_src

*** highlight-indent-guides

[[https://github.com/DarthFennec/highlight-indent-guides][highlight-indent-guides]] Highlight indentation levels.

#+begin_src emacs-lisp :name highlight-indent-guides
(use-package highlight-indent-guides
  :defer t
  :delight highlight-indent-guides-mode
  :init
  (setq highlight-indent-guides-method 'character
        ;; default is \x2502 but it is very slow on Mac
        highlight-indent-guides-character ?\xFFE8
        highlight-indent-guides-responsive 'top)
  :config
  ;; only in Python
  (add-hook 'python-mode-hook 'highlight-indent-guides-mode))
#+end_src

*** highlight numbers

[[https://github.com/Fanael/highlight-numbers][highlight-numbers]] Highlight numeric literals in source code.

#+begin_src emacs-lisp :name highlight-numbers
(use-package highlight-numbers
  :defer t
  :commands highlight-numbers-mode
  :init (add-hook 'prog-mode-hook #'highlight-numbers-mode))
#+end_src

*** highlight quotes

[[https://github.com/Fanael/highlight-quoted][highlight-quotes]] Highlight Lisp quotes and quoted symbols

#+begin_src emacs-lisp :name highlight-quotes
(use-package highlight-quoted
  :defer t
  :config
  (add-hook 'emacs-lisp-mode-hook 'highlight-quoted-mode))
#+end_src

*** highlight symbols

[[https://github.com/gennad/auto-highlight-symbol][highlight-symbol]] Highlight the symbol under point.

#+begin_src emacs-lisp :name highlight-symbol
(use-package auto-highlight-symbol
  :defer t
  :commands auto-highlight-symbol-mode
  :init
  (setq ahs-case-fold-search nil
        ahs-default-range 'ahs-range-whole-buffer
        ahs-idle-interval 0.25
        ahs-inhibit-face-list nil)
  ;; but a box around the face.
  (custom-set-faces `(ahs-face ((t (:box t)))))
  (custom-set-faces `(ahs-definition-face ((t (:box t)))))
  (custom-set-faces `(ahs-plugin-whole-buffer-face ((t (:box t)))))
  :config
  (add-hook 'prog-mode-hook 'auto-highlight-symbol-mode))
#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] - Make parenthesis' standout no matter your language.

#+begin_src emacs-lisp :name rainbow-delimiters
  (use-package rainbow-delimiters
    :config
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src

** Rainbow mode

[[https://julien.danjou.info/projects/emacs-packages][rainbow-mode]] - Show hex codes as their actual color.

#+begin_src emacs-lisp :name rainbow-mode
  (use-package rainbow-mode
    :defer t
    :commands rainbow-turn-on
    :init
    (add-hook 'prog-mode-hook 'rainbow-turn-on)
    :config
    (setq rainbow-x-colors nil))
#+end_src

** Themes

#+begin_src emacs-lisp :name doom-themes
  (use-package doom-themes
    :config
    (setq doom-themes-enable-bold t
          doom-themes-enable-italic t)
    (load-theme 'doom-moonlight t)
    (doom-themes-org-config)
  )
#+end_src

** solaire mode

[[https://github.com/hlissner/emacs-solaire-mode][solaire mode]] Give windows that you are working on a brighter background.

#+begin_src emacs-lisp :name solaire-mode
;; A more complex, more lazy-loaded config
(use-package solaire-mode
  ;; Ensure solaire-mode is running in all solaire-mode buffers
  :hook (change-major-mode . turn-on-solaire-mode)
  ;; ...if you use auto-revert-mode, this prevents solaire-mode from turning
  ;; itself off every time Emacs reverts the file
  :hook (after-revert . turn-on-solaire-mode)
  ;; To enable solaire-mode unconditionally for certain modes:
  :hook (ediff-prepare-buffer . solaire-mode)
  ;; Highlight the minibuffer when it is activated:
  :hook (minibuffer-setup . solaire-mode-in-minibuffer)
  :config
  ;; The bright and dark background colors are automatically swapped the first 
  ;; time solaire-mode is activated. Namely, the backgrounds of the `default` and
  ;; `solaire-default-face` faces are swapped. This is done because the colors 
  ;; are usually the wrong way around. If you don't want this, you can disable it:
  (setq solaire-mode-auto-swap-bg nil)

  (solaire-global-mode +1))
#+end_src

* Keybinding utilities

Things like hydra, major-mode-hydra, posframe and general.el that have to come pretty early so that we
can take advantage of them with other major mode packages and the like.

** posframe

A child frame at point connected to the root window's buffer.  I use this with
hydra/major-mode-hydra/pretty-hydra for convenience.

#+begin_src emacs-lisp :name posframe
  (use-package posframe)
#+end_src

** The General

[[https://github.com/noctuid/general.el][general.el]] - We use general.el to setup evil-mode, leader and other keybindings, as a result we pull it
in quite early.

Set the 'general-override-states' and enable the 'general-override-mode' so
that evil-collection and others don't override bindings that I want.

#+begin_src emacs-lisp :name general.el
  (use-package general
    :config
    (setq general-override-states '(insert
                                    emacs
                                    hybrid
                                    normal
                                    visual
                                    motion
                                    operator
                                    replace))
    (general-override-mode))
#+end_src

** Hydra

[[https://github.com/abo-abo/hydra][hydra]] - Make some bindings stick around.

#+BEGIN_SRC emacs-lisp :name hydra
  (use-package hydra)
#+END_SRC

** major-mode-hydra (includes pretty-hydra)

pretty-hydra saves us the trouble of formating the docstring using classic hydra (can be a pain).

#+BEGIN_SRC emacs-lisp :name majore-mode-hydra
  (use-package major-mode-hydra
    :init
    ;; Set the major-mode-hydra title using all-the-icons icon for the major mode
    (setq major-mode-hydra-title-generator
        '(lambda (mode)
           (s-concat "\n"
                     (s-repeat 10 " ")
                     (all-the-icons-icon-for-mode mode :v-adjust 0.05)
                     " "
                     (symbol-name mode)
                     " commands"))))

  ;; A bunch of utility functions from https://gist.github.com/mbuczko/e15d61363d31cf78ff17427072e0c325
  (defun with-faicon (icon str &optional height v-adjust)
    (s-concat (all-the-icons-faicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-fileicon (icon str &optional height v-adjust)
    (s-concat (all-the-icons-fileicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-octicon (icon str &optional height v-adjust)
    (s-concat (all-the-icons-octicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-material (icon str &optional height v-adjust)
    (s-concat (all-the-icons-material icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-mode-icon (mode str &optional height nospace face)
    (let* ((v-adjust (if (eq major-mode 'emacs-lisp-mode) 0.0 0.05))
           (args     `(:height ,(or height 1) :v-adjust ,v-adjust))
           (_         (when face
                        (lax-plist-put args :face face)))
           (icon     (apply #'all-the-icons-icon-for-mode mode args))
           (icon     (if (symbolp icon)
                         (apply #'all-the-icons-octicon "file-text" args)
                       icon)))
      (s-concat icon (if nospace "" " ") str)))
#+END_SRC

** hydra-posframe

#+BEGIN_SRC emacs-lisp :name hydra-posframe
  (use-package hydra-posframe
    :straight (hydra-posframe :type git :host github :repo "Ladicle/hydra-posframe")
    :hook (after-init . hydra-posframe-enable))
#+END_SRC

** which-key

[[https://github.com/justbur/emacs-which-key][which-key]] - Display available keybindings.

- =which-key-show-top-level= will show most key bindings without a prefix. It
  is most and not all, because many are probably not interesting to most
  users.
- =which-key-show-major-mode= will show the currently active major-mode
  bindings. It's similar to =C-h m= but in a which-key format. It is also
  aware of evil commands defined using =evil-define-key=.
- =which-key-show-next-page= is the command used for paging.
- =which-key-undo= can be used to undo the last keypress when in the middle
  of a key sequence.

#+begin_src emacs-lisp :name which-key
  (use-package which-key
    :commands which-key-mode
    :init
    (setq which-key-allow-evil-operators t
          which-key-show-operator-state-maps t)
    :config
    (which-key-mode))
#+end_src

* General Utilites

Make Emacs nicer to use in some way.

** ace-link

[[https://github.com/abo-abo/ace-link][ace-link]] Select a link to jump to in Info, help, woman, org or eww modes

#+begin_src emacs-lisp :name ace-link
   (use-package ace-link
     :init (ace-link-setup-default))
#+end_src

** ace-window

[[https://github.com/abo-abo/ace-window][ace-window]] - Selecting a window/frame to switch to

#+begin_src emacs-lisp :name ace-window
  (use-package ace-window
    :defer t
    :init
    (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
          aw-leading-char-style 'path
          aw-dispatch-alist '((?? aw-show-dispatch-help))
          aw-background t
          aw-dispatch-always t)
    :config
    (set-face-attribute 'aw-leading-char-face nil :height 4.0))
#+end_src

** hl-todo

[[https://github.com/tarsius/hl-todo][hl-todo]] - Highlight TODO and similar keywords in comments and strings.
By default it is only active in modes that derive from prog-mode.  It is a
dependency for =magit-hl-todos= which toggles in =magit-status=.

#+begin_src emacs-lisp :name hl-todo
  (use-package hl-todo
    :init
    (setq hl-todo-highlight-punctuation ":"))
  (add-hook 'prog-mode-hook 'hl-todo-mode)
#+end_src


* Software Development Utilites

** Git

*** git-gutter & git-gutter-fringe

[[https://github.com/syohex/emacs-git-gutter][git-gutter]] - Highlighting uncommited changes in the buffer.

#+begin_src emacs-lisp :name git-gutter
(use-package git-gutter
  :defer t
  :delight "gg"
  :init
  (setq git-gutter:update-interval 0.1
        git-gutter:ask-p nil
        git-gutter:verbosity 0
        git-gutter:handled-backends '(git))

  (add-hook 'git-gutter:update-hooks 'magit-after-revert-hook)
  (add-hook 'git-gutter:update-hooks 'magit-not-reverted-hook)
  (add-hook 'git-gutter:update-hooks 'vc-checkin-hook)
  (add-hook 'git-gutter:update-hooks 'focus-in-hook)
  (add-hook 'git-gutter:update-hooks 'auto-revert-mode-hook)
  (add-hook 'git-gutter:update-hooks 'after-revert-hook)
  (global-git-gutter-mode 1))

(use-package git-gutter-fringe)
(require 'git-gutter-fringe)

;; Update git-gutter on focus (in case I was using git externally) - from hlissner's emacs config.
(add-hook 'focus-in-hook #'git-gutter:update-all-windows)

(set-face-foreground 'git-gutter-fr:modified "blue3")
(set-face-foreground 'git-gutter:modified "blue3")
#+end_src

*** git-link

[[https://github.com/sshaw/git-link][git-link]] - Create URLs for files and commits in GitHub/Bitbucket/GitLab/... repositories.

#+begin_src emacs-lisp :name git-link
(use-package git-link
  :defer t
  :commands (git-link git-link-commit git-link-homepage))
#+end_src

*** git-messenger

[[https://github.com/syohex/emacs-git-messenger][git-messenger]] - Provides a function that pops up the commit message of the current line.

#+begin_src emacs-lisp :name git-messenger
  (use-package git-messenger
    :defer t
    :init
    (setq git-messenger:show-detail t
           git-messenger:handled-backends '(git))
    :config
    (define-key git-messenger-map (kbd "m") 'git-messenger:copy-message)
    (define-key git-messenger-map (kbd "ESC") 'git-messenger:popup-close))
#+end_src

*** git-modes

[[https://github.com/magit/git-modes][git-modes]] major modes for gitattributes, gitconfig & gitignore files

The gitconfig & gitignore modes derive from `conf-unix-mode` so you can use `gitignore-mode` for other
files that have nothing to do with Git.
```lisp
(add-to-list 'auto-mode-alist
             (cons "/.dockerignore\\'" 'gitignore-mode))
```

#+begin_src emacs-lisp :name git-modes
  (use-package git-modes
    :defer t)
#+end_src

*** git-timemachine

[[https://github.com/pidu/git-timemachine][git-timemachine]] - Allows you to go back and forth to the revisions of a file.

#+begin_src emacs-lisp :name git-timemachine
(use-package git-timemachine
  :defer t
  :config
  (require 'magit-blame)
  ;; Sometimes I forget `git-timemachine' is enabled in a buffer, so instead of
  ;; showing revision details in the minibuffer, show them in
  ;; `header-line-format', which has better visibility.
  (setq git-timemachine-show-minibuffer-details nil)
  (add-hook 'git-timemachine-mode-hook #'+vcs|init-header-line)
  (advice-add #'git-timemachine-show-revision :after #'+vcs*update-header-line)

  ;; Force evil to rehash keybindings for the current state
  (add-hook 'git-timemachine-mode-hook #'evil-force-normal-state))

;; From redguardtoo - http://blog.binchen.org/posts/new-git-timemachine-ui-based-on-ivy-mode.html
(defun my-git-timemachine-show-selected-revision ()
  "Show last (current) revision of file."
  (interactive)
  (let (collection)
    (setq collection
          (mapcar (lambda (rev)
                    ;; re-shape list for the ivy-read
                    (cons (concat (substring (nth 0 rev) 0 7) "|" (nth 5 rev) "|" (nth 6 rev)) rev))
                  (git-timemachine--revisions)))
    (ivy-read "commits:"
              collection
              :action (lambda (rev)
                        (git-timemachine-show-revision rev)))))

(defun my-git-timemachine ()
  "Open git snapshot with the selected version.  Based on ivy-mode."
  (interactive)
  (unless (featurep 'git-timemachine)
    (require 'git-timemachine))
  (git-timemachine--start #'my-git-timemachine-show-selected-revision))
#+end_src

** Magit

[[https://magit.vc/][Magit]] - The best git porcelain around.

Some more informational links:
https://emacsair.me/2017/09/01/magit-walk-through/
https://emacsair.me/2017/09/01/the-magical-git-interface/

#+begin_src emacs-lisp :name magit
  (use-package magit
    :defer t
    :init
    ;; Prevent ~/.emacs.d/transient from being created
    (setq transient-levels-file (concat deftpunk--local-dir "transient/levels")
          transient-values-file (concat deftpunk--local-dir "transient/values")
          transient-history-file (concat deftpunk--local-dir "transient/history"))

    :config
    (setq  magit-log-arguments '("--graph" "--decorate" "--color")
           magit-save-repository-buffers 'dontask
           magit-revert-buffers 'silent)

    (setq magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")
          magit-diff-refine-hunk t ; show granular diffs in selected hunk
	  ;; Don't autosave repo buffers. This is too magical, and saving can
	  ;; trigger a bunch of unwanted side-effects, like save hooks and
	  ;; formatters. Trust us to know what we're doing.
	  magit-save-repository-buffers nil)

   ;; TODO: switching buffers, cleaning up, doom autoloads (modules/tools/magit/autoload.el)
  ; (defadvice! +magit-revert-repo-buffers-deferred-a (&rest _)
  ;   :after '(magit-checkout magit-branch-and-checkout)
  ;   ;; Since the project likely now contains new files, best we undo the
  ;   ;; projectile cache so it can be regenerated later.
  ;   (projectile-invalidate-cache nil)
  ;   ;; Use a more efficient strategy to auto-revert buffers whose git state has
  ;   ;; changed: refresh the visible buffers immediately...
  ;   (+magit-mark-stale-buffers-h))
  ; ;; ...then refresh the rest only when we switch to them, not all at once.
  ; (add-hook 'doom-switch-buffer-hook #'+magit-revert-buffer-maybe-h)

    (after! evil
      ;; Switch to emacs state only while in `magit-blame-mode', then back when
      ;; its done (since it's a minor-mode).
      (add-hook! 'magit-blame-mode-hook
        (evil-local-mode (if magit-blame-mode -1 +1)))))
#+end_src

*** Magit Todos

https://github.com/alphapapa/magit-todos
Show TODOs in Magit status buffer for each file.

#+BEGIN_SRC emacs-lisp :name magit-todos
(use-package magit-todos
  :defer t
  :after magit
  :config
  (magit-todos-mode 1))
#+END_SRC

* The Prime Evil

** evil dependencies

*** goto-chg

[[https://github.com/emacs-evil/goto-chg][goto-chg]]

Provides support for the motions g; g, and for the last-change-register ., also
provides the functions goto-last-change and goto-last-change-reverse.

#+begin_src emacs-lisp :name goto-chg
(use-package goto-chg)
#+end_src

*** undo-tree

(use-package! undo-tree
  :when (featurep! +tree)
  ;; Branching & persistent undo
  :hook (doom-first-buffer . global-undo-tree-mode)
  :config
  (setq undo-tree-visualizer-diff t
        undo-tree-auto-save-history t
        undo-tree-enable-undo-in-region t
        ;; Increase undo-limits by a factor of ten to avoid emacs prematurely
        ;; truncating the undo history and corrupting the tree. See
        ;; https://github.com/syl20bnr/spacemacs/issues/12110
        undo-limit 800000
        undo-strong-limit 12000000
        undo-outer-limit 120000000
        undo-tree-history-directory-alist
        `(("." . ,(concat doom-cache-dir "undo-tree-hist/"))))

  ;; Compress undo-tree history files with zstd, if available. File size isn't
  ;; the (only) concern here: the file IO barrier is slow for Emacs to cross;
  ;; reading a tiny file and piping it in-memory through zstd is *slightly*
  ;; faster than Emacs reading the entire undo-tree file from the get go (on
  ;; SSDs). Whether or not that's true in practice, we still enjoy zstd's ~80%
  ;; file savings (these files add up over time and zstd is so incredibly fast).
  (when (executable-find "zstd")
    (defadvice! doom--undo-tree-make-history-save-file-name-a (file)
      :filter-return #'undo-tree-make-history-save-file-name
      (concat file ".zst")))

  ;; Strip text properties from undo-tree data to stave off bloat. File size
  ;; isn't the concern here; undo cache files bloat easily, which can cause
  ;; freezing, crashes, GC-induced stuttering or delays when opening files.
  (defadvice! doom--undo-tree-strip-text-properties-a (&rest _)
    :before #'undo-list-transfer-to-tree
    (dolist (item buffer-undo-list)
      (and (consp item)
           (stringp (car item))
           (setcar item (substring-no-properties (car item))))))

  ;; Undo-tree is too chatty about saving its history files. This doesn't
  ;; totally suppress it logging to *Messages*, it only stops it from appearing
  ;; in the echo-area.
  (advice-add #'undo-tree-save-history :around #'doom-shut-up-a))

** evil

[[https://github.com/emacs-evil/evil][evil]] Using Evil to make the editor part of Emacs even better than vim/neovim.

#+begin_src emacs-lisp :name evil
  (use-package evil
    :init
    (setq evil-default-state 'normal
          evil-want-C-u-scroll    t
          evil-want-C-w-delete    t
          evil-esc-delay          0
          evil-want-Y-yank-to-eol t
          evil-shift-width        4
          evil-want-integration   t
          evil-want-keybinding    nil   ; this is for evil-collection
          evil-toggle-key         "s-z" ; I want C-z to background in terminal
          evil-want-C-i-jump      t)

    (setq-default evil-symbol-word-search 1)

    :config

    (evil-mode 1)

    ;; https://emacs.stackexchange.com/questions/14940/emacs-doesnt-paste-in-evils-visual-mode-with-every-os-clipboard/15054#15054
    ;; Imagine the following scenario.  One wants to paste some previously copied
    ;; (from application other than Emacs) text to the system's clipboard in place
    ;; of some contiguous block of text in a buffer.  Hence, one switches to
    ;; `evil-visual-state' and selects the corresponding block of text to be
    ;; replaced.  However, one either pastes some (previously killed) text from
    ;; `kill-ring' or (if `kill-ring' is empty) receives the error: "Kill ring is
    ;; empty"; see `evil-visual-paste' and `current-kill' respectively.  The
    ;; reason why `current-kill' does not return the desired text from the
    ;; system's clipboard is because `evil-visual-update-x-selection' is being run
    ;; by `evil-visual-pre-command' before `evil-visual-paste'.  That is
    ;; `x-select-text' is being run (by `evil-visual-update-x-selection') before
    ;; `evil-visual-paste'.  As a result, `x-select-text' copies the selected
    ;; block of text to the system's clipboard as long as
    ;; `x-select-enable-clipboard' is non-nil (and in this scenario we assume that
    ;; it is).  According to the documentation of `interprogram-paste-function',
    ;; it should not return the text from the system's clipboard if it was last
    ;; provided by Emacs (e.g. with `x-select-text').  Thus, one ends up with the
    ;; problem described above.  To solve it, simply make
    ;; `evil-visual-update-x-selection' do nothing:
    (fset 'evil-visual-update-x-selection 'ignore)

    ;; More Esc quits
    (define-key evil-normal-state-map [escape] 'keyboard-quit)
    (define-key evil-visual-state-map [escape] 'keyboard-quit)
    (define-key evil-insert-state-map [escape] 'evil-normal-state)
    (global-set-key [escape] 'evil-exit-emacs-state))
#+end_src

** evil-collection

[[https://github.com/emacs-evil/evil-collection][evil-collection]] A collection of Evil bindings.

#+begin_src emacs-lisp :name evil-collection
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

** evil-goggles

[[https://github.com/edkolev/evil-goggles][evil-goggles]] Display a visual hint when editing with evil.

#+begin_src emacs-lisp :name evil-goggles
(use-package evil-goggles
  :config
  (evil-goggles-mode)

  ;; optionally use diff-mode's faces; as a result, deleted text
  ;; will be highlighed with `diff-removed` face which is typically
  ;; some red color (as defined by the color theme)
  ;; other faces such as `diff-added` will be used for other actions
  (evil-goggles-use-diff-faces))
#+end_src

* Keybindings

** Ctrl/Alt/Super

#+begin_src emacs :name ctrl_alt_super
  (global-set-key (kbd "C--") 'ace-window)
#+end_src

** Hydras

*** the version-control hydra

#+BEGIN_SRC emacs-lisp :name version-control-hydra
  ;; A modified unpackaged/magit-status
  ;; I removed the deletion of the other window.
  ;;;###autoload
  (defun deftpunk:unpackaged/magit-status ()
    "Open a `magit-status' buffer and close the other window so only Magit is visible.
  If a file was visited in the buffer that was active when this
  command was called, go to its unstaged changes section."
    (interactive)
    (let* ((buffer-file-path (when buffer-file-name
                               (file-relative-name buffer-file-name
                                                   (locate-dominating-file buffer-file-name ".git"))))
           (section-ident `((file . ,buffer-file-path) (unstaged) (status))))
      (magit-status)
      (when buffer-file-path
        (goto-char (point-min))
        (cl-loop until (when (equal section-ident (magit-section-ident (magit-current-section)))
                         (magit-section-show (magit-current-section))
                         (recenter)
                         t)
                 do (condition-case nil
                        (magit-section-forward)
                      (error (cl-return (magit-status-goto-initial-section-1))))))))

    (defvar version-control-hydra--title (with-faicon "code" "Version Control" 1 -0.05))
    (pretty-hydra-define version-control-hydra
      (:color blue :title version-control-hydra--title)
      ("Magit"
       (("a" vc-annotate "side-by-side blame")
        ("d" magit-file-dispatch "do stuff with git")
        ("g" magit-status "magit status")
        ("G" deftpunk:unpackaged/magit-status "Only magit-status")
        ("h" helm-hunks-current-buffer "Helm Git hunks")
        ("j" (progn (git-gutter:next-hunk 1) (recenter)) "next hunk")
        ("k" (progn (git-gutter:previous-hunk 1) (recenter)) "previous hunk")
        ("m" git-messenger:popup-message "git messenger")
        ("l" magit-log "Git log")
        ("t" git-timemachine "timemachine"))))
#+END_SRC

*** windows hydra

#+BEGIN_SRC emacs-lisp :name windows-hydra
  (defun spacemacs/alternate-window ()
    "Switch back and forth between current and last window in the
  current frame."
    (interactive)
    (let (;; switch to first window previously shown in this frame
          (prev-window (get-mru-window nil t t)))
      ;; Check window was not found successfully
      (unless prev-window (user-error "Last window not found."))
      (select-window prev-window)))

    ;(defvar windows-hydra--title (with-faicon "window-maximize" "Windows" 1 -0.05))
    (pretty-hydra-define windows-hydra
      (:color red :title "Windows" :post (progn (message "Don't break the windows!")))
      ("Change Size"
       (("s" shrink-window-horizontally "shrink horizontally")
        ("e" enlarge-window-horizontally "enlarge horizontally")
        ("b" balance-windows "balance window height")
        ("m" maximize-window "maximize current window")
        ("M" minimize-window "minimize current window"))

       "The Splits"
       (("h" split-window-below "split horizontally")
        ("v" split-window-right "split vertically")
        ("c" delete-window "delete current window")
        ("o" delete-other-windows "delete-other-windows"))

       "Window Movement"
       (("-" ace-window "ace window" :color blue)
        ("h" windmove-left "← window")
        ("j" windmove-down "↓ window")
        ("k" windmove-up "↑ window")
        ("l" windmove-right "→ window")
        ("r" toggle-window-split "rotate windows")
        ("w" spacemacs/alternate-window "last window"))))
#+END_SRC

*** the jk hydra

#+BEGIN_SRC emacs-lisp :name jk-hydra
  (defvar hydra-jk--title (with-faicon "cogs" "Control Panel" 1 -0.05))
  (pretty-hydra-define hydra-jk
    (:color blue :title hydra-jk--title
            :post (progn
                    (message "Thank you, please come again")))
    ("Tools"
     (("e" major-mode-hydra "Major Mode Hydra")
      ("i" helm-mini "Buffers/Recentf")
      ("s" swiper "Swiper")
      ("x" helm-M-x "Fuzzy M-x"))

     "Version Control"
     (("g" version-control-hydra/body "Git stuff"))

     "Windows"
     (("-" ace-window "ace-window")
      ("w" windows-hydra/body "windows hydra"))))
#+END_SRC

*** the toggle hydra

l - line numbers
n - treemacs
t - some tagbar equivalent; maybe there is a lsp-mode outline

** Evil leader

Set up the leader key using general.el

#+begin_src emacs-lisp :name leader
  (general-create-definer my-leader-def
    ;; :prefix my-leader
    :prefix "SPC")

  ;; helpful-hydra/body - is defined in the helpful 'use-package' declaration
  (my-leader-def 'normal 'override
    ;"c" 'hydra-cee/body
    "e" 'major-mode-hydra
    ;"f" 'hydra-files-projectile/body
    "f" 'counsel-find-file
    "g" 'version-control-hydra/body
    ;"h" 'helpful-hydra/body
    "i" 'helm-mini
    "k" 'flex//kill-current-buffer
    ; Use with M-o to select other actions, e.g. switch-project
    "p" 'counsel-projectile
    "q" 'save-buffers-kill-terminal
    "r" 'counsel-rg
    "s" 'swiper
    "w" 'save-buffer
    "y" 'counsel-yank-pop
    "-" 'ace-window
    )
#+end_src


** State keybindings

*** Normal State bindings

Normal state keybindings.

#+BEGIN_SRC emacs-lisp :name normal-state
  (general-define-key
   :states 'normal
   ;; run the macro in the q register
   "Q" "@q"
   "U" 'undo-tree-redo
   "Y" "yg_"
   ;; "gd" 'counsel-etags-find-tag-at-point
   "gs" 'avy-goto-char-2
   ;; Evil doesn't allow you to overload like Vim/Neovim do.  So this fails because s is not a prefix key.
   ;; But 'v' gets blown away and doesn't fail with the same error???
   ;; "ss" 'deftpunk:split-horizontally-recenter
   ;; "vv" 'deftpunk:split-vertically-recenter
   )

;; Add some bindings to the window "C-w <something" map.
;; Thu Nov 22 22:54:18 2018 - we have to bind evil-window-map this way, as
;; opposed to using general.el
(define-key evil-window-map "b" 'balance-windows)          ; replaces evil-window-bottom-right.
(define-key evil-window-map "d" 'ace-delete-window)        ; was unused
;; (define-key evil-window-map "e" 'hydra-window-sizing/body) ; was unused
(define-key evil-window-map "f" 'make-frame)               ; was unused
(define-key evil-window-map "i" 'ace-maximize-window)      ; was unused
;; (define-key evil-window-map "m" 'doom/toggle-fullscreen)   ; was unused
(define-key evil-window-map "r" 'winner-redo)              ; replaces evil-window-rotate-downwards
(define-key evil-window-map "u" 'winner-undo)              ; was unused
(define-key evil-window-map "-" 'ace-window)               ; was unused

;; Some easy window moving keys
;; Thrs Nov 22 2018 9:54:34 - for some reason I had to use the define-key mapping scheme in order toxtxt
;; get this to work(?)
(global-unset-key  (kbd "C-j"))
(global-unset-key  (kbd "C-k"))
(global-unset-key  (kbd "C-l"))
;; (global-unset-key (kbd "C-h"))
(define-key evil-normal-state-map (kbd "C-j") 'windmove-down)
(define-key evil-normal-state-map (kbd "C-k") 'windmove-up)
(define-key evil-normal-state-map (kbd "C-h") 'windmove-left)
(define-key evil-normal-state-map (kbd "C-l") 'windmove-right)

;; TODO: modify gx to use - org-open-at-point
#+END_SRC

* keychord

[[https://www.emacswiki.org/emacs/key-chord.el][key-chord]] Map pairs of simultaneously pressed keys to commands.

Keychord has a couple of drawbacks
1. Doesn't get recorded when recording macros.
2. Can't use function keys in keychords
3. Doesn't work well with internationalization packages.

#+begin_src emacs-lisp :name key-chord
  (use-package key-chord
    :init
    (key-chord-mode 1))
  (key-chord-define-global "jk" 'hydra-jk/body)
#+end_src

