;;; early-init.el --- deftpunk early-init file. -*- lexical-binding: t; -*-
;;;
;;; Commentary:
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in emacs.d/dftpnk-emacs.org
;;;
;;; Code:

(setq package-enable-at-startup nil)

;; Time how long Emacs starts up.
;; Use a hook so the message doesn't get clobbered by other messages.
(add-hook 'emacs-startup-hook
          (lambda ()
            (message "Emacs ready in %s with %d garbage collections."
                     (format "%.2f seconds"
                             (float-time
                              (time-subtract after-init-time before-init-time)))
                     gcs-done)))

(defun load-env-file (file)
  "Read and set envvars from FILE."
  (if (null (file-exists-p file))
      (signal 'file-error
              (list "No envvar file exists." file
                    "Run `emacs --quick --script ~/.emacs.d/scripts/gen-env-file.el` from a terminal."))
    (with-temp-buffer
      (insert-file-contents file)
      (when-let (env (read (current-buffer)))
        (let ((tz (getenv-internal "TZ")))
          (setq-default process-environment (append env (default-value 'process-environment))
                        exec-path (append (split-string (getenv "PATH") path-separator t)
                                          (list exec-directory))
                        shell-file-name (or (getenv "SHELL") (default-value 'shell-file-name)))
          (when-let (newtz (getenv-internal "TZ"))
            (unless (equal tz newtz)
              (set-time-zone-rule newtz))))
        env))))

(load-env-file "~/.emacs.d/var/env.el")

;; Mostly prevents libgccjit errors; manually setting to the latest gcc path is brittle.
;; I had to update the path below to the latest gcc/libgccjit, uninstall/re-install emacs-plus, then run `emacs -nw` to get the native-comp to work properly.
;; Solution found at: https://github.com/d12frosted/homebrew-emacs-plus/issues/554
(setenv "LIBRARY_PATH"
        (string-join
         '("/opt/homebrew/lib/gcc/current"
           "/opt/homebrew/opt/libgccjit/lib/gcc/14"
           "/opt/homebrew/opt/gcc/lib/gcc/14/gcc/aarch64-apple-darwin21/14")
         ":"))

;; Use plists for deserialization for lsp-mode
(setenv "LSP_USE_PLISTS" "true")

;; Get rid of some window chrome.
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)

;; Remove the startup nonsense and replace w/ mine.
(setq inhibit-startup-screen t
      inhibit-startup-message t
      inhibit-startup-echo-area-message t
      inhibit-splash-screen t
      initial-scratch-message ";;; Welcome to the Church of Emacs ;;;")

(setq use-file-dialog nil)

;; Resizing the Emacs frame can be a terribly expensive part of changing the
;; font. By inhibiting this, we easily halve startup times with fonts that are
;; larger than the system default.
(setq frame-inhibit-implied-resize t
      frame-resize-pixelwise t
      cursor-in-non-selected-windows nil)

;; Initial GC numbers
;; Set here, at the top of init.el and then reset at end of init.el
(setq gc-cons-threshold most-positive-fixnum)

;; Unbind some Super keys on my Mac
(global-unset-key (kbd "s-a"))
(global-unset-key (kbd "s-d"))
(global-unset-key (kbd "s-f"))
(global-unset-key (kbd "s-g"))
(global-unset-key (kbd "s-h"))
(global-unset-key (kbd "s-i"))
(global-unset-key (kbd "s-j"))
(global-unset-key (kbd "s-k"))
(global-unset-key (kbd "s-m"))
(global-unset-key (kbd "s-o"))
(global-unset-key (kbd "s-p"))
(global-unset-key (kbd "s-s"))
(global-unset-key (kbd "s-t"))
(global-unset-key (kbd "s-u"))
(global-unset-key (kbd "s-w"))
(global-unset-key (kbd "s-y"))

(provide 'early-init)
;;; early-init.el ends here
