;;; init.el --- deftpunk Emacs config file -*- lexical-binding: t; buffer-read-only: t -*-
;;;
;;; Commentary:
;;; Emacs `init.el' config for deftpunk
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in emacs.d/deftpunk-emacs.org
;;;
;;; Code:

(defconst deftpunk--emacs-dir (file-truename "~/.emacs.d")
  "The path to the emacs.d directory")

(defconst deftpunk--org-configuration-file (concat deftpunk--emacs-dir "/deftpunk-emacs.org")
  "The Org mode literate configuration file.")

(defconst deftpunk--etc-dir (concat deftpunk--emacs-dir "/etc/")
  "Location for files to save across systems.")

(defconst deftpunk--var-dir (concat deftpunk--emacs-dir "/var/")
  "Location for cache & files that we don't save across systems.")

;; I use Mac & occasionally Linux, no Windoze.
(defconst IS-MAC (eq system-type 'darwin))
(defconst IS-LINUX (eq system-type 'gnu/linux))

(defvar elpaca-installer-version 0.6)
(defvar elpaca-directory (expand-file-name "elpaca/" deftpunk--var-dir))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;; Install a package via the elpaca macro
;; See the "recipes" section of the manual for more details.

;; (elpaca example-package)

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;; Expands to: (elpaca evil (use-package evil :demand t))
;; (use-package evil :demand t)

;;Turns off elpaca-use-package-mode current declaration
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
;; (use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
;; (elpaca nil (message "deferred"))

(use-package general)

(elpaca-wait)

;; local leader
;; This allows for finer granularity than hydra-major-mode by binding to individual key maps.
(general-create-definer deftpunk-local-leader-def
  :keymaps 'override
  :prefix "C-;")

(use-package blackout)
(elpaca-wait)

(use-package on
  :elpaca (:host github :repo "ajgrf/on.el")
  :config
  (elpaca-wait)
  (require 'on))

(use-package which-key
  :blackout
  :commands (which-key-mode)
  :hook (on-first-input . which-key-mode)
  :custom
  (which-key-enable-exteded-define-key t)
  (which-key-idle-delay 0.5)
  :config
  (elpaca-wait)
  (which-key-mode +1))

(use-package hydra)
(elpaca-wait)

;;; Some convenience macros from our favorite martian - Doom Emacs creator Henrik Lissner ;;;

;; 4/22/2020 - In after! below, I removed the check to see if the package was
;; in the list of doom-disabled-packages
(defmacro after! (package &rest body)
  "Evaluate BODY after PACKAGE have loaded.

    PACKAGE is a symbol or list of them. These are package names, not modes,
    functions or variables. It can be:

    - An unquoted package symbol (the name of a package)
        (after! helm BODY...)
    - An unquoted list of package symbols (i.e. BODY is evaluated once both magit
      and git-gutter have loaded)
        (after! (magit git-gutter) BODY...)
    - An unquoted, nested list of compound package lists, using any combination of
      :or/:any and :and/:all
        (after! (:or package-a package-b ...)  BODY...)
        (after! (:and package-a package-b ...) BODY...)
        (after! (:and package-a (:or package-b package-c) ...) BODY...)
      Without :or/:any/:and/:all, :and/:all are implied.

    This is a wrapper around `eval-after-load' that:

    1. Suppresses warnings for disabled packages at compile-time
    2. No-ops for package that are disabled by the user (via `package!')
    3. Supports compound package statements (see below)
    4. Prevents eager expansion pulling in autoloaded macros all at once"
  (declare (indent defun) (debug t))
  (if (symbolp package)
      (list (if (or (not (bound-and-true-p byte-compile-current-file))
                    (require package nil 'noerror))
                #'progn
              #'with-no-warnings)
            (let ((body (macroexp-progn body)))
              `(if (featurep ',package)
                   ,body
                 ;; We intentionally avoid `with-eval-after-load' to prevent
                 ;; eager macro expansion from pulling (or failing to pull) in
                 ;; autoloaded macros/packages.
                 (eval-after-load ',package ',body))))
    (let ((p (car package)))
      (cond ((not (keywordp p))
             `(after! (:and ,@package) ,@body))
            ((memq p '(:or :any))
             (macroexp-progn
              (cl-loop for next in (cdr package)
                       collect `(after! ,next ,@body))))
            ((memq p '(:and :all))
             (dolist (next (cdr package))
               (setq body `((after! ,next ,@body))))
             (car body))))))

(defmacro appendq! (sym &rest lists)
  "Append LISTS to SYM in place."
  `(setq ,sym (append ,sym ,@lists)))

;; TODO: Need the doom-enlist function definition for this to work.
;;  (defmacro defadvice! (symbol arglist &optional docstring &rest body)
;;    "Define an advice called SYMBOL and add it to PLACES.
;;
;;    ARGLIST is as in `defun'. WHERE is a keyword as passed to `advice-add', and
;;    PLACE is the function to which to add the advice, like in `advice-add'.
;;    DOCSTRING and BODY are as in `defun'.
;;
;;    \(fn SYMBOL ARGLIST &optional DOCSTRING &rest [WHERE PLACES...] BODY\)"
;;    (declare (doc-string 3) (indent defun))
;;    (unless (stringp docstring)
;;      (push docstring body)
;;      (setq docstring nil))
;;    (let (where-alist)
;;      (while (keywordp (car body))
;;        (push `(cons ,(pop body) (doom-enlist ,(pop body)))
;;              where-alist))
;;      `(progn
;;         (defun ,symbol ,arglist ,docstring ,@body)
;;         (dolist (targets (list ,@(nreverse where-alist)))
;;           (dolist (target (cdr targets))
;;             (advice-add target (car targets) #',symbol))))))
;;
;;  (defmacro delq! (elt list &optional fetcher)
;;    "`delq' ELT from LIST in-place.
;;      If FETCHER is a function, ELT is used as the key in LIST (an alist)."
;;    `(setq ,list
;;           (delq ,(if fetcher
;;                      `(funcall ,fetcher ,elt ,list)
;;                    elt)
;;                 ,list)))

;; There are certain buffers I don't want to delete on accident.
;; Code taken from https://github.com/rememberYou/.emacs.d/blob/master/config.org
(defvar *protected-buffers* '("*scratch*" "*Messages*"))

(defun arco/protected-buffers ()
  "Protects some buffers from being killed."
  (dolist (buffer *protected-buffers*)
    (if (get-buffer buffer)
        (with-current-buffer buffer
          (emacs-lock-mode 'kill))
      (get-buffer-create buffer)
      (with-current-buffer buffer
        (emacs-lock-mode 'kill)))))

(general-add-hook 'emacs-startup-hook #'arco/protected-buffers)

  ;;;###autoload
;; https://stackoverflow.com/questions/251908/how-can-i-insert-current-date-and-time-into-a-file-using-emacs
(defun today ()
  "Insert string for today's date nicely formatted in American style,
  e.g. Sunday, September 17, 2000."
  (interactive)                 ; permit invocation in minibuffer
  (insert (format-time-string "%A, %B %e, %Y")))

  ;;;###autoload
(defun flex//kill-current-buffer ()
  "What it says."
  (interactive)
  (kill-buffer (current-buffer)))

(defun vim-return ()
  "Still want Return to do the right thing in dired mode."
  (interactive)
  (if (eq major-mode 'dired-mode)
      (dired-find-file)
    (progn
      (next-line)
      (back-to-indentation-or-beginning))))

;; not broken, toggle letter case from
;; http://ergoemacs.org/emacs/modernization_upcase-word.html][xah]] originally.
;; http://stackoverflow.com/questions/18257573/how-to-toggle-letter-cases-in-a-region-in-emacs
(defun toggle-letter-case ()
  "Toggle the letter case of current word or text selection.
   Toggles between: “all lower”, “Init Caps”, “ALL CAPS”."
  (interactive)
  (let (p1 p2 (deactivate-mark nil) (case-fold-search nil))
    (if (region-active-p)
        (setq p1 (region-beginning) p2 (region-end))
      (let ((bds (bounds-of-thing-at-point 'word) ) )
        (setq p1 (car bds) p2 (cdr bds)) ) )
    (when (not (eq last-command this-command))
      (save-excursion
        (goto-char p1)
        (cond
         ((looking-at "[[:lower:]][[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]][[:upper:]]") (put this-command 'state "all caps") )
         ((looking-at "[[:upper:]][[:lower:]]") (put this-command 'state "init caps") )
         ((looking-at "[[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]]") (put this-command 'state "all caps") )
         (t (put this-command 'state "all lower") ) ) ) )
    (cond
     ((string= "all lower" (get this-command 'state))
      (upcase-initials-region p1 p2) (put this-command 'state "init caps"))
     ((string= "init caps" (get this-command 'state))
      (upcase-region p1 p2) (put this-command 'state "all caps"))
     ((string= "all caps" (get this-command 'state))
      (downcase-region p1 p2) (put this-command 'state "all lower")) )
    ) )

;;
(defun deftpunk/catch-error-p (func-symbol)
  "Call the passed function solely for the purpose of catching its error."
  (let (retval)
    (condition-case error
        (funcall func-symbol)
      ('error (setq retval error)))
    retval))

;; Full history of this function is foggy and lost to time.
;; https://stackoverflow.com/questions/234963/re-open-scratch-buffer-in-emacs
(defun eme-goto-scratch ()
            "this sends you to the scratch buffer"
            (interactive)
            (let ((eme-scratch-buffer (get-buffer-create "*scratch*")))
    (switch-to-buffer eme-scratch-buffer)
    (lisp-interaction-mode)))

;; Some more excellence from karthinks.
(defun repeated-prefix-help-command ()
  (interactive)
  (when-let* ((keys (this-command-keys-vector))
              (prefix (seq-take keys (1- (length keys))))
              (orig-keymap (key-binding prefix 'accept-default))
              (keymap (copy-keymap orig-keymap))
              (exit-func (set-transient-map keymap t #'which-key-abort)))
    (define-key keymap [remap keyboard-quit]
                (lambda () (interactive) (funcall exit-func)))
    (which-key--create-buffer-and-show nil keymap)))
(setq prefix-help-command #'repeated-prefix-help-command)

(use-package no-littering
  :custom
  (no-littering-etc-directory deftpunk--etc-dir)
  (no-littering-var-directory deftpunk--var-dir)
  (auto-save-file-name-transforms
   `((".*" ,(expand-file-name "auto-save/" no-littering-var-directory) t))))

(elpaca-wait) ; So that other packages know where some Emacs system files are.

(use-package crux
  :bind (("C-a" . crux-move-beginning-of-line)
         ("C-k" . crux-smart-kill-line)
         ("s-o" . crux-smart-open-line-above)
         ("s-RET" . crux-smart-open-line)))

(set-face-attribute 'default nil :font "Menlo" :height 120)
;;(set-face-attribute 'default nil :font "Victor Mono" :height 110)
(set-fontset-font t nil "Menlo" nil 'append) ; fallback font

(use-package all-the-icons)

(use-package beacon
  :custom
  (beacon-lighter "")
  (beacon-size 45)
  (beacon-blink-when-window-scrolls nil)
  :config (beacon-mode 1))

(use-package hl-todo
  :elpaca (hl-todo :depth nil) ; see https://github.com/alphapapa/magit-todos/issues/171
  :init
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces '(("TODO" . "#FF0000")
                                ("FIXME" . "#FF9999")
                                ("FAIL" . "#FF0000")
                                ("DEPRECATED" . "#1F39EF")
                                ("HACK" . "#FF0000")
                                ("XXX" . "#FF0000")
                                ("NOTE" . "#1E90FF")))
  :hook (prog-mode . hl-todo-mode))

(use-package solaire-mode
  :config
  (solaire-global-mode +1))

(keymap-set minibuffer-local-map "C-w" 'backword-kill-word)
(keymap-set minibuffer-local-completion-map "C-w" 'backword-kill-word)
(keymap-set minibuffer-local-filename-completion-map "C-w" 'backword-kill-word)

(use-package avy
  :defer t
  :config
  (setq avy-all-windows nil
        avy-background t))

(use-package vertico
  :demand t ; otherwise it doesn't come up right away.
  :elpaca (vertico :files (:defaults "extensions/*") ; Special recipe to load extensions conveniently
           :includes (vertico-indexed
                      vertico-flat
                      vertico-grid
                      vertico-mouse
                      vertico-quick
                      vertico-buffer
                      vertico-repeat
                      vertico-reverse
                      vertico-directory
                      vertico-multiform
                      vertico-unobtrusive
                      ))
  :general
  (:keymaps 'vertico-map
        "<tab>" #'vertico-insert
        "<escape>" #'keyboard-quit
        "<backspace>" #'vertico-directory-delete-char
        "C-w" #'vertico-directory-delete-word
        "?" #'minibuffer-completion-help
        "s-." #'vertico-repeat
        )
  :custom
  (read-file-name-completion-ignore-case t)
  (read-buffer-completion-ignore-case t)
  (completion-ignore-case t)
  (vertico-resize t)
  (vertico-cycle t)
  (vertico-count 25)
  :config
  (vertico-mode))

(use-package orderless
  :after vertico
  :custom
  (orderless-matching-styles
   '(orderless-literal
     orderless-prefixes
     orderless-initialism
     orderless-regexp
     orderless-flex))
  (completion-styles '(orderless basic))
  (completion-category-defaults nil)
  (completion-category-overrides
   '((file (styles basic-remote                            ; basic-remote for Tramp hostname completion with vertico
                   orderless partial-completion)))))

(use-package marginalia
  :general
  (:keymaps 'minibuffer-local-map
   "s-a" 'marginalia-cycle)
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'right)
  :init
  (marginalia-mode)
  :config
  ;; An annotator so that M-x aliases show up.
  ;; https://www.reddit.com/r/emacs/comments/196pvtx/comment/khxa8ip/?utm_source=share&utm_medium=web2x&context=3
  (defun marginalia-annotate-alias (cand)
"Annotate CAND with the function it aliases."
(when-let ((sym (intern-soft cand))
       (alias (car (last (function-alias-p sym t))))
       (name (and (symbolp alias) (symbol-name alias))))
  (format #(" (%s)" 1 5 (face marginalia-function)) name)))

  (defun marginalia-annotate-command-with-alias (cand)
"Annotate command CAND with its documentation string.
  Similar to `marginalia-annotate-symbol', but does not show symbol class."
(when-let (sym (intern-soft cand))
  (concat
   (marginalia-annotate-binding cand)
   (marginalia-annotate-alias cand)
   (marginalia--documentation (marginalia--function-doc sym)))))

  (cl-pushnew #'marginalia-annotate-command-with-alias
      (alist-get 'command marginalia-annotator-registry)))

(use-package all-the-icons-completion
  :after (marginalia all-the-icons)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
  :init
  (all-the-icons-completion-mode))

(use-package consult
  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :bind (("C-c r" . consult-ripgrep)
         ([remap switch-to-buffer] . consult-buffer)
         ("s-i" . consult-buffer)
         :map minibuffer-local-map
         ("s-s" . consult-history)
         ("C-r" . consult-history))
  :custom
  (completion-in-region-function #'consult-completion-in-region))

;; from the consult wiki
(defcustom my/consult-ripgrep-or-line-limit 300000
  "Buffer size threshold for `my/consult-ripgrep-or-line'.
When the number of characters in a buffer exceeds this threshold,
`consult-ripgrep' will be used instead of `consult-line'."
  :type 'integer)

(defun my/consult-ripgrep-or-line ()
  "Call `consult-line' for small buffers or `consult-ripgrep' for large files."
  (interactive)
  (if (or (not buffer-file-name)
          (buffer-narrowed-p)
          (ignore-errors
            (file-remote-p buffer-file-name))
          (jka-compr-get-compression-info buffer-file-name)
          (<= (buffer-size)
              (/ my/consult-ripgrep-or-line-limit
                 (if (eq major-mode 'org-mode) 4 1))))
      (consult-line)
    (when (file-writable-p buffer-file-name)
      (save-buffer))
    (let ((consult-ripgrep-args
           (concat consult-ripgrep-args
                   ;; filter to desired filename
                   " -g "
                   (shell-quote-argument (file-name-nondirectory buffer-file-name))
                   " ")))
      (consult-ripgrep))))

(use-package consult-dir
  :ensure t
  :bind (("C-x C-d" . consult-dir)
         :map minibuffer-local-completion-map
         ("C-x C-d" . consult-dir)
         ("C-x C-j" . consult-dir-jump-file)))

(use-package consult-todo
  :demand t
  :elpaca (:main nil) ; skip dependency check because hl-todos doesn't have version info.
  :custom
  (defconst consult-todo--narrow
  '((?t . "TODO")
    (?f . "FIXME")
    (?d . "DEPRECATED")
    (?b . "BUG")
    (?x . "XXX")
    (?n . "NOTE")
    (?h . "HACK"))
  "Default mapping of narrow and keywords."))

(use-package embark
  :bind
  (("C-c a" . embark-act)))

(use-package embark-consult
  :after (embark consult))

(use-package corfu
  :elpaca (corfu :files (:defaults "extensions/*")
         :includes (corfu-info corfu-history))
  :general
  (:keymaps 'corfu-map
        :states 'insert
        "C-n" #'corfu-next
        "C-p" #'corfu-previous
        "TAB" #'corfu-next
        "S-TAB" #'corfu-previous
        "<escape>" #'corfu-quit)
  :custom
  (corfu-cycle t)
  (corfu-min-width 80)
  (corfu-max-width corfu-min-width) ; always have the same width
  (corfu-preselect 'prompt)
  (corfu-auto t)
  (corfu-auto-delay 0.25)
  (corfu-auto-prefix 2)
  (corfu-popupinfo-delay 0)
  ;; `nil' means to ignore `corfu-separator' behavior, that is, use the older
  ;; `corfu-quit-at-boundary' = nil behavior. Set this to separator if using
  ;; `corfu-auto' = `t' workflow (in that case, make sure you also set up
  ;; `corfu-separator' and a keybind for `corfu-insert-separator', which my
  ;; configuration already has pre-prepared). Necessary for manual corfu usage with
  ;; orderless, otherwise first component is ignored, unless `corfu-separator'
  ;; is inserted.
  (corfu-quit-at-boundary nil)
  :init
  (global-corfu-mode)
  (corfu-popupinfo-mode))

(use-package kind-icon
  :after corfu
  :custom
  (kind-icon-use-icons t)
  ;; No pollution. Change the location of the svg-lib cache directory.
  (svg-lib-icons-dir (no-littering-expand-var-file-name "svg-lib/cache"))
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

(setq-default
 display-time-default-load-average nil            ; Don't display load average
 fill-column 100                                  ; Set column width
 help-window-select t                             ; Focus new help windows when opened
 indent-tabs-mode nil                             ; Prefer spaces over tabs, duh.
 tab-width 4                                      ; Set width for tabs
 kill-ring-max 128                                ; Maximum length of kill ring
 load-prefer-newer t                              ; Prefer the newest version of a file
 mark-ring-max 128                                ; Maximum length of mark ring
 select-enable-clipboard t                        ; Merge system's and Emacs' clipboard
 x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)
 user-full-name "ERick BOdine"                    ; Name
 vc-follow-symlinks t                             ; Always follow the symlinks
 frame-title-format '("Emacs: %f")                ; Frame title
 icon-title-format frame-title-format             ; OS icon title
 message-log-max 8192                             ; Don't lose any logging information.
 bidi-paragraph-separate-re "^"
 bidi-paragraph-start-re "^"
 ring-bell-function 'ignore                       ; Turn off the damn bell!
 history-delete-duplicates t                      ; Remove dups from helm-M-x & such.
 history-length 55                                ; Limit history length; see above.
 view-read-only t)                                ; Always open read-only buffers in view-mode

;; sane trackpad/mouse scroll settings
(when IS-MAC
  (setq mac-redisplay-dont-reset-vscroll t
        mac-mouse-wheel-smooth-scroll nil))

;; Some IO related settings.
;; support reading large blobs of data
(setq process-adaptive-read-buffering nil
      read-process-output-max (* 2048 2048))

;; Reduce rendering/line scan work for Emacs by not rendering cursors or regions
;; in non-focused windows.
(setq-default cursor-in-non-selected-windows nil)
(setq highlight-nonselected-windows nil)

;; More performant rapid scrolling over unfontified regions. May cause brief
;; spells of inaccurate syntax highlighting right after scrolling, which should
;; quickly self-correct.
(setq fast-but-imprecise-scrolling t)
(setq-default scroll-conservatively 101)

;; Resizing the Emacs frame can be a terribly expensive part of changing the
;; font. By inhibiting this, we halve startup times, particularly when we use
;; fonts that are larger than the system default (which would resize the frame).
(setq frame-inhibit-implied-resize t)

;; Don't popup UI/graphical dialog boxes.
(setq use-dialog-box nil)

;; Don't ping things that look like domain names.
(setq ffap-machine-p-known 'reject)

;; Font compacting can be terribly expensive, especially for rendering icon
;; fonts on Windows. Whether it has a noteable affect on Linux and Mac hasn't
;; been determined, but we inhibit it there anyway.
(setq inhibit-compacting-font-caches t)

;; Remove command line options that aren't relevant to our current OS; means
;; slightly less to process at startup.
(unless IS-MAC   (setq command-line-ns-option-alist nil))
(unless IS-LINUX (setq command-line-x-option-alist nil))

;; Make apropos more useful
(setq apropos-do-all t)

;; Silence advised functions warnings
(setq ad-redefinition-action 'accept)

;; Don't pass over `auto-mode-alist' a second time.
(setq auto-mode-case-fold nil)

;; don't ask to kill buffers
(setq kill-buffer-query-functions
      (remq 'process-kill-buffer-query-function
            kill-buffer-query-functions))

;; Get rid of "For information about GNU Emacs..." message at startup
(unless noninteractive
  (advice-add #'display-startup-echo-area-message :override #'ignore)
  (setq inhibit-startup-message t
        inhibit-startup-echo-area-message user-login-name
        inhibit-default-init t
        ;; initial-major-mode 'fundamental-mode
        initial-scratch-message "Welcome to the Church of Emacs, Cardinal deftpunk presiding"
        mode-line-format nil))
;; we're in a daemon session, where it'll say "Starting Emacs daemon." instead
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore))

;; This file stores usernames, passwords, and such.
(setq auth-sources (list (expand-file-name "authinfo.gpg" deftpunk--etc-dir) "~/.authinfo.gpg"))

;; Some timezone stuff for logview.el and others.
(setenv "TZ" "America/Denver")
(setq datetime-timezone "America/Denver")

;; I actually find the custom system a nuisance; move the file out of the way.
(setq custom-file (expand-file-name "custom.el" deftpunk--etc-dir))

;; Replace yes/no prompts with y/n
(fset 'yes-or-no-p 'y-or-n-p)

;; see https://www.emacswiki.org/emacs/BrowseUrl#h5o-7
(after! browse-url
  (setq browse-url-browser-function 'browse-url-chrome
        browse-url-chrome-program "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        browse-url-new-window-flag  t))

;; Don't ask if you want to kill a buffer with a live process attached to it:
(remove-hook 'kill-buffer-query-functions 'process-kill-buffer-query-function)

(after! simple
        ;; The following may be of interest to people who (a) are happy with
        ;; "C-w" and friends for killing and yanking, (b) use
        ;; "transient-mark-mode", (c) also like the traditional Unix tty
        ;; behaviour that "C-w" deletes a word backwards. It tweaks "C-w" so
        ;; that, if the mark is inactive, it deletes a word backwards instead
        ;; of killing the region. Without that tweak, the C-w would create an
        ;; error text without an active region.
        ;; http://www.emacswiki.org/emacs/DefaultKillingAndYanking#toc2

        (defadvice kill-region (before unix-werase activate compile)
          "When called interactively with no active region, delete a single word backwards
           instead."
          (interactive
           (if mark-active (list (region-beginning) (region-end))
             (list (save-excursion (backward-word 1) (point)) (point))))))

;; Deleting past a tab normally changes tab into spaces. Don't do
;; that, kill the tab instead.
(setq backward-delete-char-untabify-method nil)

;; Don't type C-u C-SPC C-u C-SPC to pop 2 marks, now you can do C-u C-SPC C-SPC
(setq set-mark-command-repeat-pop t)

;; Revert buffers when the underlying file has changed.
(global-auto-revert-mode 1)
;; Revert Dired and other buffers
(setq global-auto-revert-non-file-buffers t)

;; no lockfiles
(setq create-lockfiles nil)

(setq-default save-abbrevs 'silently)

;; Turn abbreviations on globally.
(setq-default abbrev-mode t)
(blackout 'abbrev-mode)

;; Read the abbrev file on startup.
(quietly-read-abbrev-file)

;; https://www.emacswiki.org/emacs/BackupDirectory
;; https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files

;; Default and per-save backups go here:
(setq backup-directory-alist '(("" . (expand-file-name "backups" deftpunk--var-dir))))

(defun force-backup-of-buffer ()
  ;; Make a special "per session" backup at the first save of each
  ;; emacs session.
  (when (not buffer-backed-up)
    ;; Override the default parameters for per-session backups.
    (let ((backup-directory-alist '(("" . "~/.emacs.d/backup/per-session")))
          (kept-new-versions 3))
      (backup-buffer)))
  ;; Make a "per save" backup on each save.  The first save results in
  ;; both a per-session and a per-save backup, to keep the numbering
  ;; of per-save backups consistent.
  (let ((buffer-backed-up nil))
    (backup-buffer)))

(add-hook 'before-save-hook  'force-backup-of-buffer)

(setq version-control t              ; Use version numbers for backup
      kept-new-versions 5            ; Number of newest version to keep around
      kept-old-versions 0            ; Number of oldest versions to keep around
      delete-old-versions t          ; Don't ask to delete older versions
      backup-by-copying t            ; Copy all files, don't rename them - best compromise for safety.
      vc-make-backup-files t         ; Even backup files under version control
      )

(column-number-mode 1)

(use-package dired
  :elpaca nil
  :custom
  ;; Allow dired to delete or copy a dir.
  ;; 02/14/24 17:41:48 - These default to 'top in dired now.
  ;; 'top means ask every time.
  ;; 'always means don't ask.
  (dired-recursive-copies 'top)
  (dired-recursive-deletes 'top)
  :config

  ;; Open marked files in dired
  ;; http://xahlee.info/emacs/emacs/emacs_dired_open_marked.html
  (defun xah-dired-open-marked ()
    "Open marked files in `dired'.
URL `http://xahlee.info/emacs/emacs/emacs_dired_open_marked.html'
Version 2019-10-22"
    (interactive)
    (mapc 'find-file (dired-get-marked-files)))

  ;; Make dired open in the same window when using RET or ^
  ;; Make Dired only use a single buffer when visiting a directory.
  ;; http://ergoemacs.org/emacs/emacs_dired_tips.html
  (put 'dired-find-alternate-file 'disabled nil) ; disables warning
  (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file) ; was dired-advertised-find-file
  (define-key dired-mode-map (kbd "^") (lambda ()
                                         (interactive)
                                         (find-alternate-file ".."))))  ; was dired-up-directory

(setq savehist-file (expand-file-name "savehist" deftpunk--var-dir)
      history-length 65                                                ; reducing size helps reduce startup cost.
      history-delete-duplicates t
      savehist-save-minibuffer-history t
      savehist-additional-variables '(kill-ring
                                      search-ring
                                      mark-ring
                                      global-mark-ring
                                      regexp-search-ring
                                      extended-command-history
                                      regexp-search-ring))
(savehist-mode 1)

;; Limit some of the items in savehist
(put 'savehist-minibuffer-history-variables 'history-length 50)
(put 'org-read-date-history                 'history-length 50)
(put 'read-expression-history               'history-length 50)
(put 'org-table-formula-history             'history-length 50)
(put 'extended-command-history              'history-length 50)
(put 'ido-file-history                      'history-length 50)
(put 'helm-M-x-input-history                'history-length 50)
(put 'minibuffer-history                    'history-length 50)
(put 'ido-buffer-history                    'history-length 50)
(put 'buffer-name-history                   'history-length 50)
(put 'file-name-history                     'history-length 50)

(setq save-place-file (expand-file-name "emacs-places" deftpunk--var-dir)
      save-place-forget-unreadable-files nil  ; Setting to t has the potential to make exiting slow
      )
(save-place-mode 1)
(add-hook 'save-place-find-file-hook 'recenter)
(add-hook 'find-file-hook 'save-place-find-file-hook t)

(setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow))
(global-visual-line-mode)
(blackout 'visual-line-mode)

;; Ignore all the *<name>* buffers by regex.
(setq winner-boring-buffers-regexp "^\\*")
(winner-mode +1)

(use-package ace-window
  :bind (("C--" . ace-window))
  :init
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
        aw-leading-char-style 'path
        aw-background t
        aw-dispatch-always t)
  :config
  (set-face-attribute 'aw-leading-char-face nil :height 4.0))

(use-package ace-link
  :init (ace-link-setup-default))

(use-package emacs
  :elpaca nil
  :config
  (defadvice keyboard-escape-quit
      (around keyboard-escape-quit-dont-close-windows activate)
    (let ((buffer-quit-function (lambda () ())))
      ad-do-it)))

(use-package ws-butler
  :elpaca (ws-butler :type git :host github :repo "hlissner/ws-butler")
  :blackout t
  :hook ((text-mode . ws-butler-mode)
         (prog-mode . ws-butler-mode))
  :custom
  (ws-butler-keep-whitespace-before-point nil))

;; show trailing whitespace
(setq show-trailing-whitespace t)

(with-eval-after-load 'ws-butler
  (blackout 'ws-butler-mode))

(use-package devdocs
  :init
  (setq devdocs-data-dir (expand-file-name "devdocs" user-emacs-directory)))

(use-package devdocs-browser
  :commands (devdocs-browser-open)
  :general ("C-h D" #'devdocs-browser-open))

(use-package discover-my-major
  :general
  ("C-h C-m" #'discover-my-major))

(use-package helpful
  :general
  ([remap describe-function]  #'helpful-callable
   [remap describe-command]   #'helpful-command
   [remap describe-variable]  #'helpful-variable
   [remap display-local-help] #'helpful-at-point
   [remap describe-symbol]    #'helpful-symbol
   [remap describe-key]       #'helpful-key
   "C-h x"                    #'helpful-macro))

;; Make all the lines soft-wrap
(use-package org
  :elpaca nil
  :blackout (org-mode . " Org")
  :hook (org-mode . (lambda ()
          (toggle-truncate-lines nil)))
  :general
  (:keymaps 'org-mode-map
        "C-c C-'" 'org-edit-special)
  (:keymaps 'org-src-mode-map
        "C-c C-'" 'org-edit-src-exit)
  :custom
  (org-use-speed-commands t)      ; faster navigation
  (org-fontify-quote-and-verse-blocks t)    ; quote/verse blocks show up better
  (org-return-follows-link t)
  (org-src-fontify-natively t)
  (org-startup-indented t)
  (org-pretty-entities t)
  (org-hide-emphasis-markers t)       ; show italicized text instead of /italicized text/
  (org-startup-with-inline-images t)
  (org-image-actual-width '(300))
  :init
  ;; Load markdown as well as emacs-lisp
  ;; Add/Create function for executing markdown or send to previewer
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)))
  :config
  ;; Moving general bindings here to reduce startup penalty.

  ;; Create a sparse tree view of TODOs in the current Org buffer.
  ;; https://stackoverflow.com/a/63195446
  ;; You can use C-x 4 0 to kill the buffer and window when done.
  (defun org-todo-buffer ()
    "Create new indirect buffer with sparse tree of undone TODO items"
    (interactive)
    (clone-indirect-buffer "*org TODO undone*" t)
    (org-show-todo-tree nil) ; mimics interactive usage
    (org-remove-occur-highlights))

  ;; Keys for org-mode-map
  (general-define-key
   :keymaps 'org-mode-map
   ;; so that C-j actually is mapped to avy-goto-char-timer
   "C-j" 'nil
   "C-k" 'nil
   ;; so that we can use it as help prefix
   "M-h" 'nil)

  ;; Local leader bindings.
  (deftpunk-local-leader-def
    :keymaps 'org-mode-map
    "a" '(org-todo-buffer :which-key "Show TODOs for current buffer.")
    "d" '(org-todo :which-key "Org Todo + Todo States")
    "e" '(org-edit-special :which-key "Edit blk in special buffer")
    "h" '(consult-org-heading :which-key "Org Headers")
    "i" '(org-insert-link :which-key "Org Insert link")
    "n" '(org-babel-next-src-block :which-key "Go to the next src block")
    "o" '(ace-link-org :which-key "Links in Org mode document")
    "p" '(org-babel-previous-src-block :which-key "Go to previous src block")
    "s" '(org-insert-structure-template :which-key "Insert templates")
    "t" '(org-babel-tangle :which-key "Tangle the src blocks")
    "u" '(org-babel-goto-src-block-head :which-key "Go to the head of the src block")
    "x" '(org-open-at-point :which-key "Open link at point")
    "y" '(org-download-screenshot file :which-key "Yank screenshot"))
  )

;; More "keep off my modeline"
(with-eval-after-load 'org-indent
  (blackout 'org-indent-mode))

(use-package org-appear
  :blackout t
  :hook (org-mode . org-appear-mode)
  :custom
  (org-appear-autolinks t)
  (org-appear-autosubmarkers t)
  (org-appear-autoentities t)
  (org-appear-auto-keywards))

(use-package org-auto-tangle
  :hook (org-mode . org-auto-tangle-mode))

;; The joys of hooks and loading.
(with-eval-after-load 'org-auto-tangle
  (blackout 'org-auto-tangle-mode))

;; https://github.com/minad/org-modern/issues/106#issuecomment-1344659316
;; Fixes issue mentioned above
(defun disable-point-adjustment (&rest args)
  (setq disable-point-adjustment t))
(advice-add 'org-beginning-of-line :after #'disable-point-adjustment)

(use-package org-modern
  :blackout
  :after org
  :init
  (setq org-modern-hide-stars nil
        ;; I prefer just the circle
        org-modern-star '("○" "○" "○" "○" "○" "○")
        org-auto-align-tags nil
        org-tags-column 0
        org-catch-invisible-edits 'show-and-error
        org-special-ctrl-a/e t
        org-insert-heading-respect-content t

        ;; Org styling, hide markup etc.
        org-ellipsis "…"

        ;; Agenda styling
        org-agenda-tags-column 0
        org-agenda-block-separator ?─
        org-agenda-time-grid
        '((daily today require-timed)
          (800 1000 1200 1400 1600 1800 2000)
          " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
        org-agenda-current-time-string
        "⭠ now ─────────────────────────────────────────────────")
  :config
  (global-org-modern-mode))

;; From Doom Emacs ui/vc-gutter/config.el
;; UI: make the fringe small enough that the diff bars aren't too domineering,
;;   while leaving enough room for other indicators.
(if (fboundp 'fringe-mode) (fringe-mode '8))
;; UI: the gutter looks less cramped with some space between it and  buffer.
(setq-default fringes-outside-margins t)

(use-package git-gutter
  :blackout t
  :hook ((org-mode . git-gutter-mode)
         (org-src-mode . git-gutter-mode)
         (prog-mode . git-gutter-mode)
         (markdown-mode . git-gutter-mode))
  :custom
  (git-gutter:update-interval 0.05)
  (git-gutter:disabled-modes '(fundamental-mode image-mode pdf-vew-mode))
  ;; Don't go looking for backends I don't use.
  (git-gutter:handled-backends '(git))
  ;; Don't ask to commit/revert
  (git-gutter:ask-p nil)
  :config
  ;; UX: update git-gutter on focus (in case I was using git externally)
  (add-hook 'focus-in-hook #'git-gutter:update-all-windows)

  ;; Stop git-gutter doing things when we don't want
  (remove-hook 'post-command-hook #'git-gutter:post-command-hook)
  (advice-remove #'quit-window #'git-gutter:quit-window)
  (advice-remove #'switch-to-buffer #'git-gutter:switch-to-buffer)

  (defhydra hydra-git-gutter (:body-pre (git-gutter-mode 1)
                                        :hint nil)
    "
 Git gutter:
   _j_: next hunk        _s_tage hunk     _q_uit
   _k_: previous hunk    _r_evert hunk    _Q_uit and deactivate git-gutter
   ^ ^                   _p_opup hunk
   _h_: first hunk
   _l_: last hunk        set start _R_evision
 "
    ("j" git-gutter:next-hunk)
    ("k" git-gutter:previous-hunk)
    ("h" (progn (goto-char (point-min))
                (git-gutter:next-hunk 1)))
    ("l" (progn (goto-char (point-min))
                (git-gutter:previous-hunk 1)))
    ("s" git-gutter:stage-hunk)
    ("r" git-gutter:revert-hunk)
    ("p" git-gutter:popup-hunk)
    ("R" git-gutter:set-start-revision)
    ("q" nil :color blue)
    ("Q" (progn (git-gutter-mode -1)
                ;; git-gutter-fringe doesn't seem to
                ;; clear the markup right away
                (sit-for 0.1)
                (git-gutter:clear))
     :color blue)))

(use-package git-gutter-fringe
  :config
  ;; Make added/modified a bar & deleted a triangle.
  (define-fringe-bitmap 'git-gutter-fr:added [#b11100000] nil nil '(center repeated))
  (define-fringe-bitmap 'git-gutter-fr:modified [#b11100000] nil nil '(center repeated))
  (define-fringe-bitmap 'git-gutter-fr:deleted
    [#b10000000
     #b11000000
     #b11100000
     #b11110000] nil nil 'bottom))

;; Turn off git-gutter in the modeline.
(blackout 'git-gutter-mode)

(use-package git-timemachine
  :config
  (setq git-timemachine-abbreviation-length 14
        git-timemachine-show-minibuffer-details t)
  (elpaca-wait))

;; From redguardtoo - http://blog.binchen.org/posts/new-git-timemachine-ui-based-on-ivy-mode.html
(defun my-git-timemachine-show-selected-revision ()
  "Show last (current) revision of file."
  (interactive)
  (let (collection)
    (setq collection
          (mapcar (lambda (rev)
                    ;; re-shape list for the ivy-read
                    (cons (concat (substring (nth 0 rev) 0 7) "|" (nth 5 rev) "|" (nth 6 rev)) rev))
                  (git-timemachine--revisions)))
    (ivy-read "commits:"
              collection
              :action (lambda (rev)
                        (git-timemachine-show-revision rev)))))

(defun my-git-timemachine ()
  "Open git snapshot with the selected version.  Based on ivy-mode."
  (interactive)
  (unless (featurep 'git-timemachine)
    (require 'git-timemachine))
  (git-timemachine--start #'my-git-timemachine-show-selected-revision))

(use-package magit
  :commands (magit-dispatch)
  :general
  (:prefix "C-x"
           "g" 'magit-status
           "C-g" 'magit-status)
  :hook (git-commit-setup-hook . git-commit-turn-on-flyspell)
  :init
  (if IS-MAC
      (setq magit-git-executable "/opt/homebrew/bin/git")
    (setq magit-git-executable "/usr/local/bin/git"))
  :config
  ;; Add git-timemachine to the magit-dispatch transient map.
  (transient-append-suffix 'magit-dispatch '(0 -1 -1) '("S" "git timemachine" git-timemachine))

  (setq  magit-log-arguments '("--graph" "--decorate" "--color")
         magit-revert-buffers 'silent
         magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")
         magit-diff-refine-hunk t ; show granular diffs in selected hunk
         ;; Don't autosave repo buffers. This is too magical, and saving can
         ;; trigger a bunch of unwanted side-effects, like save hooks and
         ;; formatters. Trust us to know what we're doing.
         magit-save-repository-buffers nil))

(use-package forge
  :after magit)

(use-package magit-todos
  :after magit
  :config
  (magit-todos-mode +1))

(use-package conda
  :after python
  :config
  ;; taken from doom
  ;; The location of your anaconda home will be guessed from a list of common
  ;; possibilities, starting with `conda-anaconda-home''s default value (which
  ;; will consult a ANACONDA_HOME envvar, if it exists).
  ;;
  ;; If none of these work for you, `conda-anaconda-home' must be set
  ;; explicitly. Afterwards, run M-x `conda-env-activate' to switch between
  ;; environments
  (or (cl-loop for dir in (list conda-anaconda-home
                                "~/.miniconda3"
                                "~/.conda")
               if (file-directory-p dir)
               return (setq conda-anaconda-home (expand-file-name dir)
                            conda-env-home-directory (expand-file-name dir)))
      (message "Cannot find Anaconda installation"))
  ;; integration with term/eshell
  (conda-env-initialize-interactive-shells)
  (after! eshell (conda-env-initialize-eshell))

  ;; auto-activation (see below for details)
  ;; (conda-env-autoactivate-mode t)
  ;; automatically activate a conda environment on the opening of a file:
  ;; (add-hook 'find-file-hook (lambda () (when (and (bound-and-true-p conda-project-env-path) (string-match "\\.py\\'" buffer-file-name))
  ;;                                       (conda-env-activate-for-buffer))))

  ;; Add to the modeline so that we know which env is activated.
  (add-to-list 'global-mode-string
               '(conda-env-current-name (" conda:" conda-env-current-name " "))
               'append))

(use-package markdown-mode
  :defer t
  :commands (markdown-mode gfm-mode)
  :hook (markdown-mode . flyspell-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'"       . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init
  (setq markdown-command "/opt/homebrew/bin/multimarkdown"
        markdown-header-scaling t)
  )

(use-package vterm
  :ensure t
  :hook
  ;; Change the face so its more obvious we are in an emulator.
  (vterm-mode . (lambda ()
                  (set (make-local-variable 'buffer-face-mode-face) 'fixed-pitch)
                  (buffer-face-mode t)))
  :custom
  (vterm-always-compile-module t)
  (vterm-max-scrollback 100000)               ; the max without changing vterm-module.h and re-compiling
  (vterm-copy-mode-remove-fake-newlines t))

;; Trying out matching parens
;; https://www.gnu.org/software/emacs/manual/html_node/efaq/Matching-parentheses.html
(defun match-paren (arg)
  "Go to the matching paren if on a paren; otherwise insert %."
  (interactive "p")
  (cond ((looking-at "\\s(") (forward-list 1) (backward-char 1))
        ((looking-at "\\s)") (forward-char 1) (backward-list 1))
        (t (self-insert-command (or arg 1)))))

(global-set-key "%" 'match-paren)

;; Some final remapping of Escape to "Quit"

(global-set-key (kbd "<escape>") 'keyboard-quit)

;; When C-g gets rebound.
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))

(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)

(defun ora-ex-point-mark ()
  (interactive)
  (if rectangle-mark-mode
      (exchange-point-and-mark)
    (let ((mk (mark)))
      (rectangle-mark-mode 1)
      (goto-char mk))))

(defhydra hydra-rectangle (:body-pre (rectangle-mark-mode 1)
                           :color pink
                           :post (deactivate-mark))
  "
  ^_k_^     _d_elete    _s_tring     |\\     ‗,,,--,,‗
_h_   _l_   _o_k        _y_ank       /,`.-'`'   .‗  \-;;,‗
  ^_j_^     _n_ew-copy  _r_eset     |,4-  ) )‗   .;.(  `'-'
^^^^        _e_xchange  _u_ndo     '---''(‗/.‗)-'(‗\‗)
^^^^        ^ ^         _p_aste
"
  ("h" backward-char nil)
  ("l" forward-char nil)
  ("k" previous-line nil)
  ("j" next-line nil)
  ("e" ora-ex-point-mark nil)
  ("n" copy-rectangle-as-kill nil)
  ("d" delete-rectangle nil)
  ("r" (if (region-active-p)
           (deactivate-mark)
         (rectangle-mark-mode 1)) nil)
  ("y" yank-rectangle nil)
  ("u" undo nil)
  ("s" string-rectangle nil)
  ("p" kill-rectangle nil)
  ("o" nil nil))

(global-set-key (kbd "C-x SPC") 'hydra-rectangle/body)

;; NOTE: The org-open-at-point will open a "Babel Results" window when this function is called
;;       inside a src block
(defun deftpunk/url-at-point ()
  "Make opening the url at point a little more flexible."
  (interactive)
  (if (string-equal major-mode "org-mode")
      (unless (ignore-errors (or (org-open-at-point) t))
        (ace-link))
    (unless (ignore-errors (or (browse-url-at-point) t))
      (ace-link))))

(general-create-definer deftpunk-g-def
  :keymaps 'override
  :prefix "s-g"
  "g" goto-line
  "s-g" goto-line
  "o" ace-link
  "x" deftpunk/url-at-point
  )

(global-set-key (kbd "C--") 'ace-window)

;; Move around
(global-set-key (kbd "s-h") 'windmove-left)
(global-set-key (kbd "s-j") 'windmove-down)
(global-set-key (kbd "s-k") 'windmove-up)
(global-set-key (kbd "s-l") 'windmove-right)

(defalias 'ff 'find-file)

;; Using C-j for jumping around.
(global-unset-key (kbd "C-j"))
(global-set-key (kbd "C-j") 'avy-goto-char-timer)
(global-set-key (kbd "s-f") 'avy-goto-char-in-line)

(global-set-key (kbd "s-s") 'my/consult-ripgrep-or-line)

;; Figure out hippie-expand
;; From https://stackoverflow.com/a/43665319
(defun my-expand-lines ()
  "My old friend C-x C-l in Emacs"
  (interactive)
  (let ((hippie-expand-try-functions-list
     '(try-expand-line)))
    (call-interactively 'hippie-expand)))

(global-unset-key (kbd "C-x C-l")) ; I can downcase the region another way.
(global-set-key (kbd "C-x C-l") 'my-expand-lines)

(defun deftpunk/current-time ()
  (interactive)
  (insert (format-time-string "%D %T")))
(define-abbrev global-abbrev-table "ydate" "" 'deftpunk/current-time)

(use-package key-chord
  :commands (key-chord-define-global)
  :init
  (key-chord-mode 1)

(key-chord-define-global "jk" 'execute-extended-command)
(key-chord-define-global "hh" 'split-window-below)
(key-chord-define-global "vv" 'split-window-right))
