;;; init.el --- deftpunk Emacs config file -*- lexical-binding: t; buffer-read-only: t -*-
;;;
;;; Commentary:
;;; Emacs `init.el' config for deftpunk
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in emacs.d/deftpunk-emacs.org
;;;
;;; Code:

(defconst deftpunk--emacs-dir (file-truename "~/.emacs.d")
  "The path to the emacs.d directory")

(defconst deftpunk--org-configuration-file (concat deftpunk--emacs-dir "/deftpunk-emacs.org")
  "The Org mode literate configuration file.")

(defconst deftpunk--etc-dir (concat deftpunk--emacs-dir "/etc/")
  "Location for files to save across systems.")

(defconst deftpunk--var-dir (concat deftpunk--emacs-dir "/var/")
  "Location for cache & files that we don't save across systems.")

;; I use Mac & occasionally Linux, no Windoze.
(defconst IS-MAC (eq system-type 'darwin))
(defconst IS-LINUX (eq system-type 'gnu/linux))

(defvar elpaca-installer-version 0.7)
(defvar elpaca-directory (expand-file-name "elpaca/" deftpunk--var-dir))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;; Install a package via the elpaca macro
;; See the "recipes" section of the manual for more details.

;; (elpaca example-package)

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;; Expands to: (elpaca evil (use-package evil :demand t))
;; (use-package evil :demand t)

;;Turns off elpaca-use-package-mode current declaration
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
;; (use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
;; (elpaca nil (message "deferred"))

(use-package general)

(elpaca-wait)

;; Leader key
(general-create-definer deftpunk-leader-def
  :keymaps 'override
  :prefix "s-SPC")

;; local leader
;; This allows for finer granularity than hydra-major-mode by binding to individual key maps.
(general-create-definer deftpunk-local-leader-def
  :keymaps 'override
  :prefix "C-;")

(use-package blackout)
(elpaca-wait)

(use-package on
  :ensure (:host github :repo "ajgrf/on.el")
  :config
  (elpaca-wait)
  (require 'on))

(use-package which-key
  :blackout
  :commands (which-key-mode which-key-show-toplevel)
  :hook (on-first-input . which-key-mode)
  :custom
  (which-key-enable-exteded-define-key t)
  (which-key-idle-delay 0.5)
  :config
  (elpaca-wait)
  (which-key-mode +1))

(use-package hydra)
(elpaca-wait)

(use-package major-mode-hydra
;  :straight (major-mode-hydra :type git :host github :repo "jerrypnz/major-mode-hydra.el")
  :init
  ;; Set the default major-mode-hydra title using all-the-icons icon
  ;; for the major mode.  THis is just in case we don't use any of the
  ;; "with=*" functions below.
  (setq major-mode-hydra-title-generator
    '(lambda (mode)
       (s-concat "\n"
                 (s-repeat 10 " ")
                 (all-the-icons-icon-for-mode mode :v-adjust 0.05)
                 " "
                 (symbol-name mode)
                 ""))))

;; A bunch of utility functions from https://gist.github.com/mbuczko/e15d61363d31cf78ff17427072e0c325
(defun with-faicon (icon str &optional height v-adjust)
  (s-concat (all-the-icons-faicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun with-fileicon (icon str &optional height v-adjust)
  (s-concat (all-the-icons-fileicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun with-octicon (icon str &optional height v-adjust)
  (s-concat (all-the-icons-octicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun with-material (icon str &optional height v-adjust)
  (s-concat (all-the-icons-material icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

(defun with-mode-icon (mode str &optional height nospace face)
  (let* ((v-adjust (if (eq major-mode 'emacs-lisp-mode) 0.0 0.05))
         (args     `(:height ,(or height 1) :v-adjust ,v-adjust))
         (_         (when face
                      (lax-plist-put args :face face)))
         (icon     (apply #'all-the-icons-icon-for-mode mode args))
         (icon     (if (symbolp icon)
                       (apply #'all-the-icons-octicon "file-text" args)
                     icon)))
    (s-concat icon (if nospace "" " ") str)))

(use-package transient :ensure t)
(elpaca-wait)

;;; Some convenience macros from our favorite martian - Doom Emacs creator Henrik Lissner ;;;

;; 4/22/2020 - In after! below, I removed the check to see if the package was
;; in the list of doom-disabled-packages
(defmacro after! (package &rest body)
  "Evaluate BODY after PACKAGE have loaded.

    PACKAGE is a symbol or list of them. These are package names, not modes,
    functions or variables. It can be:

    - An unquoted package symbol (the name of a package)
        (after! helm BODY...)
    - An unquoted list of package symbols (i.e. BODY is evaluated once both magit
      and git-gutter have loaded)
        (after! (magit git-gutter) BODY...)
    - An unquoted, nested list of compound package lists, using any combination of
      :or/:any and :and/:all
        (after! (:or package-a package-b ...)  BODY...)
        (after! (:and package-a package-b ...) BODY...)
        (after! (:and package-a (:or package-b package-c) ...) BODY...)
      Without :or/:any/:and/:all, :and/:all are implied.

    This is a wrapper around `eval-after-load' that:

    1. Suppresses warnings for disabled packages at compile-time
    2. No-ops for package that are disabled by the user (via `package!')
    3. Supports compound package statements (see below)
    4. Prevents eager expansion pulling in autoloaded macros all at once"
  (declare (indent defun) (debug t))
  (if (symbolp package)
      (list (if (or (not (bound-and-true-p byte-compile-current-file))
                    (require package nil 'noerror))
                #'progn
              #'with-no-warnings)
            (let ((body (macroexp-progn body)))
              `(if (featurep ',package)
                   ,body
                 ;; We intentionally avoid `with-eval-after-load' to prevent
                 ;; eager macro expansion from pulling (or failing to pull) in
                 ;; autoloaded macros/packages.
                 (eval-after-load ',package ',body))))
    (let ((p (car package)))
      (cond ((not (keywordp p))
             `(after! (:and ,@package) ,@body))
            ((memq p '(:or :any))
             (macroexp-progn
              (cl-loop for next in (cdr package)
                       collect `(after! ,next ,@body))))
            ((memq p '(:and :all))
             (dolist (next (cdr package))
               (setq body `((after! ,next ,@body))))
             (car body))))))

(defmacro appendq! (sym &rest lists)
  "Append LISTS to SYM in place."
  `(setq ,sym (append ,sym ,@lists)))

;; TODO: Need the doom-enlist function definition for this to work.
;;  (defmacro defadvice! (symbol arglist &optional docstring &rest body)
;;    "Define an advice called SYMBOL and add it to PLACES.
;;
;;    ARGLIST is as in `defun'. WHERE is a keyword as passed to `advice-add', and
;;    PLACE is the function to which to add the advice, like in `advice-add'.
;;    DOCSTRING and BODY are as in `defun'.
;;
;;    \(fn SYMBOL ARGLIST &optional DOCSTRING &rest [WHERE PLACES...] BODY\)"
;;    (declare (doc-string 3) (indent defun))
;;    (unless (stringp docstring)
;;      (push docstring body)
;;      (setq docstring nil))
;;    (let (where-alist)
;;      (while (keywordp (car body))
;;        (push `(cons ,(pop body) (doom-enlist ,(pop body)))
;;              where-alist))
;;      `(progn
;;         (defun ,symbol ,arglist ,docstring ,@body)
;;         (dolist (targets (list ,@(nreverse where-alist)))
;;           (dolist (target (cdr targets))
;;             (advice-add target (car targets) #',symbol))))))
;;
;;  (defmacro delq! (elt list &optional fetcher)
;;    "`delq' ELT from LIST in-place.
;;      If FETCHER is a function, ELT is used as the key in LIST (an alist)."
;;    `(setq ,list
;;           (delq ,(if fetcher
;;                      `(funcall ,fetcher ,elt ,list)
;;                    elt)
;;                 ,list)))

;; There are certain buffers I don't want to delete on accident.
;; Code taken from https://github.com/rememberYou/.emacs.d/blob/master/config.org
(defvar *protected-buffers* '("*scratch*" "*Messages*"))

(defun arco/protected-buffers ()
  "Protects some buffers from being killed."
  (dolist (buffer *protected-buffers*)
    (if (get-buffer buffer)
        (with-current-buffer buffer
          (emacs-lock-mode 'kill))
      (get-buffer-create buffer)
      (with-current-buffer buffer
        (emacs-lock-mode 'kill)))))

(general-add-hook 'emacs-startup-hook #'arco/protected-buffers)

  ;;;###autoload
;; https://stackoverflow.com/questions/251908/how-can-i-insert-current-date-and-time-into-a-file-using-emacs
(defun today ()
  "Insert string for today's date nicely formatted in American style,
  e.g. Sunday, September 17, 2000."
  (interactive)                 ; permit invocation in minibuffer
  (insert (format-time-string "%A, %B %e, %Y")))

  ;;;###autoload
(defun flex//kill-current-buffer ()
  "What it says."
  (interactive)
  (kill-buffer (current-buffer)))

(defun vim-return ()
  "Still want Return to do the right thing in dired mode."
  (interactive)
  (if (eq major-mode 'dired-mode)
      (dired-find-file)
    (progn
      (next-line)
      (back-to-indentation-or-beginning))))

;; not broken, toggle letter case from
;; http://ergoemacs.org/emacs/modernization_upcase-word.html][xah]] originally.
;; http://stackoverflow.com/questions/18257573/how-to-toggle-letter-cases-in-a-region-in-emacs
(defun toggle-letter-case ()
  "Toggle the letter case of current word or text selection.
   Toggles between: “all lower”, “Init Caps”, “ALL CAPS”."
  (interactive)
  (let (p1 p2 (deactivate-mark nil) (case-fold-search nil))
    (if (region-active-p)
        (setq p1 (region-beginning) p2 (region-end))
      (let ((bds (bounds-of-thing-at-point 'word) ) )
        (setq p1 (car bds) p2 (cdr bds)) ) )
    (when (not (eq last-command this-command))
      (save-excursion
        (goto-char p1)
        (cond
         ((looking-at "[[:lower:]][[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]][[:upper:]]") (put this-command 'state "all caps") )
         ((looking-at "[[:upper:]][[:lower:]]") (put this-command 'state "init caps") )
         ((looking-at "[[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]]") (put this-command 'state "all caps") )
         (t (put this-command 'state "all lower") ) ) ) )
    (cond
     ((string= "all lower" (get this-command 'state))
      (upcase-initials-region p1 p2) (put this-command 'state "init caps"))
     ((string= "init caps" (get this-command 'state))
      (upcase-region p1 p2) (put this-command 'state "all caps"))
     ((string= "all caps" (get this-command 'state))
      (downcase-region p1 p2) (put this-command 'state "all lower")) )
    ) )

;;
(defun deftpunk/catch-error-p (func-symbol)
  "Call the passed function solely for the purpose of catching its error."
  (let (retval)
    (condition-case error
        (funcall func-symbol)
      ('error (setq retval error)))
    retval))

;; Full history of this function is foggy and lost to time.
;; https://stackoverflow.com/questions/234963/re-open-scratch-buffer-in-emacs
(defun eme-goto-scratch ()
            "this sends you to the scratch buffer"
            (interactive)
            (let ((eme-scratch-buffer (get-buffer-create "*scratch*")))
    (switch-to-buffer eme-scratch-buffer)
    (lisp-interaction-mode)))

;; Some more excellence from karthinks.
(defun repeated-prefix-help-command ()
  (interactive)
  (when-let* ((keys (this-command-keys-vector))
              (prefix (seq-take keys (1- (length keys))))
              (orig-keymap (key-binding prefix 'accept-default))
              (keymap (copy-keymap orig-keymap))
              (exit-func (set-transient-map keymap t #'which-key-abort)))
    (define-key keymap [remap keyboard-quit]
                (lambda () (interactive) (funcall exit-func)))
    (which-key--create-buffer-and-show nil keymap)))
(setq prefix-help-command #'repeated-prefix-help-command)

;; https://github.com/daut/dotfiles/blob/2ad4f5a5e0f1e786c91f17460d8599ec5d57318b/.emacs.d/init.el#L236C1-L241C47
(defun daut/print-current-theme ()
  "Print the currently active theme."
  (interactive)
  (if custom-enabled-themes
      (message "Current theme: %s" (car custom-enabled-themes))
    (message "No theme is currently active")))

(use-package no-littering
  :custom
  (no-littering-etc-directory deftpunk--etc-dir)
  (no-littering-var-directory deftpunk--var-dir)
  (auto-save-file-name-transforms
   `((".*" ,(expand-file-name "auto-save/" no-littering-var-directory) t))))

(elpaca-wait) ; So that other packages know where some Emacs system files are.

(use-package crux
  :bind (("C-a" . crux-move-beginning-of-line)
         ("C-k" . crux-smart-kill-line)
         ("s-o" . crux-smart-open-line-above)
         ("s-RET" . crux-smart-open-line)))

(use-package yasnippet-snippets)

(use-package yasnippet
  :hook (prog-mode-hook . yas-minor-mode)
  :custom
  (yas-verbosity 3)
  (yas-also-auto-indent-first-line t)
  :init
  ;; Remove default ~/.emacs.d/snippets
  ;; (defvar yas-snippet-dirs nil)

  :config
  ;; Allow private snippets.
  (add-to-list 'yas-snippet-dirs (expand-file-name "snippets" user-emacs-directory))
;; Only way I could get this to work.
(require 'yasnippet)
(yas-global-mode 1)

  )

;;(elpaca-wait)

(use-package markdown-mode
  :defer t
  :after (magit forge lsp-mode)
  :commands (markdown-mode gfm-mode)
  :hook (markdown-mode . flyspell-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'"       . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :custom
  (markdown-command "/opt/homebrew/bin/multimarkdown")
  (markdown-header-scaling t))

(use-package magit
  :hook ((git-commit-setup-hook . git-commit-turn-on-flyspell)
         (git-commit-setup-hook . git-commit-save-message)
         (git-commit-setup-hook . turn-on-auto-fill))
  :init
  (if IS-MAC
      (setq magit-git-executable "/opt/homebrew/bin/git")
    (setq magit-git-executable "/usr/local/bin/git"))
  :config
  ;; Add git-timemachine to the magit-dispatch transient map.
  (transient-append-suffix 'magit-dispatch '(0 -1 -1) '("S" "git timemachine" git-timemachine))

  (setq  magit-log-arguments '("--graph" "--decorate" "--color")
         magit-revert-buffers 'silent
         magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")
         magit-diff-refine-hunk t ; show granular diffs in selected hunk
         ;; Don't autosave repo buffers. This is too magical, and saving can
         ;; trigger a bunch of unwanted side-effects, like save hooks and
         ;; formatters. Trust us to know what we're doing.
         magit-save-repository-buffers nil)

  ;; Open magit-status in entire window & restore the previous window config on close.
  (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1
        magit-bury-buffer-function 'magit-restore-window-configuration))

(use-package forge
  :after magit)

(use-package magit-delta
  :after magit
  :hook (magit-mode . magit-delta-mode))

(use-package magit-todos
  :after magit
  :config
  (magit-todos-mode +1))

(set-face-attribute 'default nil :font "Menlo" :height 120)
;;(set-face-attribute 'default nil :font "Victor Mono" :height 110)
(set-fontset-font t nil "Menlo" nil 'append) ; fallback font

(use-package all-the-icons)

(use-package all-the-icons-dired
  :config
  :hook (dired-mode . (lambda ()
                        (interactive)
                        (unless (file-remote-p default-directory)
                          (all-the-icons-dired-mode)))))

(use-package nerd-icons
  :ensure t)

(use-package beacon
  :custom
  (beacon-lighter "")
  (beacon-size 45)
  :config
  (beacon-mode 1))

(use-package highlight-numbers
  :hook (prog-mode . highlight-numbers-mode)
  :config
  ;; setting to magenta-warmer for ef-spring theme.
  (set-face-attribute 'highlight-numbers-number nil :foreground "#cb26a0"))

(use-package hl-todo
  :ensure (hl-todo :depth nil) ; see https://github.com/alphapapa/magit-todos/issues/171
  :init
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces '(("TODO" . "#FF0000")
                                ("FIXME" . "#FF9999")
                                ("FAIL" . "#FF0000")
                                ("DEPRECATED" . "#1F39EF")
                                ("HACK" . "#FF0000")
                                ("XXX" . "#FF0000")
                                ("NOTE" . "#1E90FF")))
  :hook (prog-mode . hl-todo-mode))

(use-package solaire-mode
  :config
  (solaire-global-mode +1))

(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-vibrant t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)

  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less minimal icon theme
  (doom-themes-treemacs-config)

  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config)
  )
(face-spec-set 'tree-sitter-hl-face:method\.call '((t (:inherit tree-sitter-hl-face:function\.call :foreground "red"))))

(use-package doom-modeline
  :custom
  (doom-modeline-buffer-file-name-style 'truncate-upto-root)
  (doom-modeline-buffer-name t)
  (doom-modeline-vcs-max-length 35)
  (doom-modeline-icon t)
  (doom-modeline-display-default-persp-name t)
  :init
  (doom-modeline-mode 1)
  :config
  (setq inhibit-compacting-font-caches t) ;; Don´t compact font caches during GC

  ;; This in combination w/ reducing the height allows everything to fit on the modeline.
  (setq nerd-icons-scale-factor 1.1)

  (unless (eq system-type 'darwin)
    (if (facep 'mode-line-active)
        (set-face-attribute 'mode-line-active nil
                            :family "Hack"
                            :height 100) ; For 29+
      (set-face-attribute 'mode-line nil
                          :family "Hack"
                          :height 100))
    (set-face-attribute 'mode-line-inactive nil
                        :family "Hack"
                        :height 100))

  (when (eq system-type 'darwin)
    (if (facep 'mode-line-active)
        (set-face-attribute 'mode-line-active nil
                            :family "Hack Nerd Font"
                            :height 110) ; For 29+
      (set-face-attribute 'mode-line nil
                          :family "Hack Nerd Font"
                          :height 110))
    (set-face-attribute 'mode-line-inactive nil
                        :family "Hack Nerd Font"
                        :height 110)))

(use-package hide-mode-line
  :ensure (:host github :repo "hlissner/emacs-hide-mode-line" :main "hide-mode-line.el")
  :hook ((completion-list-mode . hide-mode-line-mode))
  :config
  (hide-mode-line-mode))

(use-package rainbow-delimiters
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))

(use-package avy
  :defer t
  :config
  (setq avy-all-windows nil
        avy-background t))

;; https://github.com/daut/dotfiles/blob/2ad4f5a5e0f1e786c91f17460d8599ec5d57318b/.emacs.d/init.el#L105
(defun daut/minibuffer-backward-kill (arg)
  (interactive "p")
  (if (and minibuffer-completing-file-name
	   (eq (char-before) ?/))
      (zap-up-to-char (- arg) ?/)
    (delete-backward-char arg)))

(use-package vertico
  :ensure t
  :general
  (:keymaps 'vertico-map
	    "<backspace>" #'daut/minibuffer-backward-kill
	    "<escape>" #'minibuffer-keyboard-quit
	    "C-w" #'backward-kill-word)
  :custom
  (vertico-cycle t)
  (vertico-count 45)
  (vertico-resize t)  ; allow vertico size to shrink and grow based on vertico count
  :init
  (vertico-mode t))

(use-package vertico-posframe
  :ensure t
  :init (vertico-posframe-mode)
  :config
  (setq vertico-multiform-commands
	'((consult-line (:not posframe))
	  (consult-ripgrep (:not posframe))
	  (t posframe)))
  (vertico-multiform-mode t))

(use-package marginalia
  :ensure t
  :general
  (:keymaps 'minibuffer-local-map
            "s-a" 'marginalia-cycle)
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'left)
  :init
  (marginalia-mode 1))

(use-package orderless
  :ensure t
  :custom
  (completion-category-defaults nil)
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic-remote ; For 'tramp' hostname completion
						 partial-completion)))))

(use-package consult
  :ensure t
  :bind (("C-c r" . consult-ripgrep)
         ("s-i" . consult-buffer)
         ("s-r" . consult-ripgrep)
         ;; Misc bindings
         ("s-y" . consult-yank-pop))

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)

  :config
  ;; Preview
  ;; (setq consult-preview-key "s-.")

  ;; Narrowing
  (setq consult-narrow-key "<") ; Prefix key for narrowing results
  (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help) ; get help for narrowing

  ;; Using project.el for project support.
  ;; (setq consult-project-function #'consult--default-project--function))
  )

(use-package flycheck
  :hook (prog-mode . global-flycheck-mode)
  :general
  (:keymaps 'flycheck-mode-map
            "M-n" 'flycheck-next-error
            "M-p" 'flycheck-previous-error))

(use-package consult-flycheck
  :after flycheck)

(use-package consult-git-log-grep
  :ensure t
  :custom
  (consult-git-log-grep-open-function #'magit-show-commit))

(use-package consult-tramp
  :ensure (consult-tramp :type git :host github :repo "Ladicle/consult-tramp")
  :config
  (setq consult-tramp-extra-targets '("/ssh:cxo-vdt8-567.cxo.storage.hpecorp.net:/data/workspace/")))

;; https://github.com/agzam/browser-hist.el
(use-package browser-hist
  :init
  ;; (require 'embark) ; load Embark before the command (if you're using it)
  :config
  (setq browser-hist-default-browser 'chrome)
  :commands (browser-hist-search))

(elpaca-wait)

(use-package consult-omni
  :ensure (consult-omni :type git :host github :repo "armindarvish/consult-omni" :branch "main" :files (:defaults "sources/*.el"))
  :after consult
  :custom

  ;;; General settings that apply to all sources

  (consult-omni-show-preview t) ;;; show previews
  (consult-omni-preview-key "C-o") ;;; set the preview key to C-o
  (consult-omni-highlight-matches-in-minibuffer t) ;;; highlight matches in minibuffer
  (consult-omni-highlight-matches-in-file t) ;;; highlight matches in files
  (consult-omni-default-count 5) ;;; set default count
  (consult-omni-default-page 0) ;;; set the default page (default is 0 for the first page)

  ;; optionally change the consult-omni debounce, throttle and delay.
  ;; Adjust these (e.g. increase to avoid hiting a source (e.g. an API) too frequently)
  (consult-omni-dynamic-input-debounce 0.8)
  (consult-omni-dynamic-input-throttle 1.6)
  (consult-omni-dynamic-refresh-delay 0.8)

  ;; Optionally set backend for http request (either 'url, 'request, or 'plz)
  (consult-omni-http-retrieve-backend 'plz)
  (setq consult-omni-log-level 'debug)


  :config

  ;;; Load Sources Core code
  (require 'consult-omni-sources)

  ;;; Load Embark Actions
  (require 'consult-omni-embark)

  ;;; Either load all source modules or a selected list
  ;; Select a list of modules you want to aload, otherwise all sources all laoded
  ; (setq consult-omni-sources-modules-to-load (list 'consult-omni-wkipedia 'consult-omni-notes))
  (consult-omni-sources-load-modules)

  ;; set multiple sources for consult-omni-multi command. Change these lists as needed for different interactive commands. Keep in mind that each source has to be a key in `consult-omni-sources-alist'.
  (setq consult-omni-multi-sources '("calc"
                                     ;; "File"
                                     ;; "Buffer"
                                     ;; "Bookmark"
                                     "Apps"
                                     ;; "gptel"
                                     "Brave"
                                     "Dictionary"
                                     ;; "Google"
                                     "Wikipedia"
                                     "elfeed"
                                     ;; "mu4e"
                                     ;; "buffers text search"
                                     "Notes Search"
                                     "Org Agenda"
                                     "GitHub"
                                     ;; "YouTube"
                                     "Invidious"))

  ;;; Per source customization

  ;; Set API KEYs. It is recommended to use a function that returns the string for better security.
  (setq consult-omni-google-customsearch-key "YOUR-GOOGLE-API-KEY-OR-FUNCTION")
  (setq consult-omni-google-customsearch-cx "YOUR-GOOGLE-CX-NUMBER-OR-FUNCTION")
  (setq consult-omni-brave-api-key "YOUR-BRAVE-API-KEY-OR-FUNCTION")
  (setq consult-omni-stackexchange-api-key "YOUR-STACKEXCHANGE-API-KEY-OR-FUNCTION")
  (setq consult-omni-pubmed-api-key "YOUR-PUBMED-API-KEY-OR-FUNCTION")
  (setq consult-omni-openai-api-key "YOUR-OPENAI-API-KEY-OR-FUNCTION")
  ;; add more keys as needed here.

  ;; gptel settings
  (setq consult-omni-gptel-cand-title #'consult-omni--gptel-make-title-short-answer)

  ;; default terminal
  (setq consult-omni-embark-default-term #'vterm)

  ;; default video player
  (setq consult-omni-embark-video-default-player  #'mpv-play-url)

  ;; pretty prompt for launcher
  (setq consult-omni-open-with-prompt "  ")

  ;;; Pick you favorite autosuggest command.
  (setq consult-omni-default-autosuggest-command #'consult-omni-dynamic-brave-autosuggest) ;;or any other autosuggest source you define

  ;;; Set your shorthand favorite interactive command
  (setq consult-omni-default-interactive-command #'consult-omni-multi)

  ;;; Optionally Set back-end for notes search to ripgrep-all (requires ripgrep-all)
  ;; (setq consult-omni-notes-backend-command "rga")

  ;;; Optionally add more interactive commands

  ;; consult-omni-web
  (defvar consult-omni-web-sources (list "gptel"
                                         "Brave"
                                         "elfeed"
                                         "mu4e"
                                         "Wikipedia"
                                         "GitHub"
                                         "Invidious"
                                         ))
  (defun consult-omni-web (&optional initial prompt sources no-callback &rest args)
    "Interactive web search”

This is similar to `consult-omni-multi', but runs the search on
web sources defined in `consult-omni-web-sources'.
See `consult-omni-multi' for more details.
"
    (interactive "P")
    (let ((prompt (or prompt (concat "[" (propertize "consult-omni-web" 'face 'consult-omni-prompt-face) "]" " Search:  ")))
          (sources (or sources consult-omni-web-sources)))
      (consult-omni-multi initial prompt sources no-callback args)))

  ;; consult-omni-local
  (defvar consult-omni-local-sources (list "ripgrep"
                                           "mdfind"
                                           "Notes Search"
                                           "Apps"
                                           "Org Agenda"))
  (defun consult-omni-local (&optional initial prompt sources no-callback &rest args)
    "Interactive local search”

This is similar to `consult-omni-multi', but runs the search on
local sources defined in `consult-omni-local-sources'.
See `consult-omni-multi' for more details.
"
    (interactive "P")
    (let ((prompt (or prompt (concat "[" (propertize "consult-omni-local" 'face 'consult-omni-prompt-face) "]" " Search:  ")))
          (sources (or sources consult-omni-local-sources)))
      (consult-omni-multi initial prompt sources no-callback args)))

  ;; consult-omni-scholar
  (setq consult-omni-scholar-sources (list "PubMed" "Scopus" "Notes Search" "gptel"))

  (defun consult-omni-scholar (&optional initial prompt sources no-callback &rest args)
    "Interactive “multi-source acadmic literature” search

This is similar to `consult-omni-multi', but runs the search on
academic literature sources defined in `consult-omni-scholar-sources'.
See `consult-omni-multi' for more details.
"
    (interactive "P")
    (let ((prompt (or prompt (concat "[" (propertize "consult-omni-multi" 'face 'consult-omni-prompt-face) "]" " Search:  ")))
          (sources (or sources consult-omni-scholar-sources)))
      (consult-omni-multi initial prompt sources no-callback args)))

  ;; AutoSuggest at point
  (defun consult-omni-autosuggest-at-point ()
  (interactive)
  (let ((input (or (thing-at-point 'url) (thing-at-point 'filename) (thing-at-point 'symbol) (thing-at-point 'sexp) (thing-at-point 'word))))
    (when (and (minibuffer-window-active-p (selected-window))
               (equal (substring input 0 1) (consult--async-split-initial nil)))
      (setq input (substring input 1)))
    (consult-omni-brave-autosuggest input))))

(use-package consult-yasnippet
  :after yasnippet)

(use-package embark
  :ensure t
  :bind (("C-." . embark-act)
         :map minibuffer-local-map
         ("C-c C-c" . embark-collect)
         ("C-c C-e" . embark-export)))

(use-package embark-consult
  :ensure t
  :after (embark consult)
  :demand t
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))

(use-package all-the-icons-completion
  :after (marginalia all-the-icons)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
  :init
  (all-the-icons-completion-mode))

(use-package kind-icon
  :after corfu
  :custom
  (kind-icon-use-icons t)
  ;; No pollution. Change the location of the svg-lib cache directory.
  (svg-lib-icons-dir (no-littering-expand-var-file-name "svg-lib/cache"))
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

(use-package company
  :ensure t
  :config
  (global-company-mode 1))

(setq-default
 tab-always-indent 'complete                      ; Indent, if already indented, try to complete
 display-time-default-load-average nil            ; Don't display load average
 fill-column 100                                  ; Set column width
 help-window-select t                             ; Focus new help windows when opened
 indent-tabs-mode nil                             ; Prefer spaces over tabs, duh.
 tab-width 4                                      ; Set width for tabs
 kill-ring-max 128                                ; Maximum length of kill ring
 load-prefer-newer t                              ; Prefer the newest version of a file
 mark-ring-max 128                                ; Maximum length of mark ring
 select-enable-clipboard t                        ; Merge system's and Emacs' clipboard
 x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)
 user-full-name "ERick BOdine"                    ; Name
 vc-follow-symlinks t                             ; Always follow the symlinks
 frame-title-format '("Emacs: %f")                ; Frame title
 icon-title-format frame-title-format             ; OS icon title
 message-log-max 8192                             ; Don't lose any logging information.
 bidi-paragraph-separate-re "^"
 bidi-paragraph-start-re "^"
 ring-bell-function 'ignore                       ; Turn off the damn bell!
 history-delete-duplicates t                      ; Remove dups from helm-M-x & such.
 history-length 55                                ; Limit history length; see above.
 view-read-only t)                                ; Always open read-only buffers in view-mode

;; sane trackpad/mouse scroll settings
(when IS-MAC
  (setq mac-redisplay-dont-reset-vscroll t
        mac-mouse-wheel-smooth-scroll nil))

;; Some IO related settings.
;; support reading large blobs of data
(setq process-adaptive-read-buffering nil
      read-process-output-max (* 2048 2048))

;; Reduce rendering/line scan work for Emacs by not rendering cursors or regions
;; in non-focused windows.
(setq-default cursor-in-non-selected-windows nil)
(setq highlight-nonselected-windows nil)

;; More performant rapid scrolling over unfontified regions. May cause brief
;; spells of inaccurate syntax highlighting right after scrolling, which should
;; quickly self-correct.
(setq fast-but-imprecise-scrolling t)

;;; Scrolling
;;; These are mostly Doom Emacs changes.
(setq hscroll-margin 2
      hscroll-step 1
      scroll-conservatively 10
      scroll-margin 0
      scroll-preserve-screen-position t
      auto-window-vscroll nil)

;; Resizing the Emacs frame can be a terribly expensive part of changing the
;; font. By inhibiting this, we halve startup times, particularly when we use
;; fonts that are larger than the system default (which would resize the frame).
(setq frame-inhibit-implied-resize t)

;; Don't popup UI/graphical dialog boxes.
(setq use-dialog-box nil)


;; Don't ping things that look like domain names.
(setq ffap-machine-p-known 'reject)

;; Font compacting can be terribly expensive, especially for rendering icon
;; fonts on Windows. Whether it has a noteable affect on Linux and Mac hasn't
;; been determined, but we inhibit it there anyway.
(setq inhibit-compacting-font-caches t)

;; Remove command line options that aren't relevant to our current OS; means
;; slightly less to process at startup.
(unless IS-MAC   (setq command-line-ns-option-alist nil))
(unless IS-LINUX (setq command-line-x-option-alist nil))

;; Make apropos more useful
(setq apropos-do-all t)

;; Silence advised functions warnings
(setq ad-redefinition-action 'accept)

;; Don't pass over `auto-mode-alist' a second time.
(setq auto-mode-case-fold nil)

;; don't ask to kill buffers
(setq kill-buffer-query-functions
      (remq 'process-kill-buffer-query-function
            kill-buffer-query-functions))

;; Get rid of "For information about GNU Emacs..." message at startup
(unless noninteractive
  (advice-add #'display-startup-echo-area-message :override #'ignore)
  (setq inhibit-startup-message t
        inhibit-startup-echo-area-message user-login-name
        inhibit-default-init t
        ;; initial-major-mode 'fundamental-mode
        initial-scratch-message ";; Welcome to the Church of Emacs, Cardinal deftpunk presiding"
        mode-line-format nil))
;; we're in a daemon session, where it'll say "Starting Emacs daemon." instead
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore))

;; This file stores usernames, passwords, and such.
(setq auth-sources (list (expand-file-name "authinfo.gpg" deftpunk--etc-dir) "~/.authinfo.gpg"))

;; Some timezone stuff for logview.el and others.
(setenv "TZ" "America/Denver")
(setq datetime-timezone "America/Denver")

;; I actually find the custom system a nuisance; move the file out of the way.
(setq custom-file (expand-file-name "custom.el" deftpunk--var-dir))
(load custom-file :no-error-if-file-is-missing)


;; Replace yes/no prompts with y/n
(fset 'yes-or-no-p 'y-or-n-p)

;; see https://www.emacswiki.org/emacs/BrowseUrl#h5o-7
(after! browse-url
  (setq browse-url-browser-function 'browse-url-chrome
        browse-url-chrome-program "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        browse-url-new-window-flag  t))

;; Don't ask if you want to kill a buffer with a live process attached to it:
(remove-hook 'kill-buffer-query-functions 'process-kill-buffer-query-function)

(after! simple
        ;; The following may be of interest to people who (a) are happy with
        ;; "C-w" and friends for killing and yanking, (b) use
        ;; "transient-mark-mode", (c) also like the traditional Unix tty
        ;; behaviour that "C-w" deletes a word backwards. It tweaks "C-w" so
        ;; that, if the mark is inactive, it deletes a word backwards instead
        ;; of killing the region. Without that tweak, the C-w would create an
        ;; error text without an active region.
        ;; http://www.emacswiki.org/emacs/DefaultKillingAndYanking#toc2

        (defadvice kill-region (before unix-werase activate compile)
          "When called interactively with no active region, delete a single word backwards
           instead."
          (interactive
           (if mark-active (list (region-beginning) (region-end))
             (list (save-excursion (backward-word 1) (point)) (point))))))

;; Deleting past a tab normally changes tab into spaces. Don't do
;; that, kill the tab instead.
(setq backward-delete-char-untabify-method nil)

;; Don't type C-u C-SPC C-u C-SPC to pop 2 marks, now you can do C-u C-SPC C-SPC
(setq set-mark-command-repeat-pop t)

;; Revert buffers when the underlying file has changed.
(global-auto-revert-mode 1)
;; Revert Dired and other buffers
(setq global-auto-revert-non-file-buffers t)

;; no lockfiles
(setq create-lockfiles nil)

(setq-default save-abbrevs 'silently)

;; Turn abbreviations on globally.
(setq-default abbrev-mode t)
(blackout 'abbrev-mode)

;; Read the abbrev file on startup.
(quietly-read-abbrev-file)

(defun deftpunk/current-time ()
  (interactive)
  (insert (format-time-string "%D %T")))
(define-abbrev global-abbrev-table "ydate" "" 'deftpunk/current-time)

(use-package ansi-color
  :ensure nil)

;; Revert Dired and other buffers
(setq global-auto-revert-non-file-buffers t)
;; Revert buffers when the underlying file has changed.
(global-auto-revert-mode 1)

;; https://www.emacswiki.org/emacs/BackupDirectory
;; https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files

;; Default and per-save backups go here:
(setq backup-directory-alist `(("" . ,(expand-file-name "backups" deftpunk--var-dir))))

(defun force-backup-of-buffer ()
  ;; Make a special "per session" backup at the first save of each
  ;; emacs session.
  (when (not buffer-backed-up)
    ;; Override the default parameters for per-session backups.
    (let ((backup-directory-alist '(("" . "~/.emacs.d/backup/per-session")))
          (kept-new-versions 3))
      (backup-buffer)))
  ;; Make a "per save" backup on each save.  The first save results in
  ;; both a per-session and a per-save backup, to keep the numbering
  ;; of per-save backups consistent.
  (let ((buffer-backed-up nil))
    (backup-buffer)))

(add-hook 'before-save-hook  'force-backup-of-buffer)

(setq version-control t              ; Use version numbers for backup
      kept-new-versions 5            ; Number of newest version to keep around
      kept-old-versions 0            ; Number of oldest versions to keep around
      delete-old-versions t          ; Don't ask to delete older versions
      backup-by-copying t            ; Copy all files, don't rename them - best compromise for safety.
      vc-make-backup-files t         ; Even backup files under version control
      )

(column-number-mode 1)

(after! compile
  (setq compilation-always-kill t       ; kill compilation process before starting another.
        compilation-ask-about-save nil  ; save all buffers.
        compilation-auto-jump-to-first-error t
        compilation-scroll-output 'first-error)

  ;; Take care of color codes in the output and colorize the compilation buffer.
  (add-hook 'compilation-filter-hook 'ansi-color-compilation-filter)

  (autoload 'comint-truncate-buffer "comint" nil t)
  (add-hook 'compilation-filter-hook #'comint-truncate-buffer)
  )

(setopt compilation-ask-about-save nil)

(deftpunk-local-leader-def
  :keymaps 'compilation-mode-map
  "o" '(ace-link :which-keys "Highlight links in compilation buffer"))

(use-package dired
  :ensure nil
  :general
  (:keymaps 'dired-mode-map
            "RET" #'dired-find-alternate-file
            "^" (lambda ()
                  (interactive)
                  (find-alternate-file "..")))
  :custom
  ;; Allow dired to delete or copy a dir.
  ;; 02/14/24 17:41:48 - These default to 'top in dired now.
  ;; 'top means ask every time.
  ;; 'always means don't ask.
  (dired-recursive-copies 'top)
  (dired-recursive-deletes 'top)
  :config

  ;; Open marked files in dired
  ;; http://xahlee.info/emacs/emacs/emacs_dired_open_marked.html
  (defun xah-dired-open-marked ()
    "Open marked files in `dired'.
URL `http://xahlee.info/emacs/emacs/emacs_dired_open_marked.html'
Version 2019-10-22"
    (interactive)
    (mapc 'find-file (dired-get-marked-files)))

  ;; Make dired open in the same window when using RET or ^
  ;; Make Dired only use a single buffer when visiting a directory.
  ;; http://ergoemacs.org/emacs/emacs_dired_tips.html
  (put 'dired-find-alternate-file 'disabled nil) ; disables warning
  (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file) ; was dired-advertised-find-file
  (define-key dired-mode-map (kbd "^") (lambda ()
                                         (interactive)
                                         (find-alternate-file ".."))))  ; was dired-up-directory

(use-package dired+
  :ensure (dired+ :type git :host github :repo "emacsmirror/dired-plus"))

(use-package dired-subtree
  :ensure t
  :general
  (:keymaps 'dired-mode-map
            ("i" . dired-subtree-insert)
            (";" . dired-subtree-remove)
            ("<tab>" . dired-subtree-toggle)
            ("<backtab>" . dired-subtree-cycle)
            ("S-TAB" . dired-subtree-cycle)
            ))

(use-package ediff
  :ensure nil
  :custom
  (ediff-diff-options "-w")
  (ediff-use-long-help-message t)
  (ediff-split-window-function #'split-window-horizontally)
  (ediff-window-setup-function #'ediff-setup-windows-plain)
  :config

;; I just want to restore the previous window layout... so hard.
;; Added to and modified from https://emacs.stackexchange.com/questions/7482/restoring-windows-and-layout-after-an-ediff-session
(defvar my-ediff-last-windows nil
  "Window configuration prior to calling `ediff-buffers',
`ediff-regions-linewise', or `ediff-regions-wordwise'.")

(defun my-ediff-restore-last-windows ()
  "Set window configuration to `my-ediff-last-windows'."
  (cond (my-ediff-last-windows
         (set-window-configuration my-ediff-last-windows)
         (setq my-ediff-last-windows nil))))

(add-hook 'ediff-quit-hook #'my-ediff-restore-last-windows)

(defadvice ediff-buffers (before ediff-buffers-advice activate)
  (setq my-ediff-last-windows (current-window-configuration)))

(defadvice ediff-regions-linewise (before ediff-regions-linewise-advice activate)
  (setq my-ediff-last-windows (current-window-configuration)))

(defadvice ediff-regions-wordwise (before ediff-regions-wordwise-advice activate)
  (setq my-ediff-last-windows (current-window-configuration)))

;; For ediff-buffers/ediff-files
(defvar ediff-last-windows nil
  "Last ediff window configuration.")

(defun ediff-restore-windows ()
  "Restore window configuration to `ediff-last-windows'."
  (set-window-configuration ediff-last-windows)
  (remove-hook 'ediff-after-quit-hook-internal
               'ediff-restore-windows))

(defadvice ediff-buffers (around ediff-restore-windows activate)
  (setq ediff-last-windows (current-window-configuration))
  (add-hook 'ediff-after-quit-hook-internal 'ediff-restore-windows)
  ad-do-it)

(defadvice ediff-files (around ediff-restore-windows activate)
  (setq ediff-last-windows (current-window-configuration))
  (add-hook 'ediff-after-quit-hook-internal 'ediff-restore-windows)
  ad-do-it)
)

;; Remove the C-; key so that we can use it for a local-leader
(general-define-key
 :keymaps 'flyspell-mode-map
 "C-;" nil)

(use-package hl-line
  :ensure nil
  :custom
  (hl-line-sticky-flag nil) ; Don't highlight current line across windows.
  :config
  (defun eat/hl-line-setup ()
    "Disable `hl-line-mode' if region is active."
    (when (and (bound-and-true-p hl-line-mode)
               (region-active-p))
      (hl-line-unhighlight)))

  (with-eval-after-load 'hl-line
    (add-hook 'post-command-hook #'eat/hl-line-setup))

  (add-hook 'prog-mode-hook #'hl-line-mode)
  (add-hook 'text-mode-hook #'hl-line-mode))

(use-package emacs
  :ensure nil
  :custom
  (recentf-max-saved-items 250)
  (recentf-max-menu-items 15)
      ;; disable recentf-cleanup on Emacs start, because it can cause
      ;; problems with remote files, ie. Tramp files.
  (recentf-save-file "~/.emacs.d/etc/recentf-save.el")
  (recentf-auto-cleanup 'never)
  (recentf-exclude (list "/scp:"
                         "/ssh:"
                         "/sudo:"
                         "/tmp/"
                         "~$"
                         "COMMIT_EDITMSG"))
  :config
  (recentf-mode +1))

(setq savehist-file (expand-file-name "savehist" deftpunk--var-dir)
      history-length 65                                                ; reducing size helps reduce startup cost.
      history-delete-duplicates t
      savehist-save-minibuffer-history t
      savehist-additional-variables '(kill-ring
                                      search-ring
                                      mark-ring
                                      global-mark-ring
                                      regexp-search-ring
                                      extended-command-history
                                      regexp-search-ring))
(savehist-mode 1)

;; Limit some of the items in savehist
(put 'savehist-minibuffer-history-variables 'history-length 50)
(put 'org-read-date-history                 'history-length 50)
(put 'read-expression-history               'history-length 50)
(put 'org-table-formula-history             'history-length 50)
(put 'extended-command-history              'history-length 50)
(put 'ido-file-history                      'history-length 50)
(put 'helm-M-x-input-history                'history-length 50)
(put 'minibuffer-history                    'history-length 50)
(put 'ido-buffer-history                    'history-length 50)
(put 'buffer-name-history                   'history-length 50)
(put 'file-name-history                     'history-length 50)

(use-package saveplace
  :ensure nil
  :custom
  (save-place-limit 100)
  (save-place-file (expand-file-name "emacs-places" deftpunk--var-dir))
  (save-place-forget-unreadable-files nil)  ; Setting to t has the potential to make exiting slow
  :config
  (save-place-mode 1)
  (add-hook 'save-place-find-file-hook 'recenter)
  (add-hook 'find-file-hook 'save-place-find-file-hook t))

(use-package tramp
  :ensure nil
  :custom
  (tramp-default-method "ssh")
  ;; https://www.reddit.com/r/emacs/comments/lp8bjb/comment/goai6ig/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
  (tramp-ssh-controlmaster-options (concat
                                    "-o ControlPath=\~/.ssh/cons/ssh-%%r@%%h:%%p "
                                    "-o ControlMaster=auto -o ControlPersist=yes"))
  :config
  (setq remote-file-name-inhibit-cache nil)
  (setq vc-ignore-dir-regexp
        (format "%s\\|%s"
                vc-ignore-dir-regexp
                tramp-file-name-regexp))
  (setq tramp-verbose 1))

(use-package treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  (treesit-auto-langs '(python rust clojure commonlisp bash nim json yaml toml go))
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))

(setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow))
(global-visual-line-mode)
(blackout 'visual-line-mode)

;; Ignore all the *<name>* buffers by regex.
(setq winner-boring-buffers-regexp "^\\*")
(winner-mode +1)

(use-package ztree)

(use-package ace-window
  :bind (("C--" . ace-window))
  :init
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
        aw-leading-char-style 'path
        aw-background t
        aw-dispatch-always t)
  :config
  (set-face-attribute 'aw-leading-char-face nil :height 4.0))

(use-package ace-link
  :init (ace-link-setup-default))

;; NOTE: If problems w/ TRAMP are encountered, add >> (setq docker-open-hook '())
(use-package docker
  :ensure t
  :bind ("C-c d" . docker))

(use-package emacs
  :ensure nil
  :config
  (defadvice keyboard-escape-quit
      (around keyboard-escape-quit-dont-close-windows activate)
    (let ((buffer-quit-function (lambda () ())))
      ad-do-it)))

(use-package elfeed
  :custom
  ;; Prefer the curl we install via homebrew
  (elfeed-curl-program-name "/opt/homebrew/opt/curl/bin/curl")
  (elfeed-db-directory (expand-file-name "elfeed" user-emacs-directory))
  (elfeed-show-entry-switch 'display-buffer)
  (elfeed-feeds '(("http://www.reddit.com/r/emacs.rss" emacs)
                  ("https://planet.emacslife.com/atom.xml" emacs)
                  ("https://xkcd.com/rss.xml" fun)))
  :bind
  (("C-c e" . elfeed )))

 (defun my-elfeed-mark-all-read ()
   (interactive)
   (elfeed-untag elfeed-search-entries 'unread)
   (elfeed-search-update :force)) ; redraw

(use-package elfeed-org
  :after (elfeed)
  :config
  (setq rmh-elfeed-org-files (list (expand-file-name deftpunk--etc-dir "elfeed.org")))
  (elfeed-org))

(use-package expand-region
  :bind ("C-=" . er/expand-region))

(use-package google-this)

(use-package indent-bars
  :ensure (indent-bars :type git :host github :repo "jdtsmith/indent-bars")
  :custom
  (indent-bars-no-descend-lists t) ; no extra bars in continued func arg lists
  (indent-bars-treesit-support t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  ;; Add other languages as needed
  (indent-bars-treesit-scope '((python function_definition class_definition for_statement
      if_statement with_statement while_statement)))
  ;; Note: wrap may not be needed if no-descend-list is enough
  ;;(indent-bars-treesit-wrap '((python argument_list parameters ; for python, as an example
  ;;				      list list_comprehension
  ;;				      dictionary dictionary_comprehension
  ;;				      parenthesized_expression subscript)))
  :hook ((python-base-mode yaml-mode) . indent-bars-mode))

(use-package move-text
  :config
  (defun indent-region-advice (&rest ignored)
    "Indent after moving"
    (let ((deactivate deactivate-mark))
      (if (region-active-p)
          (indent-region (region-beginning) (region-end))
        (indent-region (line-beginning-position) (line-end-position)))
      (setq deactivate-mark deactivate)))

  (advice-add 'move-text-up :after 'indent-region-advice)
  (advice-add 'move-text-down :after 'indent-region-advice))

;; Cuz general won't  add these as part of use-package declaration??
(global-set-key (kbd "s-C-j") #'move-text-down)
(global-set-key (kbd "s-C-k") #'move-text-up)

(use-package osx-trash
  :config
  (when (eq system-type 'darwin)
    (osx-trash-setup))
  (setq delete-by-moving-to-trash t))

(use-package page-break-lines
  :blackout t
  :hook (text-mode . page-break-lines-mode))

(use-package perspective
  :hook (kill-emacs-hook . persp-state-save)
  :bind (("C-x b" . persp-switch-to-buffer*)
         ("C-x k" . persp-kill-buffer*)
         ("C-x C-b" . persp-list-buffers))         ; or use a nicer switcher, see below
  :custom
  (persp-initial-frame-name "Main Perspective")
  (persp-state-default-file "~/.emacs.d/.perspective-state")
  (persp-mode-prefix-key (kbd "s-p"))  ; pick your own prefix key here
  :init
  (persp-mode))

(use-package projectile
  :bind (:map projectile-mode-map
;;              ("s-p" . projectile-command-map)
              ("C-c p" . projectile-command-map))
  :init
  (setq
   ;; Auto-discovery is slow to do by default. Better to update the list
   ;; when you need to (`projectile-discover-projects-in-search-path').
   projectile-project-search-path '("~/WorkStuff/eig")
   projectile-completion-system 'default
   projectile-auto-discover t
   projectile-enable-caching t
   projectile-globally-ignored-files '(".DS_Store" "TAGS")
   projectile-globally-ignored-file-suffixes '(".elc" ".pyc" ".o")
   projectile-kill-buffers-filter 'kill-only-files
   projectile-ignored-projects '("~/" "/tmp"))

  (setq projectile-cache-file (expand-file-name "projectile.cache" deftpunk--var-dir)
        projectile-known-projects-file (expand-file-name "projectile-known-projects.eld"
                                                         deftpunk--var-dir))
  ;; Do not include the straight repos
  (setq projectile-ignored-project-function
        (lambda (project-root)
          (string-prefix-p (expand-file-name "straight/" user-emacs-directory) project-root)))

  (global-set-key [remap find-tag]         #'projectile-find-tag)

  (projectile-mode +1))

(use-package consult-projectile
  ;; :bind (("s-p" . consult-projectile))
  :ensure (consult-projectile :type git :host gitlab :repo "OlMon/consult-projectile" :branch "master"))

(use-package persp-projectile
  :config
  (require 'persp-projectile))

(use-package selected
  :commands selected-minor-mode
  :init
  (setq selected-org-mode-map (make-sparse-keymap))
  :bind (:map selected-keymap
              ("q" . selected-off)
              ("u" . upcase-region)
              ("d" . downcase-region)
              ("m" . apply-macro-to-region-lines)
              :map selected-org-mode-map
              ("t" . org-table-convert-region)))

(use-package smart-hungry-delete
  :bind (([remap backward-delete-char-untabify] . smart-hungry-delete-backward-char)
         ([remap delete-backward-char] . smart-hungry-delete-backward-char)
         ([remap delete-char] . smart-hungry-delete-forward-char))
  :init (smart-hungry-delete-add-default-hooks))

(use-package smartparens
  :commands (sp-local-pair)
  :hook (prog-mode . smartparens-mode)
  :config
  ;; smartparens doesn't recognize the sly-mrepl-mode
  (add-to-list 'sp-lisp-modes 'sly-mrepl-mode)

  ;; load the default smartparens rules for various languages.
  (require 'smartparens-config)

  ;; Overlays are too distracting and not terribly helpful. show-parens does
  ;; this for us already (and is faster), so...
  (setq sp-highlight-pair-overlay nil
        sp-highlight-wrap-overlay nil
        sp-highlight-wrap-tag-overlay nil)

  ;; The default is 100, because smartparen's scans are relatively expensive
  ;; (especially with large pair lists for some modes), we reduce it, as a
  ;; better compromise between performance and accuracy.
  (setq sp-max-prefix-length 25)
  ;; No pair has any business being longer than 4 characters; if they must, set
  ;; it buffer-locally. It's less work for smartparens.
  (setq sp-max-pair-length 4)
  ;; This isn't always smart enough to determine when we're in a string or not.
  ;; See https://github.com/Fuco1/smartparens/issues/783.
  (setq sp-escape-quotes-after-insert nil)

  ;; Silence some harmless but annoying echo-area spam
  (dolist (key '(:unmatched-expression :no-matching-tag))
    (setf (alist-get key sp-message-alist) nil))

  ;; You're likely writing lisp in the minibuffer, therefore, disable these
  ;; quote pairs, which lisps doesn't use for strings:
  (sp-local-pair 'minibuffer-inactive-mode "'" nil :actions nil)
  (sp-local-pair 'minibuffer-inactive-mode "`" nil :actions nil))

(setq auto-save-default nil) ; turn off the builtin auto-save
(use-package super-save
  :blackout t
  :custom
  (super-save-silent t)
  (super-save-delete-trailing-whitespace t)
  (super-save-remote-files nil)
  (super-save-auto-save-when-idle t)
  (super-save-exclude '(".gpg"))
  :config
  (add-to-list 'super-save-triggers 'ace-window)
  (add-to-list 'super-save-hook-triggers 'find-file-hook)
  (super-save-mode +1))

(use-package symbols-outline
  :config
  (setq symbols-outline-fetch-fn #'symbols-outline-lsp-fetch
        symbols-outline-window-position 'left)
  (symbols-outline-follow-mode))

(use-package transpose-frame
  :bind
  (("C-x 4 t" . transpose-frame)
   ("C-x 4 r" . rotate-frame-clockwise))
  :config)

(use-package treemacs
  :ensure t
  :commands (treemacs-follow-mode
             treemacs-filewatch-mode
             treemacs-fringe-indicator-mode
             treemacs-git-mode)
  :init
  (setq treemacs-missing-project-action  'remove
        treemacs-sorting                 'alphabetic-asc
        treemacs-follow-after-init       t
        treemacs-width                   35)
  :config
  (treemacs-follow-mode t)
  (treemacs-filewatch-mode t))

(use-package treemacs-magit
  :ensure t
  :after magit
  :commands treemacs-magit--schedule-update
  :hook ((magit-post-commit
          git-commit-post-finish
          magit-post-stage
          magit-post-unstage)
         . treemacs-magit--schedule-update))

(use-package undo-fu)

(use-package undo-fu-session
  :config
  (setq undo-fu-session-incompatible-files '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
  (undo-fu-session-global-mode))
(elpaca-wait)

(global-unset-key (kbd "M-u"))
(use-package unfill
  :bind
  (("M-u" . unfill-toggle)))

(use-package vundo
  :commands (vundo)
  :ensure (vundo :type git :host github :repo "casouri/vundo")
  :custom
  ;; Take less on-screen space.
  (vundo-compact-display t)
  :config

  ;; Better contrasting highlight.
  (custom-set-faces
    '(vundo-node ((t (:foreground "#808080"))))
    '(vundo-stem ((t (:foreground "#808080"))))
    '(vundo-highlight ((t (:foreground "#FFFF00")))))

  ;; Use `HJKL` VIM-like motion, also Home/End to jump around.
  (define-key vundo-mode-map (kbd "l") #'vundo-forward)
  (define-key vundo-mode-map (kbd "<right>") #'vundo-forward)
  (define-key vundo-mode-map (kbd "h") #'vundo-backward)
  (define-key vundo-mode-map (kbd "<left>") #'vundo-backward)
  (define-key vundo-mode-map (kbd "j") #'vundo-next)
  (define-key vundo-mode-map (kbd "<down>") #'vundo-next)
  (define-key vundo-mode-map (kbd "k") #'vundo-previous)
  (define-key vundo-mode-map (kbd "<up>") #'vundo-previous)
  (define-key vundo-mode-map (kbd "<home>") #'vundo-stem-root)
  (define-key vundo-mode-map (kbd "<end>") #'vundo-stem-end)
  (define-key vundo-mode-map (kbd "q") #'vundo-quit)
  (define-key vundo-mode-map (kbd "C-g") #'vundo-quit)
  (define-key vundo-mode-map (kbd "RET") #'vundo-confirm)

  (global-define-key (kbd "C-M-u") 'vundo))

(use-package wgrep
  :ensure t
  :bind (:map grep-mode-map
              ("e" . wgrep-change-to-wgrep-mode)
              ("C-x C-q" . wgrep-change-to-wgrep-mode)
              ("C-c C-c" . wgrep-finish-edit)))

(use-package ws-butler
  :ensure (ws-butler :type git :host github :repo "hlissner/ws-butler")
  :blackout t
  :hook ((text-mode . ws-butler-mode)
         (prog-mode . ws-butler-mode))
  :custom
  (ws-butler-keep-whitespace-before-point nil))

;; show trailing whitespace
(setq show-trailing-whitespace t)

(with-eval-after-load 'ws-butler
  (blackout 'ws-butler-mode))

(use-package zzz-to-char)

(use-package devdocs-browser
  :commands (devdocs-browser-open)
  :general ("C-h D" #'devdocs-browser-open))

(use-package helpful
  :general
  ([remap describe-function]  #'helpful-callable
   [remap describe-command]   #'helpful-command
   [remap describe-variable]  #'helpful-variable
   [remap display-local-help] #'helpful-at-point
   [remap describe-symbol]    #'helpful-symbol
   [remap describe-key]       #'helpful-key
   "C-h x"                    #'helpful-macro))

;; Make all the lines soft-wrap
(use-package org
  :ensure nil
  :blackout (org-mode . " Org")
  :hook (org-mode . (lambda ()
          (toggle-truncate-lines nil)))
  :general
  (:keymaps 'org-mode-map
        "C-c C-'" 'org-edit-special)
  (:keymaps 'org-src-mode-map
        "C-c C-'" 'org-edit-src-exit)
  :custom
  (org-use-speed-commands t)      ; faster navigation
  (org-fontify-quote-and-verse-blocks t)    ; quote/verse blocks show up better
  (org-return-follows-link t)
  (org-src-fontify-natively t)
  (org-startup-indented t)
  (org-pretty-entities t)
  (org-hide-emphasis-markers t)       ; show italicized text instead of /italicized text/
  (org-startup-with-inline-images t)
  (org-image-actual-width '(300))
  :init
  ;; Load markdown as well as emacs-lisp
  ;; Add/Create function for executing markdown or send to previewer
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)))
  :config
  ;; Moving general bindings here to reduce startup penalty.

  ;; Create a sparse tree view of TODOs in the current Org buffer.
  ;; https://stackoverflow.com/a/63195446
  ;; You can use C-x 4 0 to kill the buffer and window when done.
  (defun org-todo-buffer ()
    "Create new indirect buffer with sparse tree of undone TODO items"
    (interactive)
    (clone-indirect-buffer "*org TODO undone*" t)
    (org-show-todo-tree nil) ; mimics interactive usage
    (org-remove-occur-highlights))

  ;; Keys for org-mode-map
  (general-define-key
   :keymaps 'org-mode-map
   ;; so that C-j actually is mapped to avy-goto-char-timer
   "C-j" 'nil
   "C-k" 'nil
   ;; so that we can use it as help prefix
   "M-h" 'nil)

  ;; Local leader bindings.
  (deftpunk-local-leader-def
    :keymaps 'org-mode-map
    "a" '(org-todo-buffer :which-key "Show TODOs for current buffer.")
    "d" '(org-todo :which-key "Org Todo + Todo States")
    "e" '(org-edit-special :which-key "Edit blk in special buffer")
    "h" '(consult-org-heading :which-key "Find Org heading in current buffer.") ; https://github.com/minad/consult/blob/main/consult-org.el
    "i" '(org-insert-link :which-key "Org Insert link")
    "n" '(org-babel-next-src-block :which-key "Go to the next src block")
    "o" '(ace-link-org :which-key "Links in Org mode document")
    "p" '(org-babel-previous-src-block :which-key "Go to previous src block")
    "s" '(org-insert-structure-template :which-key "Insert templates")
    "t" '(org-babel-tangle :which-key "Tangle the src blocks")
    "u" '(org-babel-goto-src-block-head :which-key "Go to the head of the src block")
    "x" '(org-open-at-point :which-key "Open link at point")
    "y" '(org-download-screenshot file :which-key "Yank screenshot"))
  )

;; More "keep off my modeline"
(with-eval-after-load 'org-indent
  (blackout 'org-indent-mode))

(defun dftpnk-org-src-mode ()
  (smartparens-mode)
  (rainbow-delimiters-mode t))

(add-hook 'org-src-mode-hook #'dftpnk-org-src-mode)

(use-package org-appear
  :blackout t
  :hook (org-mode . org-appear-mode)
  :custom
  (org-appear-autolinks t)
  (org-appear-autosubmarkers t)
  (org-appear-autoentities t)
  (org-appear-auto-keywards))

(use-package org-auto-tangle
  :hook (org-mode . org-auto-tangle-mode))

;; The joys of hooks and loading.
(with-eval-after-load 'org-auto-tangle
  (blackout 'org-auto-tangle-mode))

;; https://github.com/minad/org-modern/issues/106#issuecomment-1344659316
;; Fixes issue mentioned above
(defun disable-point-adjustment (&rest args)
  (setq disable-point-adjustment t))
(advice-add 'org-beginning-of-line :after #'disable-point-adjustment)

(use-package org-modern
  :blackout
  :after org
  :init
  (setq org-modern-hide-stars nil
        ;; I prefer just the circle
        org-modern-star '("○" "○" "○" "○" "○" "○")
        org-auto-align-tags nil
        org-tags-column 0
        org-catch-invisible-edits 'show-and-error
        org-special-ctrl-a/e t
        org-insert-heading-respect-content t

        ;; Org styling, hide markup etc.
        org-ellipsis "…"

        ;; Agenda styling
        org-agenda-tags-column 0
        org-agenda-block-separator ?─
        org-agenda-time-grid
        '((daily today require-timed)
          (800 1000 1200 1400 1600 1800 2000)
          " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
        org-agenda-current-time-string
        "⭠ now ─────────────────────────────────────────────────")
  :config
  (global-org-modern-mode))

(setenv "GPG_AGENT_INFO" nil)
(setq epg-gpg-program "gpg2")

(use-package blamer
  :ensure (:host github :repo "artawower/blamer.el")
  :bind (("C-c i" . blamer-show-commit-info))
         ;("C-c i" . blamer-show-posframe-commit-info))
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 70)
  :custom-face
  (blamer-face ((t :foreground "#7a88cf"
                    :background nil
                    :height 120
                    :italic t)))
  :config
  (global-blamer-mode 1))

(use-package browse-at-remote
  :commands (browse-at-remote)
  :general ("C-c g g" #'browse-at-remote)
  :config
  ;; Add the HPE github.
  (add-to-list 'browse-at-remote-remote-type-regexps
               `(:host ,(rx bol "github.hpe.com" eol)
                       :type "github"
                       :actual-host "github.hpe.com")))

;; From Doom Emacs ui/vc-gutter/config.el
;; UI: make the fringe small enough that the diff bars aren't too domineering,
;;   while leaving enough room for other indicators.
(if (fboundp 'fringe-mode) (fringe-mode '8))
;; UI: the gutter looks less cramped with some space between it and  buffer.
(setq-default fringes-outside-margins t)

(use-package diff-hl
  :hook ((find-file . diff-hl-mode)
         (vc-dir-mode . diff-hl-dir-mode)
         (dired-mode . diff-hl-dired-mode)
         (magit-pre-refresh . diff-hl-magit-pre-refresh)
         (magit-post-refresh . diff-hl-magit-post-refresh))
  :custom
  (diff-hl-draw-borders nil)
  :config

  ;; From Doom:
  ;; PERF: A slightly faster algorithm for diffing.
  (setq vc-git-diff-switches '("--histogram"))
  ;; PERF: Slightly more conservative delay before updating the diff
  (setq diff-hl-flydiff-delay 0.5)  ; default: 0.3
  ;; PERF: don't block Emacs when updating vc gutter
  (setq diff-hl-update-async t)

  ;; UX: get realtime feedback in diffs after staging/unstaging hunks.
  (setq diff-hl-show-staged-changes nil)
  (global-diff-hl-mode))

(use-package git-link
  :bind (("C-c g l" . 'git-link)))

(use-package git-modes
  :config
  ;; This works for .dockerignore and other .*ignore files as well.
  (dolist (pattern '("/.dockeringnore\\'"))
    (add-to-list 'auto-mode-alist (cons pattern #'gitignore-mode))))

(use-package git-timemachine
  :config
  (setq git-timemachine-abbreviation-length 14
        git-timemachine-show-minibuffer-details t)
  (elpaca-wait))

;; From redguardtoo - http://blog.binchen.org/posts/new-git-timemachine-ui-based-on-ivy-mode.html
(defun my-git-timemachine-show-selected-revision ()
  "Show last (current) revision of file."
  (interactive)
  (let (collection)
    (setq collection
          (mapcar (lambda (rev)
                    ;; re-shape list for the ivy-read
                    (cons (concat (substring (nth 0 rev) 0 7) "|" (nth 5 rev) "|" (nth 6 rev)) rev))
                  (git-timemachine--revisions)))
    (ivy-read "commits:"
              collection
              :action (lambda (rev)
                        (git-timemachine-show-revision rev)))))

(defun my-git-timemachine ()
  "Open git snapshot with the selected version.  Based on ivy-mode."
  (interactive)
  (unless (featurep 'git-timemachine)
    (require 'git-timemachine))
  (git-timemachine--start #'my-git-timemachine-show-selected-revision))

(use-package sideline-blame)
;; Show the commit message for the current line.
(use-package sideline
  :init
  (setq sideline-backends-left '((sideline-blame . down))))

(use-package vc-msg
  :init
  (setq vc-msg-force-vcs "git"))

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook (((python-mode python-ts-mode) . lsp)
         (clojure-mode . lsp-deferred))
  :hook (lsp-mode . lsp-enable-which-key-integration)
  :custom
  (lsp-completion-provider :company)
  (lsp-completion-show-detail t)
  (lsp-competion-show-kind t)
  (lsp-keymap-prefix "C-c l")
  (lsp-enable-symbol-highlighting t)
  (lsp-lens-enable t)
  (lsp-headerline-breadcrumb-enable t)
  (lsp-diagnostics-provider :flycheck)
  (lsp-completion-show-detail t)
  (lsp-completion-show-kind t))

;; lsp-clients
;; TODO: pyright on VDT
;; (lsp-register-client
 ;; (make-lsp-client :new-connection (lsp-tramp-connection "pyright")
 ;;                  :major-modes '(python-mode python-ts-mode)
 ;;                  :remote? t
 ;;                  :server-id 'pyright-vdt))

(use-package lsp-pyright
  :ensure t
  :hook ((python-mode python-ts-mode) . (lambda ()
                                          (require 'lsp-pyright)
                                          (lsp))))  ; or lsp-deferred

(use-package lsp-ui
  :commands (lsp-ui-mode)
  :general
  (:keymaps 'lsp-ui-mode-map
            [remap xref-find-definitions] #'lsp-ui-peek-find-definitions
            [remap xref-find-references] #'lsp-ui-peek-find-references)
  :hook (lsp-mode . lsp-ui-mode)
  :config
  (setq lsp-ui-doc-position 'bottom
        lsp-ui-doc-header t
        lsp-ui-peek-enable t
        lsp-ui-peek-always-show t
        lsp-ui-sideline-show-hover t
        lsp-ui-sideline-show-diagnostics t
        lsp-ui-doc-include-signature t))

(use-package lsp-ivy)

(use-package lsp-treemacs
  :config
  (lsp-treemacs-sync-mode 1))

(use-package consult-lsp
  :ensure t
  :config
  (define-key lsp-mode-map [remap xref-find-apropos] #'consult-lsp-symbols))

(defun emacswiki/comment-auto-fill ()
    " Set up auto-file / wrapping of comments."
    (setq-local comment-auto-fill-only-comments t)
    (auto-fill-mode 1))

;; Spellchecking in comments.
(add-hook 'prog-mode-hook #'flyspell-prog-mode)

;; Make a buffer executable automatically if its a script
  (add-hook 'after-save-hook
            'executable-make-buffer-file-executable-if-script-p)

(setq-default display-line-numbers-width 3)
(setq-default display-line-numbers-widen t)

(use-package fill-function-arguments
  :hook
  ((prog-mode . (lambda ()
                  (local-set-key (kbd "M-q") #'fill-function-arguments-dwim)))
   (emacs-lisp-mode . (lambda ()
                        (setq-local fill-function-arguments-second-argument-same-line t)
                        (setq-local fill-function-arguments-last-argument-same-line t)
                        (setq-local fill-function-arguments-argument-separator " "))))
  :custom
  (fill-function-arguments-indent-after-fill t)
  (fill-function-arguments-indent-first-argument-same-line t))

(use-package highlight-indent-guides
  :blackout t
  :hook (python-mode . highlight-indent-guides-mode)
  :init (setq highlight-indent-guides-method 'character
              highlight-indent-guides-responsive 'top))

(after! highlight-indent-guides-mode
  (progn
   (set-face-background 'highlight-indent-guides-odd-face "gray48")
   (set-face-background 'highlight-indent-guides-even-face "gray48")
   (set-face-foreground 'highlight-indent-guides-character-face "gray28")
   (set-face-foreground 'highlight-indent-guides-top-character-face "orchid1")))

(use-package outline-indent
  :ensure t
  :custom
  (outline-indent-ellipsis " ▼ ")
  :commands (outline-indent-minor-mode
             outline-indent-insert-heading)
  :hook (((python-mode python-ts-mode) . #'(lambda ()
                                             (setq-local outline-indent-default-offset 4)
                                             (setq-local outline-indent-shift-width 4)
                                             (outline-indent-minor-mode +1)))
         ((yaml-mode yaml-ts-mode) . #'(lambda ()
                                         (setq-local outline-indent-default-offset 2)
                                         (setq-local outline-indent-shift-width 2)
                                         (outline-indent-minor-mode +1)))))

(use-package clojure-mode
  :hook ((clojure-mode . smartparens-strict-mode)
         (clojure-mode . subword-mode)
         (clojure-mode . rainbow-delimiters-mode))
  :custom
  (clojure-indent-style 'always-align)
  (clojure-align-forms-automatically t)
  )

(use-package cider
  :after clojure-mode
  :ensure t
  :custom
  (cider-enrich-classpath t)
  (cider-connection-message-fn #'cider-random-tip)
  (cider-special-mode-truncate-lines nil)
  (cider-font-lock-dynamically '(macro core function var)))

(setq inferior-lisp-program "/opt/homebrew/bin/sbcl")
(use-package sly)

;; (defun sbcl-save-sly-and-die ()
;;   "Save a sbcl image, even when running from inside Sly.
;; This function should only be used in the *inferior-buffer* buffer,
;; inside emacs."
;;   (mapcar #'(lambda (x)
;;               (slynk::close-connection
;;                x nil nil))
;;           slynk::*connections*)
;;   (dolist (thread (remove
;;                    (slynk-backend::current-thread)
;;                    (slynk-backend::all-threads)))
;;     (slynk-backend::kill-thread thread))
;;   (sleep 1)
;;   (sb-ext:save-lisp-and-die #P"~/your-main-program.exe"
;;                             :toplevel #'your-main-function-here
;;                             :executable t
;;                             :compression t))

;; in *sly-inferior-lisp* buffer
;; (sbcl-save-sly-and-die)

(use-package nim-mode
  :hook ((nim-mode . nimsuggest-mode)
         (nim-mode . subword-mode)
         (nim-mode . rainbow-delimiters-mode))
  :mode (("\\.nim.?\\'" . nim-mode))
  )

(defun deftpunk/python-mode-hook ()
  "Setting up some basics for Python."
  (setq-local fill-column 105)
  ;; (smartparens-strict-mode)
  (highlight-indent-guides-mode)
  (display-line-numbers-mode 1))

(use-package python
  :ensure nil
  :mode ((rx ".py" string-end) . python-mode)
  :hook (((python-mode python-ts-mode) . deftpunk/python-mode-hook))
  :config
  (setq-local flycheck-python-pylint-executable "pylint")
  (setq-local flycheck-python-flake8-executable "flake8")

  (setq python-shell-interpreter (executable-find "ipython")
        python-shell-interpreter-args "-i --simple-prompt --no-color-info"
        python-shell-prompt-block-regexp "\\.\\.\\.\\.: "
        python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
        python-shell-completion-setup-code
        "from IPython.core.completerlib import module_completion"
        python-shell-completion-string-code
        "';'.join(get_ipython().Completer.all_completions('''%s'''))\n")

  ;; some smartparens "smartness" for single quotes
  ;; (sp-local-pair 'python-mode "'" nil
  ;;                :unless '(sp-point-before-word-p
  ;;                          sp-point-after-word-p
  ;;                          sp-point-before-same-p))
  )

(deftpunk-local-leader-def
  :keymaps '(python-ts-mode-map python-mode-map)
  "c" '(conda-env-activate :which-key "Activate conda env")
  "d" '(conda-env-deactivate :which-key "Deactivate conda env")
  "t" '(python-pytest-dispatch :which-key "Pytest dispatch")
  )

(use-package conda
  :after python
  :config
  ;; taken from doom
  ;; The location of your anaconda home will be guessed from a list of common
  ;; possibilities, starting with `conda-anaconda-home''s default value (which
  ;; will consult a ANACONDA_HOME envvar, if it exists).
  ;;
  ;; If none of these work for you, `conda-anaconda-home' must be set
  ;; explicitly. Afterwards, run M-x `conda-env-activate' to switch between
  ;; environments
  (or (cl-loop for dir in (list conda-anaconda-home
                                "~/.miniconda3"
                                "~/.conda")
               if (file-directory-p dir)
               return (setq conda-anaconda-home (expand-file-name dir)
                            conda-env-home-directory (expand-file-name dir)))
      (message "Cannot find Anaconda installation"))
  ;; integration with term/eshell
  (conda-env-initialize-interactive-shells)
  (after! eshell (conda-env-initialize-eshell))

  ;; auto-activation (see below for details)
  ;; (conda-env-autoactivate-mode t)
  ;; automatically activate a conda environment on the opening of a file:
  ;; (add-hook 'find-file-hook (lambda () (when (and (bound-and-true-p conda-project-env-path) (string-match "\\.py\\'" buffer-file-name))
  ;;                                       (conda-env-activate-for-buffer))))

  ;; Add to the modeline so that we know which env is activated.
  (add-to-list 'global-mode-string
               '(conda-env-current-name (" conda:" conda-env-current-name " "))
               'append))

(use-package python-pytest
  :hook (python-mode . (lambda ()
                         (when-let ((r (locate-dominating-file default-directory ".gitignore")))
                           (setq python-pytest-executable
                                 (concat "PYTHONPATH=" r " " "pytest"))))))

(use-package python-docstring-mode
  :hook (python-mode . python-docstring-mode)
  :ensure (:host github :repo "glyph/python-docstring-mode" :main "python-docstring.el"))

(use-package dockerfile-mode
  :mode "Dockerfile.*\\'")

(use-package yaml-mode
  :config
  (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode)))

(use-package yaml-pro
  :hook (yaml-mode . yaml-ts-mode-hook)
  :config
  ;; the original bindings will work as well, these are shorter if you prefer them.
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-n" #'yaml-pro-ts-next-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-p" #'yaml-pro-ts-prev-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-u" #'yaml-pro-ts-up-level)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-d" #'yaml-pro-ts-down-level)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-k" #'yaml-pro-ts-kill-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-<backspace>" #'yaml-pro-ts-kill-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-a" #'yaml-pro-ts-first-sibling)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-e" #'yaml-pro-ts-last-sibling)

  (deftpunk-local-leader-def
    :keymaps 'yaml-pro-ts-mode-map
    "n" '(yaml-pro-ts-next-subtree :which-key "Next subtree")
    "p" '(yaml-pro-ts-prev-subtree :which-key "Previous subtree")
    "u" '(yaml-pro-ts-up-level :which-key "Up subtree")
    "d" '(yaml-pro-ts-down-level :which-key "Down subtree")
    "k" '(yaml-pro-ts-kill-subtree :which-key "Kill subtree")
    "<backspace>" '(yaml-pro-ts-kill-subtree :which-key "Kill subtree")
    "a" '(yaml-pro-ts-first-sibling :which-key "First sibling")
    "e" '(yaml-pro-ts-last-sibling :which-key "Last sibling")
    )

  (defvar-keymap my/yaml-pro/tree-repeat-map
    :repeat t
    "n" #'yaml-pro-ts-next-subtree
    "p" #'yaml-pro-ts-prev-subtree
    "u" #'yaml-pro-ts-up-level
    "d" #'yaml-pro-ts-down-level
    "m" #'yaml-pro-ts-mark-subtree
    "k" #'yaml-pro-ts-kill-subtree
    "a" #'yaml-pro-ts-first-sibling
    "e" #'yaml-pro-ts-last-sibling
    "SPC" #'my/yaml-pro/set-mark)

  (defun my/yaml-pro/set-mark ()
    (interactive)
    (my/region/set-mark 'my/yaml-pro/set-mark))

  (defun my/region/set-mark (command-name)
    (if (eq last-command command-name)
        (if (region-active-p)
            (progn
              (deactivate-mark)
              (message "Mark deactivated"))
          (activate-mark)
          (message "Mark activated"))
      (set-mark-command nil))))

(use-package vterm
  :ensure t
  :hook
  ;; Change the face so its more obvious we are in an emulator.
  (vterm-mode . (lambda ()
                  (set (make-local-variable 'buffer-face-mode-face) 'fixed-pitch)
                  (buffer-face-mode t)))
  :custom
  (vterm-always-compile-module t)
  (vterm-max-scrollback 100000)               ; the max without changing vterm-module.h and re-compiling
  (vterm-copy-mode-remove-fake-newlines t))

(use-package multi-vterm
  :ensure t
  :general
  (:prefix "C-c t"
           "t" #'multi-vterm
           "d" #'multi-vterm-dedicated-toggle
           "n" #'multi-vterm-next
           "p" #'multi-vterm-previous))

;; Trying out matching parens
;; https://www.gnu.org/software/emacs/manual/html_node/efaq/Matching-parentheses.html
(defun match-paren (arg)
  "Go to the matching paren if on a paren; otherwise insert %."
  (interactive "p")
  (cond ((looking-at "\\s(") (forward-list 1) (backward-char 1))
        ((looking-at "\\s)") (forward-char 1) (backward-list 1))
        (t (self-insert-command (or arg 1)))))

(global-set-key "%" 'match-paren)

;; From https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
(defun prot/keyboard-quit-dwim ()
  "Do-What-I-Mean behaviour for a general `keyboard-quit'.

The generic `keyboard-quit' does not do the expected thing when
the minibuffer is open.  Whereas we want it to close the
minibuffer, even without explicitly focusing it.

The DWIM behaviour of this command is as follows:

- When the region is active, disable it.
- When a minibuffer is open, but not focused, close the minibuffer.
- When the Completions buffer is selected, close it.
- In every other case use the regular `keyboard-quit'."
  (interactive)
  (cond
   ((region-active-p)
    (keyboard-quit))
   ((derived-mode-p 'completion-list-mode)
    (delete-completion-window))
   ((> (minibuffer-depth) 0)
    (abort-recursive-edit))
   (t
    (keyboard-quit))))

(define-key global-map (kbd "C-g") #'prot/keyboard-quit-dwim)

;; Some final remapping of Escape to "Quit"

(global-set-key (kbd "<escape>") 'keyboard-quit)

;; When C-g gets rebound.
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))

(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)

(defun ora-ex-point-mark ()
  (interactive)
  (if rectangle-mark-mode
      (exchange-point-and-mark)
    (let ((mk (mark)))
      (rectangle-mark-mode 1)
      (goto-char mk))))

(defhydra hydra-rectangle (:body-pre (rectangle-mark-mode 1)
                           :color pink
                           :post (deactivate-mark))
  "
  ^_k_^     _d_elete    _s_tring     |\\     ‗,,,--,,‗
_h_   _l_   _o_k        _y_ank       /,`.-'`'   .‗  \-;;,‗
  ^_j_^     _n_ew-copy  _r_eset     |,4-  ) )‗   .;.(  `'-'
^^^^        _e_xchange  _u_ndo     '---''(‗/.‗)-'(‗\‗)
^^^^        ^ ^         _p_aste
"
  ("h" backward-char nil)
  ("l" forward-char nil)
  ("k" previous-line nil)
  ("j" next-line nil)
  ("e" ora-ex-point-mark nil)
  ("n" copy-rectangle-as-kill nil)
  ("d" delete-rectangle nil)
  ("r" (if (region-active-p)
           (deactivate-mark)
         (rectangle-mark-mode 1)) nil)
  ("y" yank-rectangle nil)
  ("u" undo nil)
  ("s" string-rectangle nil)
  ("p" kill-rectangle nil)
  ("o" nil nil))

(global-set-key (kbd "C-x SPC") 'hydra-rectangle/body)

;; NOTE: The org-open-at-point will open a "Babel Results" window when this function is called
  ;;       inside a src block
  (defun deftpunk/url-at-point ()
    "Make opening the url at point a little more flexible."
    (interactive)
    (if (string-equal major-mode "org-mode")
        (unless (ignore-errors (or (org-open-at-point) t))
          (ace-link))
      (unless (ignore-errors (or (browse-url-at-point) t))
        (ace-link))))

  (general-create-definer deftpunk-g-def
    :prefix "s-g")

(deftpunk-g-def
    "g"   '(goto-line :which-keys "Go to line number")
    "s-g" '(goto-line :which-keys "Go to line number")
    "o"   '(ace-link :which-keys "Highlight links in document")
    "x"   '(deftpunk/url-at-point :which-keys "Visit link at point")
    )

(global-set-key (kbd "C--") 'ace-window)

;; Move around
(global-set-key (kbd "s-h") 'windmove-left)
(global-set-key (kbd "s-j") 'windmove-down)
(global-set-key (kbd "s-k") 'windmove-up)
(global-set-key (kbd "s-l") 'windmove-right)

(defalias 'ff 'find-file)

;; https://www.reddit.com/r/emacs/comments/r7l3ar/comment/hn3kuwh/?utm_source=share&utm_medium=web2x&context=3
  (defun my/scroll-down-half-page ()
    "scroll down half a page while keeping the cursor centered"
    (interactive)
    (let ((ln (line-number-at-pos (point)))
          (lmax (line-number-at-pos (point-max))))
      (cond ((= ln 1) (move-to-window-line nil))
            ((= ln lmax) (recenter (window-end)))
            (t (progn
                 (move-to-window-line -1)
                 (recenter))))))

  (defun my/scroll-up-half-page ()
    "scroll up half a page while keeping the cursor centered"
    (interactive)
    (let ((ln (line-number-at-pos (point)))
          (lmax (line-number-at-pos (point-max))))
      (cond ((= ln 1) nil)
            ((= ln lmax) (move-to-window-line nil))
            (t (progn
                 (move-to-window-line 0)
                 (recenter))))))


(global-set-key (kbd "s-u") 'my/scroll-up-half-page)
(global-set-key (kbd "s-d") 'my/scroll-down-half-page)

(global-set-key (kbd "s-s") 'consult-line)

  ;; Using C-j for jumping around.
  (global-unset-key (kbd "C-j"))
  (global-set-key (kbd "C-j") 'avy-goto-char-timer)
  (global-set-key (kbd "s-f") 'avy-goto-char-in-line)

  ;; Figure out hippie-expand
  ;; From https://stackoverflow.com/a/43665319
  (defun my-expand-lines ()
    "My old friend C-x C-l in Emacs"
    (interactive)
    (let ((hippie-expand-try-functions-list
       '(try-expand-line)))
      (call-interactively 'hippie-expand)))

  (global-unset-key (kbd "C-x C-l")) ; I can downcase the region another way.
  (global-set-key (kbd "C-x C-l") 'my-expand-lines)

;; Repeating
(global-unset-key (kbd "C-z"))
(global-set-key (kbd "C-.") 'repeat) ; repeats single command w/out minibuffer input, userful for deletions, instertions, movement keys
(global-set-key (kbd "C-z") 'repeat-complex-command) ; repeat complex commands that involve minibuffer input

(defhydra deftpunk-leader ()
  ("g g" magit                "Magit"               :column "Source Control")
  ("g d" magit-dispatch       "Magit Dispatch"      :column "Source Control")
  ("g f" magit-file-dispatch  "Magit File Dispatch" :column "Source Control")
  ("g l" magit-file-dispatch  "Git Link"            :column "Source Control")
  ("g s" magit-status         "Git Status"          :column "Source Control")
  ("g t" git-timemachine-mode "Git Timemachine"     :column "Source Control")
  ("i" consult-buffer         "Buffers"              :column "Buffers/Files/Projects")
  ("p a" project-async-shell-command "Run shell command"   :column "Buffers/Files/Projects")
  ("p p" project-switch-project "Switch Projects"   :column "Buffers/Files/Projects")
  ("t n" treemacs                      "Treemacs"            :column "Utilities")
  ("t t" multi-vterm-dedicated-toggle  "Toggled Vterm"            :column "Utilities")
  )

(global-set-key (kbd "s-<SPC>") 'deftpunk-leader/body)

(use-package key-chord
  :commands (key-chord-define-global)
  :init
  (key-chord-mode 1)
  :config
  (key-chord-define-global "jk" 'execute-extended-command)
  (key-chord-define-global "hh" 'split-window-below)
  (key-chord-define-global "vv" 'split-window-right)
  (key-chord-define-global "  " 'deftpunk-leader/body))

(server-start)
