;;; init.el --- deftpunk Emacs config file -*- lexical-binding: t; -*-
;;;
;;; Commentary:
;;; Emacs `init.el' config for deftpunk
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in emacs.d/deftpunk-emacs.org
;;;
;;; Code:

(defconst deftpunk--emacs-dir (file-truename "~/.emacs.d")
  "The path to the emacs.d directory")

(defconst deftpunk--org-configuration-file (concat deftpunk--emacs-dir "/deftpunk-emacs.org")
  "The Org mode literate configuration file.")

(defconst deftpunk--etc-dir (concat deftpunk--emacs-dir "/etc/")
  "Location for files to save across systems.")

(defconst deftpunk--var-dir (concat deftpunk--emacs-dir "/var/")
  "Location for cache & files that we don't save across systems.")

;; I use Mac & occasionally Linux, no Windoze.
(defconst IS-MAC (eq system-type 'darwin))
(defconst IS-LINUX (eq system-type 'gnu/linux))

(defvar elpaca-installer-version 0.11)
(defvar elpaca-directory (expand-file-name "elpaca/" deftpunk--var-dir))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;; Install a package via the elpaca macro
;; See the "recipes" section of the manual for more details.

;; (elpaca example-package)

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;; Expands to: (elpaca evil (use-package evil :demand t))
;; (use-package evil :demand t)

;;Turns off elpaca-use-package-mode current declaration
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
;; (use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
;; (elpaca nil (message "deferred"))

(use-package general)

(elpaca-wait)

;; Leader key
(general-create-definer deftpunk-leader-def
  :keymaps 'override
  :prefix-map 'deftpunk-leader-map
  :prefix "s-SPC")

;; local leader
;; This allows for finer granularity than hydra-major-mode by binding to individual key maps.
(general-create-definer deftpunk-local-leader-def
  :keymaps 'override
  :prefix "C-;")

(use-package blackout)
(elpaca-wait)

(use-package on
  :ensure (:host github :repo "ajgrf/on.el")
  :config
  (require 'on))

(elpaca-wait)

(use-package which-key
  :blackout
  :commands (which-key-mode which-key-show-toplevel)
  :hook (on-first-input . which-key-mode)
  :custom
  (which-key-enable-exteded-define-key t)
  (which-key-idle-delay 0.5)
  :config
  (which-key-mode +1))

(elpaca-wait)

(use-package transient :ensure t)
(elpaca-wait)

(use-package ox-gfm
  :ensure (ox-gfm :depth treeless))
(elpaca-wait)

(use-package no-littering
  :custom
  (no-littering-etc-directory deftpunk--etc-dir)
  (no-littering-var-directory deftpunk--var-dir))

(elpaca-wait) ; So that other packages know where some Emacs system files are.

(use-package crux
  :bind (("C-a" . crux-move-beginning-of-line)
         ("C-k" . crux-smart-kill-line)
         ("s-o" . crux-smart-open-line-above)
         ("s-RET" . crux-smart-open-line)))

;;; Some convenience macros from our favorite martian - Doom Emacs creator Henrik Lissner ;;;

;; 4/22/2020 - I removed the check to see if the package was
;; in the list of doom-disabled-packages
(defmacro after! (package &rest body)
  "Evaluate BODY after PACKAGE have loaded.

    PACKAGE is a symbol or list of them. These are package names, not modes,
    functions or variables. It can be:

    - An unquoted package symbol (the name of a package)
        (after! helm BODY...)
    - An unquoted list of package symbols (i.e. BODY is evaluated once both magit
      and git-gutter have loaded)
        (after! (magit git-gutter) BODY...)
    - An unquoted, nested list of compound package lists, using any combination of
      :or/:any and :and/:all
        (after! (:or package-a package-b ...)  BODY...)
        (after! (:and package-a package-b ...) BODY...)
        (after! (:and package-a (:or package-b package-c) ...) BODY...)
      Without :or/:any/:and/:all, :and/:all are implied.

    This is a wrapper around `eval-after-load' that:

    1. Suppresses warnings for disabled packages at compile-time
    2. No-ops for package that are disabled by the user (via `package!')
    3. Supports compound package statements (see below)
    4. Prevents eager expansion pulling in autoloaded macros all at once"
  (declare (indent defun) (debug t))
  (if (symbolp package)
      (list (if (or (not (bound-and-true-p byte-compile-current-file))
                    (require package nil 'noerror))
                #'progn
              #'with-no-warnings)
            (let ((body (macroexp-progn body)))
              `(if (featurep ',package)
                   ,body
                 ;; We intentionally avoid `with-eval-after-load' to prevent
                 ;; eager macro expansion from pulling (or failing to pull) in
                 ;; autoloaded macros/packages.
                 (eval-after-load ',package ',body))))
    (let ((p (car package)))
      (cond ((not (keywordp p))
             `(after! (:and ,@package) ,@body))
            ((memq p '(:or :any))
             (macroexp-progn
              (cl-loop for next in (cdr package)
                       collect `(after! ,next ,@body))))
            ((memq p '(:and :all))
             (dolist (next (cdr package))
               (setq body `((after! ,next ,@body))))
             (car body))))))

(defmacro appendq! (sym &rest lists)
  "Append LISTS to SYM in place."
  `(setq ,sym (append ,sym ,@lists)))

;; There are certain buffers I don't want to delete on accident.
;; Code taken from https://github.com/rememberYou/.emacs.d/blob/master/config.org
(defvar *protected-buffers* '("*scratch*" "*Messages*"))

(defun arco/protected-buffers ()
  "Protects some buffers from being killed."
  (dolist (buffer *protected-buffers*)
    (if (get-buffer buffer)
        (with-current-buffer buffer
          (emacs-lock-mode 'kill))
      (get-buffer-create buffer)
      (with-current-buffer buffer
        (emacs-lock-mode 'kill)))))

(general-add-hook 'emacs-startup-hook #'arco/protected-buffers)

  ;;;###autoload
;; https://stackoverflow.com/questions/251908/how-can-i-insert-current-date-and-time-into-a-file-using-emacs
(defun today ()
  "Insert string for today's date nicely formatted in American style,
  e.g. Sunday, September 17, 2000."
  (interactive)                 ; permit invocation in minibuffer
  (insert (format-time-string "%A, %B %e, %Y")))

  ;;;###autoload
(defun flex//kill-current-buffer ()
  "What it says."
  (interactive)
  (kill-buffer (current-buffer)))

(defun vim-return ()
  "Still want Return to do the right thing in dired mode."
  (interactive)
  (if (eq major-mode 'dired-mode)
      (dired-find-file)
    (progn
      (next-line)
      (back-to-indentation-or-beginning))))

;; not broken, toggle letter case from
;; http://ergoemacs.org/emacs/modernization_upcase-word.html][xah]] originally.
;; http://stackoverflow.com/questions/18257573/how-to-toggle-letter-cases-in-a-region-in-emacs
(defun toggle-letter-case ()
  "Toggle the letter case of current word or text selection.
   Toggles between: “all lower”, “Init Caps”, “ALL CAPS”."
  (interactive)
  (let (p1 p2 (deactivate-mark nil) (case-fold-search nil))
    (if (region-active-p)
        (setq p1 (region-beginning) p2 (region-end))
      (let ((bds (bounds-of-thing-at-point 'word) ) )
        (setq p1 (car bds) p2 (cdr bds)) ) )
    (when (not (eq last-command this-command))
      (save-excursion
        (goto-char p1)
        (cond
         ((looking-at "[[:lower:]][[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]][[:upper:]]") (put this-command 'state "all caps") )
         ((looking-at "[[:upper:]][[:lower:]]") (put this-command 'state "init caps") )
         ((looking-at "[[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]]") (put this-command 'state "all caps") )
         (t (put this-command 'state "all lower") ) ) ) )
    (cond
     ((string= "all lower" (get this-command 'state))
      (upcase-initials-region p1 p2) (put this-command 'state "init caps"))
     ((string= "init caps" (get this-command 'state))
      (upcase-region p1 p2) (put this-command 'state "all caps"))
     ((string= "all caps" (get this-command 'state))
      (downcase-region p1 p2) (put this-command 'state "all lower")) )
    ) )

;;
(defun deftpunk/catch-error-p (func-symbol)
  "Call the passed function solely for the purpose of catching its error."
  (let (retval)
    (condition-case error
        (funcall func-symbol)
      ('error (setq retval error)))
    retval))

;; Full history of this function is foggy and lost to time.
;; https://stackoverflow.com/questions/234963/re-open-scratch-buffer-in-emacs
(defun eme-goto-scratch ()
            "this sends you to the scratch buffer"
            (interactive)
            (let ((eme-scratch-buffer (get-buffer-create "*scratch*")))
    (switch-to-buffer eme-scratch-buffer)
    (lisp-interaction-mode)))

;; Some more excellence from karthinks.
(defun repeated-prefix-help-command ()
  (interactive)
  (when-let* ((keys (this-command-keys-vector))
              (prefix (seq-take keys (1- (length keys))))
              (orig-keymap (key-binding prefix 'accept-default))
              (keymap (copy-keymap orig-keymap))
              (exit-func (set-transient-map keymap t #'which-key-abort)))
    (define-key keymap [remap keyboard-quit]
                (lambda () (interactive) (funcall exit-func)))
    (which-key--create-buffer-and-show nil keymap)))
(setq prefix-help-command #'repeated-prefix-help-command)

;; https://github.com/daut/dotfiles/blob/2ad4f5a5e0f1e786c91f17460d8599ec5d57318b/.emacs.d/init.el#L236C1-L241C47
(defun daut/print-current-theme ()
  "Print the currently active theme."
  (interactive)
  (if custom-enabled-themes
      (message "Current theme: %s" (car custom-enabled-themes))
    (message "No theme is currently active")))

(use-package emacs
  :ensure nil
  :custom
  ;; For corfu
  (tab-always-indent 'complete)                    ; indent, if already indented, try to complete
  (text-mode-ispell-word-completion nil)           ; disable Ispell completion - use cape-dict instead.

  (fill-column 105)                                ;
  (help-window-select t)                           ; focus new help windows when opened
  ;; tabs/spaces
  (indent-tabs-mode nil)                           ; No tabs, only spaces
  (tab-width 4)                                    ; 4 spaces
  (load-prefer-newer t)                            ; prefer the newest version of a file.
  ;; mark/kill rings & clipboard
  (kill-ring-max 128)
  (mark-ring-max 128)
  (select-enable-clipboard t)                      ; merge Emacs clipboard w/ system clipboard
  (message-log-max 8192)                           ; don't lose logging info
  (ring-bell-function 'ignore)                     ; turn of the bell!!
  (view-read-only t)                               ; open read-only buffers in view mode.
  ;; title
  (frame-title-format '("Emacs >> %f"))
  (icon-title-format t)                            ; use the frame-title-format for iconified frames.
  (datetime-timezone "America/Denver")

  ;; Emacs 30 and newer: Disable Ispell completion function.
  ;; Try `cape-dict' as an alternative.
  (text-mode-ispell-word-completion nil)

  ;; Hide commands in M-x which do not apply to the current mode.  Corfu
  ;; commands are hidden, since they are not used via M-x. This setting is
  ;; useful beyond Corfu.
  (read-extended-command-predicate #'command-completion-default-include-p)

  :config
  ;; Replace yes/no prompts
  (fset 'yes-or-no-p 'y-or-n-p)



  )

(set-face-attribute 'default nil :font "Menlo" :height 120)
;;(set-face-attribute 'default nil :font "Victor Mono" :height 110)
;;(set-fontset-font t nil "Menlo" nil 'append) ; fallback font

(use-package all-the-icons)

(use-package nerd-icons
  :ensure t)

(use-package nerd-icons-completion
  :ensure t
  :after marginalia
  :config
  (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))

(use-package nerd-icons-corfu
  :ensure t
  :after corfu
  :config
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

(use-package nerd-icons-dired
  :ensure t
  :hook
  (dired-mode . nerd-icons-dired-mode))

(elpaca-wait)

(use-package highlight-numbers
  :hook (prog-mode . highlight-numbers-mode)
  :config
  ;; setting to magenta-warmer for ef-spring theme.
  (set-face-attribute 'highlight-numbers-number nil :foreground "#cb26a0"))

(use-package hl-todo
  :ensure (hl-todo :depth nil) ; see https://github.com/alphapapa/magit-todos/issues/171
  :init
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces '(("TODO" . "#FF0000")
                                ("FIXME" . "#FF9999")
                                ("FAIL" . "#FF0000")
                                ("DEPRECATED" . "#1F39EF")
                                ("HACK" . "#FF0000")
                                ("XXX" . "#FF0000")
                                ("NOTE" . "#1E90FF")))
  :hook (prog-mode . hl-todo-mode))

(use-package doom-modeline
  :custom
  (doom-modeline-project-detection 'projectile)
  (doom-modeline-buffer-file-name-style 'truncate-upto-root)
  (doom-modeline-buffer-name t)
  (doom-modeline-vcs-max-length 35)
  (doom-modeline-env-enable-python nil) ; because we use ipython/conda/etc. & what is Python can change frequently.
  (doom-modeline-icon t)
  :init
  (doom-modeline-mode 1)
  :config
  (setq inhibit-compacting-font-caches t) ;; Don´t compact font caches during GC

  ;; This in combination w/ reducing the height allows everything to fit on the modeline.
  (setq nerd-icons-scale-factor 1.1)

  (unless (eq system-type 'darwin)
    (if (facep 'mode-line-active)
        (set-face-attribute 'mode-line-active nil
                            :family "Hack"
                            :height 100) ; For 29+
      (set-face-attribute 'mode-line nil
                          :family "Hack"
                          :height 100))
    (set-face-attribute 'mode-line-inactive nil
                        :family "Hack"
                        :height 100))

  (when (eq system-type 'darwin)
    (if (facep 'mode-line-active)
        (set-face-attribute 'mode-line-active nil
                            :family "Hack Nerd Font"
                            :height 110) ; For 29+
      (set-face-attribute 'mode-line nil
                          :family "Hack Nerd Font"
                          :height 110))
    (set-face-attribute 'mode-line-inactive nil
                        :family "Hack Nerd Font"
                        :height 110)))

(use-package doom-themes
  :ensure t
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled

  ;; (load-theme 'doom-solarized-light t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)

  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-colors") ; use "doom-colors" for less minimal icon theme
  (doom-themes-treemacs-config)

  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))

(use-package ef-themes
  :custom
  (ef-themes-mixed-fonts t)
  (ef-themes-variable-pitch-ui t)
  :config
  (load-theme 'ef-light t)
  )

(use-package solarized-theme
  :init
  ;; make the fringe stand out from the background
  (setq solarized-distinct-fringe-background t)

  ;; Don't change the font for some headings and titles
  (setq solarized-use-variable-pitch t)

  ;; make the modeline high contrast
  (setq solarized-high-contrast-mode-line nil)

  ;; Use less bolding
  (setq solarized-use-less-bold nil)

  ;; Use more italics
  (setq solarized-use-more-italic t)

  ;; Use less colors for indicators such as git:gutter, flycheck and similar
  (setq solarized-emphasize-indicators t)

  ;; Don't change size of org-mode headlines (but keep other size-changes)
  (setq solarized-scale-org-headlines t)

  ;; Change the size of markdown-mode headlines (off by default)
  (setq solarized-scale-markdown-headlines t)

  ;; Avoid all font-size changes
  ;; (setq solarized-height-minus-1 1.0)
  ;; (setq solarized-height-plus-1 1.0)
  ;; (setq solarized-height-plus-2 1.0)
  ;; (setq solarized-height-plus-3 1.0)
  ;; (setq solarized-height-plus-4 1.0)

  ;; Highlight all numbers
  (setq solarized-highlight-numbers t)

  :config
  ;; (load-theme 'solarized-light t)
  )

(use-package minibuffer
  :ensure nil
  :general
  (:keymaps 'minibuffer-mode-map
            "C-w" #'backward-kill-word))

(elpaca-wait)

;; https://github.com/daut/dotfiles/blob/2ad4f5a5e0f1e786c91f17460d8599ec5d57318b/.emacs.d/init.el#L105
(defun daut/minibuffer-backward-kill (arg)
  (interactive "p")
  (if (and minibuffer-completing-file-name
       (eq (char-before) ?/))
  (zap-up-to-char (- arg) ?/)
    (delete-backward-char arg)))

(use-package vertico
  :ensure t
  :after minibuffer
  :commands (vertico-mode
             vertico-insert
             vertico-exit)
  :hook (after-init . vertico-mode)
  :general
  (:keymaps 'vertico-map
            "C-e" #'vertico-move-end-of-line-or-insert
            "<backspace>" #'daut/minibuffer-backward-kill
            "<escape>" #'minibuffer-keyboard-quit)
  ;;"C-w" #'backward-kill-word)
  :custom
  (vertico-cycle t)
  (vertico-count 45)
  (vertico-resize t)  ; allow vertico size to shrink and grow based on vertico count
  :init

  (defun vertico-move-end-of-line-or-insert (arg)
    "Move to end of line or insert current candidate.
   ARG lines can be used.

   When only one candidate exists exit input after insert."
    (interactive "p")
    (if (eolp)
        (progn
          (vertico-insert)
          (when (= vertico--total 1)
            (vertico-exit)))
      (move-end-of-line arg)))

  (vertico-mode t))

;;(use-package vertico-posframe
;;  :ensure t
;;  :init (vertico-posframe-mode)
;;  :config
;;  (setq vertico-multiform-commands
;;    '((consult-line (:not posframe))
;;      (consult-ripgrep (:not posframe))
;;      (t posframe)))
;;  (vertico-multiform-mode t))

(use-package marginalia
  :ensure t
  :general
  (:keymaps 'minibuffer-local-map
            "s-a" 'marginalia-cycle)
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'left)
  :init
  (marginalia-mode 1))

(use-package orderless
  :ensure t
  :custom
  (completion-category-defaults nil)
  (completion-styles '(substring orderless basic))
  (completion-category-overrides '((file (styles basic
					                             partial-completion)))))

(use-package embark
  :ensure t
  :bind (("C-." . embark-act)
         ("s-." . embark-dwim)
         ("C-h B" . embark-bindings)
         :map minibuffer-local-map
         ("C-c C-c" . embark-collect)
         ("C-c C-e" . embark-export))
  :init
  (setq prefix-help-command #'embark-prefix-help-command)

  :config
  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

(use-package embark-consult
  :ensure t
  :after (embark consult)
  :demand t
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))

(use-package consult
  :ensure t
  :bind (("C-c r" . consult-ripgrep)
         ("s-i" . consult-buffer)
         ("s-s" . consult-line)
         ("s-r" . consult-ripgrep)
         ([remap Info-search] . consult-info)
         ;; Misc bindings
         ("s-y" . consult-yank-pop))

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)

  :init

  ;; Optionally configure the register formatting. This improves the register
  (setq register-preview-delay 0.25
        register-preview-function #'consult-register-format)

  ;; Optionally tweak the register preview window.
  (advice-add #'register-preview :override #'consult-register-window)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)

  :config

  ;; Optionally configure preview. The default value
  ;; is 'any, such that any key triggers the preview.
  ;; (setq consult-preview-key 'any)
  ;; (setq consult-preview-key "M-.")
  ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
  ;; For some commands and buffer sources it is useful to configure the
  ;; :preview-key on a per-command basis using the `consult-customize' macro.
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep consult-man
   consult-bookmark consult-recent-file consult-xref
   consult--source-bookmark consult--source-file-register
   consult--source-recent-file consult--source-project-recent-file
   ;; :preview-key "M-."
   :preview-key '(:debounce 0.4 any))

  ;; Narrowing
  (setq consult-narrow-key "<") ; Prefix key for narrowing results
  (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help) ; get help for narrowing

  (define-key consult-narrow-map [C-left] #'consult-narrow-cycle-backward)
  (define-key consult-narrow-map [C-right] #'consult-narrow-cycle-forward)

  (defun consult-narrow-cycle-backward ()
    "Cycle backward through the narrowing keys."
    (interactive)
    (when consult--narrow-keys
      (consult-narrow
       (if consult--narrow
           (let ((idx (seq-position consult--narrow-keys
                                    (assq consult--narrow consult--narrow-keys))))
             (unless (eq idx 0)
               (car (nth (1- idx) consult--narrow-keys))))
         (caar (last consult--narrow-keys))))))

  (defun consult-narrow-cycle-forward ()
    "Cycle forward through the narrowing keys."
    (interactive)
    (when consult--narrow-keys
      (consult-narrow
       (if consult--narrow
           (let ((idx (seq-position consult--narrow-keys
                                    (assq consult--narrow consult--narrow-keys))))
             (unless (eq idx (1- (length consult--narrow-keys)))
               (car (nth (1+ idx) consult--narrow-keys))))
         (caar consult--narrow-keys)))))
  )

(setq-default save-abbrevs 'silently)

;; Turn abbreviations on globally.
(setq-default abbrev-mode t)
(blackout 'abbrev-mode)

;; Read the abbrev file on startup.
(quietly-read-abbrev-file)

(defun deftpunk/current-time ()
  (interactive)
  (insert (format-time-string "%D %T")))
(define-abbrev global-abbrev-table "ydate" "" 'deftpunk/current-time)

;; Revert Dired and other buffers
(setq global-auto-revert-non-file-buffers t)
;; Revert buffers when the underlying file has changed.
(global-auto-revert-mode 1)

(column-number-mode 1)

(after! compile
  (setq compilation-always-kill t       ; kill compilation process before starting another.
        compilation-ask-about-save nil  ; save all buffers.
        compilation-auto-jump-to-first-error t
        compilation-scroll-output 'first-error)

  ;; Take care of color codes in the output and colorize the compilation buffer.
  (add-hook 'compilation-filter-hook 'ansi-color-compilation-filter)

  (autoload 'comint-truncate-buffer "comint" nil t)
  (add-hook 'compilation-filter-hook #'comint-truncate-buffer)
  )

(setopt compilation-ask-about-save nil)

(deftpunk-local-leader-def
  :keymaps 'compilation-mode-map
  "o" '(ace-link :which-keys "Highlight links in compilation buffer"))

(use-package delsel
  :ensure nil ; no need to install it as it is built-in
  :hook (after-init . delete-selection-mode))

(use-package ediff
  :ensure nil
  :custom
  (ediff-diff-options "-w")
  (ediff-use-long-help-message t)
  (ediff-window-setup-function #'ediff-setup-windows-plain)
  (ediff-split-window-function #'split-window-horizontally)
  (ediff-merge-split-window-function #'split-window-horizontally)
  :config

;; I just want to restore the previous window layout... so hard.
;; Added to and modified from https://emacs.stackexchange.com/questions/7482/restoring-windows-and-layout-after-an-ediff-session
(defvar my-ediff-last-windows nil
  "Window configuration prior to calling `ediff-buffers',
`ediff-regions-linewise', or `ediff-regions-wordwise'.")

(defun my-ediff-restore-last-windows ()
  "Set window configuration to `my-ediff-last-windows'."
  (cond (my-ediff-last-windows
         (set-window-configuration my-ediff-last-windows)
         (setq my-ediff-last-windows nil))))

(add-hook 'ediff-quit-hook #'my-ediff-restore-last-windows)

(defadvice ediff-buffers (before ediff-buffers-advice activate)
  (setq my-ediff-last-windows (current-window-configuration)))

(defadvice ediff-regions-linewise (before ediff-regions-linewise-advice activate)
  (setq my-ediff-last-windows (current-window-configuration)))

(defadvice ediff-regions-wordwise (before ediff-regions-wordwise-advice activate)
  (setq my-ediff-last-windows (current-window-configuration)))

;; For ediff-buffers/ediff-files
(defvar ediff-last-windows nil
  "Last ediff window configuration.")

(defun ediff-restore-windows ()
  "Restore window configuration to `ediff-last-windows'."
  (set-window-configuration ediff-last-windows)
  (remove-hook 'ediff-after-quit-hook-internal
               'ediff-restore-windows))

(defadvice ediff-buffers (around ediff-restore-windows activate)
  (setq ediff-last-windows (current-window-configuration))
  (add-hook 'ediff-after-quit-hook-internal 'ediff-restore-windows)
  ad-do-it)

(defadvice ediff-files (around ediff-restore-windows activate)
  (setq ediff-last-windows (current-window-configuration))
  (add-hook 'ediff-after-quit-hook-internal 'ediff-restore-windows)
  ad-do-it)
)

(use-package hl-line
  :ensure nil
  :custom
  (hl-line-sticky-flag nil) ; Don't highlight current line across windows.
  :config
  (defun eat/hl-line-setup ()
    "Disable `hl-line-mode' if region is active."
    (when (and (bound-and-true-p hl-line-mode)
               (region-active-p))
      (hl-line-unhighlight)))

  (with-eval-after-load 'hl-line
    (add-hook 'post-command-hook #'eat/hl-line-setup))

  (add-hook 'prog-mode-hook #'hl-line-mode)
  (add-hook 'text-mode-hook #'hl-line-mode))

(use-package isearch
  :ensure nil
  :defer t
  :bind
  (:map isearch-mode-map
        ([remap isearch-query-replace] . anzu-isearch-query-replace)
        ([remap isearch-query-replace-regexp] . anzu-isearch-query-replace-regexp)
        ("C-d" . isearch-forward-thing-at-point)
        ("C-h" . anzu-isearch-query-replace)
        ("C-l" . my-isearch-consult-line-from-isearch))
  :config
  (defun my-isearch-consult-line-from-isearch ()
    "Invoke `consult-line' from isearch."
    (interactive)
    (let ((query (if isearch-regexp
                     isearch-string
                   (regexp-quote isearch-string))))
      (isearch-update-ring isearch-string isearch-regexp)
      (let (search-nonincremental-instead)
        (ignore-errors (isearch-done t t)))
      (consult-line query)))

  )

(use-package emacs
  :ensure nil
  :custom
  (recentf-max-saved-items 250)
  (recentf-max-menu-items 15)
  ;; disable recentf-cleanup on Emacs start, because it can cause
  ;; problems with remote files, ie. Tramp files.
  (recentf-save-file "~/.emacs.d/etc/recentf-save.el")
  (recentf-auto-cleanup 'never)
  (recentf-exclude (list "/scp:"
                         "/ssh:"
                         "/sudo:"
                         "/tmp/"
                         "~$"
                         "COMMIT_EDITMSG"
                         ))
  :config
  (recentf-mode +1))

(setq savehist-file (expand-file-name "savehist" deftpunk--var-dir)
      history-length 65                                                ; reducing size helps reduce startup cost.
      history-delete-duplicates t
      savehist-save-minibuffer-history t
      savehist-additional-variables '(kill-ring
                                      search-ring
                                      mark-ring
                                      global-mark-ring
                                      regexp-search-ring
                                      extended-command-history
                                      regexp-search-ring))
(savehist-mode 1)

;; Limit some of the items in savehist
(put 'savehist-minibuffer-history-variables 'history-length 50)
(put 'org-read-date-history                 'history-length 50)
(put 'read-expression-history               'history-length 50)
(put 'org-table-formula-history             'history-length 50)
(put 'extended-command-history              'history-length 50)
(put 'ido-file-history                      'history-length 50)
(put 'helm-M-x-input-history                'history-length 50)
(put 'minibuffer-history                    'history-length 50)
(put 'ido-buffer-history                    'history-length 50)
(put 'buffer-name-history                   'history-length 50)
(put 'file-name-history                     'history-length 50)

(use-package saveplace
  :ensure nil
  :custom
  (save-place-limit 100)
  (save-place-file (expand-file-name "emacs-places" deftpunk--var-dir))
  (save-place-forget-unreadable-files nil)  ; Setting to t has the potential to make exiting slow
  :config
  (save-place-mode 1)
  (add-hook 'save-place-find-file-hook 'recenter)
  (add-hook 'find-file-hook 'save-place-find-file-hook t))

(use-package tramp
  :ensure nil
  :custom
  (tramp-default-method "ssh")
  ;; https://www.reddit.com/r/emacs/comments/lp8bjb/comment/goai6ig/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
  (tramp-ssh-controlmaster-options (concat
                                    "-o ControlPath=\~/.ssh/cons/ssh-%%r@%%h:%%p "
                                    "-o ControlMaster=auto -o ControlPersist=yes"))
  :config
  (setq remote-file-name-inhibit-cache nil)
  (setq vc-ignore-dir-regexp
        (format "%s\\|%s"
                vc-ignore-dir-regexp
                tramp-file-name-regexp))
  (setq tramp-verbose 1))

(setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow))
(global-visual-line-mode)
(blackout 'visual-line-mode)

(use-package dired
  :ensure nil
  :general
  (:keymaps 'dired-mode-map
            "RET" #'dired-find-alternate-file
            "^" (lambda ()
                  (interactive)
                  (find-alternate-file "..")))
  :custom
  ;; Allow dired to delete or copy a dir.
  ;; 02/14/24 17:41:48 - These default to 'top in dired now.
  ;; 'top means ask every time.
  ;; 'always means don't ask.
  (dired-recursive-copies 'top)
  (dired-recursive-deletes 'top)
  :config

  ;; Open marked files in dired
  ;; http://xahlee.info/emacs/emacs/emacs_dired_open_marked.html
  (defun xah-dired-open-marked ()
    "Open marked files in `dired'.
URL `http://xahlee.info/emacs/emacs/emacs_dired_open_marked.html'
Version 2019-10-22"
    (interactive)
    (mapc 'find-file (dired-get-marked-files)))

  ;; Make dired open in the same window when using RET or ^
  ;; Make Dired only use a single buffer when visiting a directory.
  ;; http://ergoemacs.org/emacs/emacs_dired_tips.html
  (put 'dired-find-alternate-file 'disabled nil) ; disables warning
  (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file) ; was dired-advertised-find-file
  (define-key dired-mode-map (kbd "^") (lambda ()
                                         (interactive)
                                         (find-alternate-file ".."))))  ; was dired-up-directory

(use-package dired+
  :ensure (dired+ :type git :host github :repo "emacsmirror/dired-plus"))

;; 12/02/24 23:05:16 changed from :general to :bind in order to avoid "dired-subtree/:catch: Wrong
;; type argument: listp, dired-subtree-toggle" error... ??
(use-package dired-subtree
  :ensure t
  :after dired
  :bind (:map dired-mode-map
            ("i" . dired-subtree-insert)
            (";" . dired-subtree-remove)
            ("<tab>" . dired-subtree-toggle)
            ("<backtab>" . dired-subtree-cycle)
            ("S-TAB" . dired-subtree-cycle)
            ))

(use-package dired-sidebar
  :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
  :general
  (deftpunk-leader-def
    "tn" '(dired-sidebar-toggle-sidebar))
  :ensure t
  :commands (dired-sidebar-toggle-sidebar)
  :init
  (add-hook 'dired-sidebar-mode-hook
            (lambda ()
              (unless (file-remote-p default-directory)
                (auto-revert-mode))))
  :config
  (push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
  (push 'rotate-windows dired-sidebar-toggle-hidden-commands)

  (setq dired-sidebar-subtree-line-prefix "   ")
  (setq dired-sidebar-theme 'nerd-icons)
  ;; (setq dired-sidebar-theme 'all-the-icons)
  (setq dired-sidebar-use-term-integration t)
  (setq dired-sidebar-use-custom-font t))

;; TODO: set the frame size
;; TODO: When 'quit' close this frame as well
(defun dftpunk/elfeed-new-frame ()
  "Open elfeed in a different frame"
  (interactive)
  (make-frame)
  (elfeed))

(use-package elfeed
  :ensure t
  :defer t
  :custom
  (url-queue-timeout 30)  ; try to avoid "Queue timeout exceeded" errors.
  ;; Prefer the curl we install via homebrew
  (elfeed-curl-program-name "/opt/homebrew/opt/curl/bin/curl")
  (elfeed-db-directory (expand-file-name "elfeed" user-emacs-directory))
  (elfeed-show-entry-switch 'display-buffer)
  :bind
  (("C-c e" . elfeed )))

 (defun my-elfeed-mark-all-read ()
   (interactive)
   (elfeed-untag elfeed-search-entries 'unread)
   (elfeed-search-update :force)) ; redraw

(use-package elfeed-org
  :ensure t
  :commands (elfeed-org)
  :custom
  (rmh-elfeed-org-files (list (expand-file-name "elfeed.org" deftpunk--etc-dir)))
  :config
  (elfeed-org))

(use-package company
  :hook (after-init . global-company-mode)
  :custom
  (company-idle-delay 0.0)
  (company-minimum-prefix-length 1)
  (company-selection-wrap-around t))

;; Use Dabbrev with Corfu!
(use-package dabbrev
  :ensure nil
  ;; Swap M-/ and C-M-/
  :bind (("M-/" . dabbrev-completion)
         ("C-M-/" . dabbrev-expand))
  :config
  (add-to-list 'dabbrev-ignored-buffer-regexps "\\` ")
  ;; Since 29.1, use `dabbrev-ignored-buffer-regexps' on older.
  (add-to-list 'dabbrev-ignored-buffer-modes 'doc-view-mode)
  (add-to-list 'dabbrev-ignored-buffer-modes 'pdf-view-mode)
  (add-to-list 'dabbrev-ignored-buffer-modes 'tags-table-mode))

(use-package yasnippet-snippets)

(use-package yasnippet
  :hook ((prog-mode
          conf-mode
          text-mode
          snippet-mode) . yas-minor-mode-on)
  :custom
  (yas-verbosity 3)
  (yas-also-auto-indent-first-line t)
  :init
  ;; Remove default ~/.emacs.d/snippets
  ;; (defvar yas-snippet-dirs nil)

  :config
  ;; Allow private snippets.
  (add-to-list 'yas-snippet-dirs (expand-file-name "snippets" user-emacs-directory))
  ;; Only way I could get this to work.
  ;; (require 'yasnippet)
  ;; (yas-global-mode 1)

  )

;;(elpaca-wait)

(use-package ace-window
  :general
  ("C--" #'ace-window)
  :init
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
        aw-leading-char-style 'path
        aw-background t
        aw-dispatch-always t)
  :general
  (deftpunk-leader-def
    "wc" '("close window" . ace-delete-window)
    "wo" '("close other window" . ace-delete-other-windows)
    "ww" '("ace window" . ace-window))
  :config
  (set-face-attribute 'aw-leading-char-face nil :height 4.0))

(use-package beframe
  :bind ("C-c b" . beframe-prefix-map)
  :custom
  (beframe-global-buffers '("*scratch*" "*Messages*" "*Backtrace*"))
  :config
  (defvar consult-buffer-sources)
  (declare-function consult--buffer-state "consult")

  (with-eval-after-load 'consult
    (defface beframe-buffer
      '((t :inherit font-lock-string-face))
      "Face for `consult' framed buffers.")

    (defun my-beframe-buffer-names-sorted (&optional frame)
      "Return the list of buffers from `beframe-buffer-names' sorted by visibility.
With optional argument FRAME, return the list of buffers of FRAME."
      (beframe-buffer-names frame :sort #'beframe-buffer-sort-visibility))

    (defvar beframe-consult-source
      `( :name     "Frame-specific buffers (current frame)"
         :narrow   ?F
         :category buffer
         :face     beframe-buffer
         :history  beframe-history
         :items    ,#'my-beframe-buffer-names-sorted
         :action   ,#'switch-to-buffer
         :state    ,#'consult--buffer-state))

    (add-to-list 'consult-buffer-sources 'beframe-consult-source))
  (beframe-mode 1))

(use-package emacs
  :ensure nil
  :bind (("H-m" . my/monocle-mode)
         ("C-x C-1" . my/monocle-mode))
  :config
  (defvar my/window-configuration nil
    "Current window configuration.
Intended for use by `my/monocle-mode.")

  (define-minor-mode my/monocle-mode
    "Toggle between multiple windows and single window.
This is the equivalent of maximising a window.  Tiling window
managers such as DWM, BSPWM refer to this state as 'monocle'."
    :lighter " [M]"
    :global nil
    (let ((win my/window-configuration))
      (if (one-window-p)
          (when win
            (set-window-configuration win))
        (setq my/window-configuration (current-window-configuration))
        (when (window-parameter nil 'window-slot)
            (let ((buf (current-buffer)))
              (other-window 1)
              (switch-to-buffer buf)))
        (delete-other-windows)))))

(use-package transpose-frame
  :bind
  (("C-x 4 t" . transpose-frame)
   ("C-x 4 r" . rotate-frame-clockwise))
  )

(use-package windmove
  :ensure nil
  :bind (("s-h" . windmove-left)
         ("s-j" . windmove-down)
         ("s-k" . windmove-up)
         ("s-l" . windmove-right)))

(use-package winner
  :ensure nil
  :custom
  ;; Ignore all the *<name>* buffers by regex.
  (winner-boring-buffers-regexp "^\\*")
  :config
  (winner-mode +1))

(use-package emacs
  :ensure nil
  :config
  (defadvice keyboard-escape-quit
      (around keyboard-escape-quit-dont-close-windows activate)
    (let ((buffer-quit-function (lambda () ())))
      ad-do-it)))

(use-package ace-link
  :init (ace-link-setup-default))

(use-package avy
  :commands (avy-goto-char-timer avy-goto-char-in-line)
  :bind (("C-j" . avy-goto-char-timer)
         ("s-f" . avy-goto-char-in-line))
  :config
  (setq avy-all-windows nil
        avy-background t))

(use-package goto-last-change
  :general ("C-x C-\\" #'goto-last-change)
  :config
  (require 'goto-last-change))

(use-package goto-line-preview
  :commands (goto-line-preview)
  :general ([remap goto-line] #'goto-line-preview)
  :custom
  (goto-line-preview-hl-duration 2.5)
  :config
  (set-face-background 'goto-line-preview-hl "white"))

(use-package expand-region
  :bind ("C-=" . er/expand-region))

(use-package move-text
  :config
  (defun indent-region-advice (&rest ignored)
    "Indent after moving"
    (let ((deactivate deactivate-mark))
      (if (region-active-p)
          (indent-region (region-beginning) (region-end))
        (indent-region (line-beginning-position) (line-end-position)))
      (setq deactivate-mark deactivate)))

  (advice-add 'move-text-up :after 'indent-region-advice)
  (advice-add 'move-text-down :after 'indent-region-advice))

;; Cuz general won't  add these as part of use-package declaration??
(global-set-key (kbd "s-C-j") #'move-text-down)
(global-set-key (kbd "s-C-k") #'move-text-up)

(use-package smart-hungry-delete
  :bind (([remap backward-delete-char-untabify] . smart-hungry-delete-backward-char)
         ([remap delete-backward-char] . smart-hungry-delete-backward-char)
         ([remap delete-char] . smart-hungry-delete-forward-char))
  :init (smart-hungry-delete-add-default-hooks))

(use-package undo-fu)

(use-package undo-fu-session
  :config
  (setq undo-fu-session-incompatible-files '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
  (undo-fu-session-global-mode))
(elpaca-wait)

(use-package vundo
  :commands (vundo)
  :ensure (vundo :type git :host github :repo "casouri/vundo")
  :bind
  (("C-c u" . vundo))
  :custom
  ;; Take less on-screen space.
  (vundo-compact-display t)
  :config

  ;; Better contrasting highlight.
  (custom-set-faces
   '(vundo-node ((t (:foreground "#808080"))))
   '(vundo-stem ((t (:foreground "#808080"))))
   '(vundo-highlight ((t (:foreground "#FFFF00")))))

  ;; Add arrows to the movement
  (define-key vundo-mode-map (kbd "<right>") #'vundo-forward)
  (define-key vundo-mode-map (kbd "<left>") #'vundo-backward)
  (define-key vundo-mode-map (kbd "<down>") #'vundo-next)
  (define-key vundo-mode-map (kbd "<up>") #'vundo-previous)
  (define-key vundo-mode-map (kbd "<home>") #'vundo-stem-root)
  (define-key vundo-mode-map (kbd "<end>") #'vundo-stem-end)
  (define-key vundo-mode-map (kbd "q") #'vundo-quit)
  (define-key vundo-mode-map (kbd "C-g") #'vundo-quit)
  (define-key vundo-mode-map (kbd "RET") #'vundo-confirm))

(use-package wgrep
  :ensure t
  :bind (:map grep-mode-map
              ("e" . wgrep-change-to-wgrep-mode)
              ("C-x C-q" . wgrep-change-to-wgrep-mode)
              ("C-c C-c" . wgrep-finish-edit)))

(use-package ws-butler
  :ensure (ws-butler :type git :host github :repo "hlissner/ws-butler")
  :blackout t
  :hook ((text-mode . ws-butler-mode)
         (prog-mode . ws-butler-mode))
  :custom
  (ws-butler-keep-whitespace-before-point nil))

;; show trailing whitespace
(setq show-trailing-whitespace t)

(with-eval-after-load 'ws-butler
  (blackout 'ws-butler-mode))

(use-package org
  :ensure nil
  :blackout (org-mode . " Org")
  :hook ((org-mode . (lambda () (toggle-truncate-lines nil))))
  :general
  (:keymaps 'org-mode-map
        "C-c C-'" 'org-edit-special)
  (:keymaps 'org-src-mode-map
        "C-c C-'" 'org-edit-src-exit)
  :custom
  (org-use-speed-commands t)      ; faster navigation
  (org-fontify-quote-and-verse-blocks t)    ; quote/verse blocks show up better
  (org-return-follows-link t)
  (org-src-fontify-natively t)
  (org-startup-indented t)
  (org-pretty-entities t)
  (org-hide-emphasis-markers t)       ; show italicized text instead of /italicized text/
  (org-startup-with-inline-images t)
  (org-image-actual-width '(300))
  (org-src-window-setup 'split-window-below)
  :init
  ;; Load python as well as emacs-lisp by default.  Other languages are lazy loaded.
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)))
  :config
  ;; Moving general bindings here to reduce startup penalty.

  ;; Create a sparse tree view of TODOs in the current Org buffer.
  ;; https://stackoverflow.com/a/63195446
  ;; You can use C-x 4 0 to kill the buffer and window when done.
  (defun org-todo-buffer ()
    "Create new indirect buffer with sparse tree of undone TODO items"
    (interactive)
    (clone-indirect-buffer "*org TODO undone*" t)
    (org-show-todo-tree nil) ; mimics interactive usage
    (org-remove-occur-highlights))

  ;; Keys for org-mode-map
  (general-define-key
   :keymaps 'org-mode-map
   ;; so that C-j actually is mapped to avy-goto-char-timer
   "C-j" 'nil
   "C-k" 'nil
   ;; so that we can use it as help prefix
   "M-h" 'nil)

  ;; Local leader bindings.
  (deftpunk-local-leader-def
    :keymaps 'org-mode-map
    "a" '(org-todo-buffer :which-key "Show TODOs for current buffer.")
    "d" '(org-todo :which-key "Org Todo + Todo States")
    "e" '(org-edit-special :which-key "Edit blk in special buffer")
    "h" '(consult-org-heading :which-key "Find Org heading in current buffer.") ; https://github.com/minad/consult/blob/main/consult-org.el
    "i" '(org-insert-link :which-key "Org Insert link")
    "n" '(org-babel-next-src-block :which-key "Go to the next src block")
    "o" '(ace-link-org :which-key "Links in Org mode document")
    "p" '(org-babel-previous-src-block :which-key "Go to previous src block")
    "s" '(org-insert-structure-template :which-key "Insert templates")
    "t" '(org-babel-tangle :which-key "Tangle the src blocks")
    "u" '(org-babel-goto-src-block-head :which-key "Go to the head of the src block")
    "x" '(org-open-at-point :which-key "Open link at point")
    "y" '(org-download-screenshot file :which-key "Yank screenshot"))
  )

;; More "keep off my modeline"
(with-eval-after-load 'org-indent
  (blackout 'org-indent-mode))

(use-package org-auto-tangle
  :hook (org-mode . org-auto-tangle-mode))

;; The joys of hooks and loading.
(with-eval-after-load 'org-auto-tangle
  (blackout 'org-auto-tangle-mode))

;; https://github.com/minad/org-modern/issues/106#issuecomment-1344659316
;; Fixes issue mentioned above
(defun disable-point-adjustment (&rest args)
  (setq disable-point-adjustment t))
(advice-add 'org-beginning-of-line :after #'disable-point-adjustment)

(use-package org-modern
  :blackout
  :after org
  :init
  (setq org-modern-hide-stars nil
        ;; I prefer just the circle
        org-modern-star '("○" "○" "○" "○" "○" "○")
        org-auto-align-tags nil
        org-tags-column 0
        org-catch-invisible-edits 'show-and-error
        org-special-ctrl-a/e t
        org-insert-heading-respect-content t

        ;; Org styling, hide markup etc.
        org-ellipsis "…"

        ;; Agenda styling
        org-agenda-tags-column 0
        org-agenda-block-separator ?─
        org-agenda-time-grid
        '((daily today require-timed)
          (800 1000 1200 1400 1600 1800 2000)
          " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
        org-agenda-current-time-string
        "⭠ now ─────────────────────────────────────────────────")
  :config
  (global-org-modern-mode))

(use-package ghelp
  :ensure (:host github :repo "casouri/ghelp")
  :defer t
  :bind
  (("C-h C-h" . ghelp-describe)
   (:map ghelp-page-mode-map
         ("o" . ace-link-help))
   (:map help-map
         ("A" . ghelp-describe-elisp)
         ("f" . ghelp-describe-function)
         ("k" . ghelp-describe-key)
         ("v" . ghelp-describe-variable))
   (:map goto-map
         ("h" . ghelp-describe-at-point))))

(use-package helpful
  :defer t
  :commands (helpful-callable
             helpful-variable
             helpful-key
             helpful-command
             helpful-at-point
             helpful-function)
  :general
  ([remap describe-function]  #'helpful-callable
   [remap describe-command]   #'helpful-command
   [remap describe-variable]  #'helpful-variable
   [remap display-local-help] #'helpful-at-point
   [remap describe-symbol]    #'helpful-symbol
   [remap describe-key]       #'helpful-key
   "C-h x"                    #'helpful-macro)
  :custom
  (helpful-max-buffers 7))

(use-package jinx
  :hook (emacs-startup . global-jinx-mode)
  :bind (("M-$" . jinx-correct)
         ("C-M-$" . jinx-languages)))

(use-package blamer
  :ensure (:host github :repo "artawower/blamer.el")
  :defer t
  :general
  (deftpunk-leader-def
    "gi" '("Blamer show commit info" . blamer-show-commit-info))
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 70)
  :custom-face
  (blamer-face ((t :foreground "#7a88cf"
                   :background "unspecified"
                   :height 120
                   :italic t)))
  :config
  (global-blamer-mode 1))

(use-package browse-at-remote
  :defer t
  :commands (browse-at-remote)
  :general
  (deftpunk-leader-def
    "gr" '("Browse file in browser" . browse-at-remote)
    )
  :config
  ;; Add the HPE github.
  (add-to-list 'browse-at-remote-remote-type-regexps
               `(:host ,(rx bol "github.hpe.com" eol)
                       :type "github"
                       :actual-host "github.hpe.com")))

(use-package consult-gh
  :load-path "~/Downloads/consult-gh"
  :after consult
  :config
  (require 'consult-gh-transient)
  (require 'consult-gh-with-pr-review)
  (require 'consult-gh-embark)
                                        ;(require 'consult-gh-forge)
  (consult-gh-embark-mode +1)
  (consult-gh-with-pr-review-mode +1)
                                        ;(consult-gh-forge-mode +1))
  )

(use-package pr-review)

;; From Doom Emacs ui/vc-gutter/config.el
;; UI: make the fringe small enough that the diff bars aren't too domineering,
;;   while leaving enough room for other indicators.
(if (fboundp 'fringe-mode) (fringe-mode '8))
;; UI: the gutter looks less cramped with some space between it and  buffer.
(setq-default fringes-outside-margins t)

(use-package diff-hl
  :defer t
  :hook ((find-file . diff-hl-mode)
         (vc-dir-mode . diff-hl-dir-mode)
         (dired-mode . diff-hl-dired-mode)
         (magit-pre-refresh . diff-hl-magit-pre-refresh)
         (magit-post-refresh . diff-hl-magit-post-refresh))
  :custom
  (diff-hl-draw-borders nil)
  :config

  ;; From Doom:
  ;; PERF: A slightly faster algorithm for diffing.
  (setq vc-git-diff-switches '("--histogram"))
  ;; PERF: Slightly more conservative delay before updating the diff
  (setq diff-hl-flydiff-delay 0.5)  ; default: 0.3
  ;; PERF: don't block Emacs when updating vc gutter
  (setq diff-hl-update-async t)

  ;; UX: get realtime feedback in diffs after staging/unstaging hunks.
  (setq diff-hl-show-staged-changes nil)
  (global-diff-hl-mode))

(use-package git-link
  :custom
  (git-link-open-in-browser t))

(use-package git-modes
  :config
  ;; This works for .dockerignore and other .*ignore files as well.
  (dolist (pattern '("/.dockeringnore\\'"))
    (add-to-list 'auto-mode-alist (cons pattern #'gitignore-mode))))

(use-package git-timemachine
  :defer t
  :commands (git-timemachine)
  :config
  (setq git-timemachine-abbreviation-length 14
        git-timemachine-show-minibuffer-details t)
  (elpaca-wait))

;; From redguardtoo - http://blog.binchen.org/posts/new-git-timemachine-ui-based-on-ivy-mode.html
(defun my-git-timemachine-show-selected-revision ()
  "Show last (current) revision of file."
  (interactive)
  (let* ((collection (mapcar (lambda (rev)
                               ;; re-shape list for the ivy-read
                               (cons (concat (substring-no-properties (nth 0 rev) 0 7) "|" (nth 5 rev) "|" (nth 6 rev)) rev))
                             (git-timemachine--revisions))))
    (ivy-read "commits:"
              collection
              :action (lambda (rev)
                        ;; compatible with ivy 8+ and later ivy version
                        (unless (string-match "^[a-z0-9]*$" (car rev))
                          (setq rev (cdr rev)))
                        (git-timemachine-show-revision rev)))))

(defun my-git-timemachine ()
  "Open git snapshot with the selected version.  Based on ivy-mode."
  (interactive)
  (unless (featurep 'git-timemachine)
    (require 'git-timemachine))
  (git-timemachine--start #'my-git-timemachine-show-selected-revision))

(use-package magit
  :defer t
  :commands (magit
             magit-status
             magit-dispatch)
  :hook ((git-commit-setup-hook . git-commit-turn-on-flyspell)
         (git-commit-setup-hook . git-commit-save-message)
         (git-commit-setup-hook . turn-on-auto-fill))
  :general
  (deftpunk-leader-def
    "gg" '("Magit" . magit)
    "gs" '("Magit status" . magit-status))
  :init
  (if IS-MAC
      (setq magit-git-executable "/opt/homebrew/bin/git")
    (setq magit-git-executable "/usr/local/bin/git"))
  :config
  ;; Add git-timemachine to the magit-dispatch transient map.
  (transient-append-suffix 'magit-dispatch '(0 -1 -1) '("S" "git timemachine" git-timemachine))

  (setq  magit-log-arguments '("--graph" "--decorate" "--color")
         magit-revert-buffers 'silent
         magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")
         magit-diff-refine-hunk t ; show granular diffs in selected hunk
         ;; Don't autosave repo buffers. This is too magical, and saving can
         ;; trigger a bunch of unwanted side-effects, like save hooks and
         ;; formatters. Trust us to know what we're doing.
         magit-save-repository-buffers nil)

  ;; Open magit-status in entire window & restore the previous window config on close.
  (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1
        magit-bury-buffer-function 'magit-restore-window-configuration))

;;  (use-package forge
;;    :after magit
;;    :hook (magit-mode . forge-bug-reference-setup))

(use-package magit-delta
  :defer t
  :after magit
  :hook (magit-mode . magit-delta-mode))

(use-package sideline-blame)
;; Show the commit message for the current line.
(use-package sideline
  :init
  (setq sideline-backends-left '((sideline-blame . down))))

(use-package vc-msg
  :init
  (setq vc-msg-force-vcs "git"))

(defun dftpunk/comment-auto-fill ()
  " Set up auto-file / wrapping of comments."
  (flyspell-prog-mode)
  (setq-local comment-auto-fill-only-comments t)
  (auto-fill-mode 1))

;; Spellchecking and wrapping in comments.
(add-hook 'prog-mode-hook #'dftpunk/comment-auto-fill)

;; Make a buffer executable automatically if its a script
  (add-hook 'after-save-hook
            'executable-make-buffer-file-executable-if-script-p)

(setq-default display-line-numbers-width 3)
(setq-default display-line-numbers-widen t)

(use-package devdocs-browser
  :commands (devdocs-browser-open)
  :general ("C-h D" #'devdocs-browser-open))

;; Crank up the treesitter decoration; ensure the special =settr= is called by using =customize-set-variable=
(customize-set-variable 'treesit-font-lock-level 4)

(use-package treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  (treesit-auto-langs '(python rust clojure commonlisp bash nim json yaml toml go))
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))

(use-package lsp-mode
  :defer t
  :commands (lsp lsp-deferred)
  :hook (((python-mode python-ts-mode) . lsp)
         (clojure-mode . lsp))
  :hook (lsp-mode . lsp-enable-which-key-integration)
  :custom
  ;; uses company by default.
  (lsp-completion-show-detail t)
  (lsp-competion-show-kind t)
  (lsp-keymap-prefix "C-c l")
  (lsp-enable-symbol-highlighting t)
  (lsp-lens-enable t)
  (lsp-headerline-breadcrumb-enable t)
                                        ; I don't want squigglies in the breadcrumb line.
  (lsp-headerline-breadcrumb-enable-diagnostics nil)
  ;; (lsp-diagnostics-provider :flycheck)
  (lsp-completion-show-detail t)
  (lsp-completion-show-kind t)
  ;; Support for ruff server:
  ;; https://github.com/emacs-lsp/lsp-mode/issues/4451#issuecomment-2146722313
  ;; https://github.com/emacs-lsp/lsp-mode/issues/4451#issuecomment-2288490522
  (lsp-ruff-lsp-server-command '("ruff" "server"))
  :init
  ;; From the corfu wiki -> https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-mode
  (defun my/lsp-mode-setup-completion ()
    (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
           '(flex))) ;; Configure flex
  :hook
  (lsp-completion-mode . my/lsp-mode-setup-completion)
  )

;; emacs-lsp-booster
;;
(defun lsp-booster--advice-json-parse (old-fn &rest args)
  "Try to parse bytecode instead of json."
  (or
   (when (equal (following-char) ?#)
     (let ((bytecode (read (current-buffer))))
       (when (byte-code-function-p bytecode)
         (funcall bytecode))))
   (apply old-fn args)))
(advice-add (if (progn (require 'json)
                       (fboundp 'json-parse-buffer))
                'json-parse-buffer
              'json-read)
            :around
            #'lsp-booster--advice-json-parse)

(defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
  "Prepend emacs-lsp-booster command to lsp CMD."
  (let ((orig-result (funcall old-fn cmd test?)))
    (if (and (not test?)                             ;; for check lsp-server-present?
             (not (file-remote-p default-directory)) ;; see lsp-resolve-final-command, it would add extra shell wrapper
             lsp-use-plists
             (not (functionp 'json-rpc-connection))  ;; native json-rpc
             (executable-find "emacs-lsp-booster"))
        (progn
          (when-let ((command-from-exec-path (executable-find (car orig-result))))  ;; resolve command from exec-path (in case not found in $PATH)
            (setcar orig-result command-from-exec-path))
          (message "Using emacs-lsp-booster for %s!" orig-result)
          (cons "emacs-lsp-booster" orig-result))
      orig-result)))
(advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)

;; lsp-clients
;; TODO: pyright on VDT
;; (lsp-register-client
;; (make-lsp-client :new-connection (lsp-tramp-connection "pyright")
;;                  :major-modes '(python-mode python-ts-mode)
;;                  :remote? t
;;                  :server-id 'pyright-vdt))

;; (use-package lsp-pyright
;;   :ensure t
;;   :hook ((python-mode python-ts-mode) . (lambda ()
;;                                           (require 'lsp-pyright)
;;                                           (lsp))))  ; or lsp-deferred

(use-package lsp-ui
  :commands (lsp-ui-mode)
  :general
  (:keymaps 'lsp-ui-mode-map
            [remap xref-find-definitions] #'lsp-ui-peek-find-definitions
            [remap xref-find-references] #'lsp-ui-peek-find-references)
  :hook (lsp-mode . lsp-ui-mode)
  :config
  (setq lsp-ui-doc-position 'bottom
        lsp-ui-doc-header t
        lsp-ui-peek-enable t
        lsp-ui-peek-always-show t
        lsp-ui-sideline-show-hover t
        lsp-ui-sideline-show-diagnostics t
        lsp-ui-doc-include-signature t))

(use-package lsp-ivy)

(use-package lsp-treemacs
  :defer t
  :config
  (lsp-treemacs-sync-mode 1))

(use-package consult-lsp
  :ensure t
  :config
  (define-key lsp-mode-map [remap xref-find-apropos] #'consult-lsp-symbols))

(use-package aggressive-indent
  :defer t
  :commands (aggressive-indent-mode)
  :hook ((emacs-lisp-mode) . aggressive-indent-mode))

;; NOTE: If problems w/ TRAMP are encountered, add >> (setq docker-open-hook '())
(use-package docker
  :ensure t
  :defer t
  :commands (docker)
  :bind ("C-c d" . docker))

(use-package evil-nerd-commenter
  :config
  (evilnc-default-hotkeys))

(use-package fill-function-arguments
  :hook
  ((prog-mode . (lambda ()
                  (local-set-key (kbd "M-q") #'fill-function-arguments-dwim)))
   (emacs-lisp-mode . (lambda ()
                        (setq-local fill-function-arguments-second-argument-same-line t)
                        (setq-local fill-function-arguments-last-argument-same-line t)
                        (setq-local fill-function-arguments-argument-separator " "))))
  :custom
  (fill-function-arguments-indent-after-fill t)
  (fill-function-arguments-indent-first-argument-same-line t))

(use-package flycheck
  :ensure (flycheck :type git :host github :repo "flycheck/flycheck" :main "flycheck.el" :depth nil)
  :hook (prog-mode . global-flycheck-mode))

(use-package consult-flycheck
  :after (consult flycheck))

(use-package flycheck-overlay
  :ensure (flycheck-overlay :type git :host github :repo "konrad1977/flycheck-overlay")
  :hook (flycheck-mode . flycheck-overlay-mode))

(use-package highlight-defined
  :defer t
  :commands (highlight-defined)
  :hook (emacs-lisp-mode . highlight-defined-mode))

;; 12/05/24 21:42:05
;; Turning off in python mode for now - my current Emacs on Mac doesn't support :stipple
(use-package indent-bars
  :ensure (indent-bars :type git :host github :repo "jdtsmith/indent-bars")
  :hook ((python-mode yaml-mode) . indent-bars-mode)
  :custom
  (indent-bars-no-descend-lists t) ; no extra bars in continued func arg lists
  (indent-bars-treesit-support t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  ;; Add other languages as needed
  (indent-bars-treesit-scope '((python function_definition class_definition for_statement
                                       if_statement with_statement while_statement)))
  ;; Note: wrap may not be needed if no-descend-list is enough
  ;;(indent-bars-treesit-wrap '((python argument_list parameters ; for python, as an example
  ;;				      list list_comprehension
  ;;				      dictionary dictionary_comprehension
  ;;				      parenthesized_expression subscript)))
  ;; :hook ((python-base-mode yaml-mode) . indent-bars-mode)
  )

(use-package lispy)

(use-package outline-indent
  :ensure t
  :defer t
  :commands (outline-indent-minor-mode
             outline-indent-insert-heading)
  :custom
  (outline-indent-ellipsis " ▼ ")
  :hook (((python-mode python-ts-mode) . #'(lambda ()
                                             (setq-local outline-indent-default-offset 4)
                                             (setq-local outline-indent-shift-width 4)
                                             (outline-indent-minor-mode +1)))
         ((yaml-mode yaml-ts-mode) . #'(lambda ()
                                         (setq-local outline-indent-default-offset 2)
                                         (setq-local outline-indent-shift-width 2)
                                         (outline-indent-minor-mode +1)))))

(use-package projectile
  :bind (:map projectile-mode-map
              ("s-p" . projectile-command-map))
  :init
  (setq
   ;; Auto-discovery is slow to do by default. Better to update the list
   ;; when you need to (`projectile-discover-projects-in-search-path').
   projectile-project-search-path '("~/WorkStuff/eig")
   projectile-completion-system 'default
   projectile-auto-discover t
   projectile-enable-caching t
   projectile-globally-ignored-files '(".DS_Store" "TAGS")
   projectile-globally-ignored-file-suffixes '(".elc" ".pyc" ".o")
   projectile-kill-buffers-filter 'kill-only-files
   projectile-ignored-projects '("~/" "/tmp"))

  (setq projectile-cache-file (expand-file-name "projectile.cache" deftpunk--var-dir)
        projectile-known-projects-file (expand-file-name "projectile-known-projects.eld"
                                                         deftpunk--var-dir))
  ;; Do not include the straight repos
  (setq projectile-ignored-project-function
        (lambda (project-root)
          (string-prefix-p (expand-file-name "straight/" user-emacs-directory) project-root)))

  (global-set-key [remap find-tag]         #'projectile-find-tag)

  (projectile-mode +1))

(use-package consult-projectile
  ;; :bind (("s-p" . consult-projectile))
  :ensure (consult-projectile :type git :host gitlab :repo "OlMon/consult-projectile" :branch "master"))

(use-package rg)

(use-package rainbow-delimiters
  :hook ((prog-mode org-src-mode) . #'rainbow-delimiters-mode))

(use-package smartparens
    :commands (sp-local-pair)
    :hook (prog-mode . smartparens-mode)
    :config
    ;; smartparens doesn't recognize the sly-mrepl-mode
    (add-to-list 'sp-lisp-modes 'sly-mrepl-mode)

    ;; load the default smartparens rules for various languages.
    (require 'smartparens-config)

    ;; Overlays are too distracting and not terribly helpful. show-parens does
    ;; this for us already (and is faster), so...
    (setq sp-highlight-pair-overlay nil
          sp-highlight-wrap-overlay nil
          sp-highlight-wrap-tag-overlay nil)

    ;; The default is 100, because smartparen's scans are relatively expensive
    ;; (especially with large pair lists for some modes), we reduce it, as a
    ;; better compromise between performance and accuracy.
    (setq sp-max-prefix-length 25)
    ;; No pair has any business being longer than 4 characters; if they must, set
    ;; it buffer-locally. It's less work for smartparens.
    (setq sp-max-pair-length 4)
    ;; This isn't always smart enough to determine when we're in a string or not.
    ;; See https://github.com/Fuco1/smartparens/issues/783.
    (setq sp-escape-quotes-after-insert nil)

    ;; Silence some harmless but annoying echo-area spam
    (dolist (key '(:unmatched-expression :no-matching-tag))
      (setf (alist-get key sp-message-alist) nil))

    ;; You're likely writing lisp in the minibuffer, therefore, disable these
    ;; quote pairs, which lisps doesn't use for strings:
    (sp-local-pair 'minibuffer-inactive-mode "'" nil :actions nil)
    (sp-local-pair 'minibuffer-inactive-mode "`" nil :actions nil))

(use-package nim-mode
  :hook ((nim-mode . lsp)
         (nim-mode . subword-mode))
  )

(defun deftpunk/python-mode-hook ()
  "Setting up some basics for Python."
  (setq-local fill-column 105)
  (smartparens-strict-mode)
  (display-line-numbers-mode 1))

(use-package python
  :ensure nil
  ;:mode ((rx ".py" string-end) . python-mode)
  :hook (((python-mode python-ts-mode) . deftpunk/python-mode-hook))
  :config
  (setq-local flycheck-python-pylint-executable "pylint")
  (setq-local flycheck-python-flake8-executable "flake8")

  (setq python-shell-interpreter (executable-find "ipython")
        python-shell-interpreter-args "-i --simple-prompt --no-color-info"
        python-shell-prompt-block-regexp "\\.\\.\\.\\.: "
        python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
        python-shell-completion-setup-code
        "from IPython.core.completerlib import module_completion"
        python-shell-completion-string-code
        "';'.join(get_ipython().Completer.all_completions('''%s'''))\n")

  ;; some smartparens "smartness" for single quotes
  ;; (sp-local-pair 'python-mode "'" nil
  ;;                :unless '(sp-point-before-word-p
  ;;                          sp-point-after-word-p
  ;;                          sp-point-before-same-p))
  )

(deftpunk-local-leader-def
  :keymaps '(python-ts-mode-map python-mode-map)
  "c" '(conda-env-activate :which-key "Activate conda env")
  "d" '(conda-env-deactivate :which-key "Deactivate conda env")
  "t" '(python-pytest-dispatch :which-key "Pytest dispatch")
  )

(use-package conda
  :after python
  :defer t
  :config
  ;; taken from doom
  ;; The location of your anaconda home will be guessed from a list of common
  ;; possibilities, starting with `conda-anaconda-home''s default value (which
  ;; will consult a ANACONDA_HOME envvar, if it exists).
  ;;
  ;; If none of these work for you, `conda-anaconda-home' must be set
  ;; explicitly. Afterwards, run M-x `conda-env-activate' to switch between
  ;; environments
  (or (cl-loop for dir in (list conda-anaconda-home
                                "~/.miniconda3"
                                "~/.conda")
               if (file-directory-p dir)
               return (setq conda-anaconda-home (expand-file-name dir)
                            conda-env-home-directory (expand-file-name dir)))
      (message "Cannot find Anaconda installation"))
  ;; integration with term/eshell
  (conda-env-initialize-interactive-shells)
  (after! eshell (conda-env-initialize-eshell))

  ;; auto-activation (see below for details)
  ;; (conda-env-autoactivate-mode t)
  ;; automatically activate a conda environment on the opening of a file:
  ;; (add-hook 'find-file-hook (lambda () (when (and (bound-and-true-p conda-project-env-path) (string-match "\\.py\\'" buffer-file-name))
  ;;                                       (conda-env-activate-for-buffer))))

  ;; Add to the modeline so that we know which env is activated.
  (add-to-list 'global-mode-string
               '(conda-env-current-name (" conda:" conda-env-current-name " "))
               'append))

(use-package python-pytest
  :hook (python-mode . (lambda ()
                         (when-let ((r (locate-dominating-file default-directory ".gitignore")))
                           (setq python-pytest-executable
                                 (concat "PYTHONPATH=" r " " "pytest"))))))

(use-package lsp-pyright
  :ensure t
  :custom (lsp-pyright-langserver-command "pyright") ;; or basedpyright
  :hook ((python-ts-mode python-mode) . (lambda ()
                                          (require 'lsp-pyright)
                                          (lsp))))

(use-package python-docstring-mode
  :hook (python-mode . python-docstring-mode)
  :ensure (:host github :repo "glyph/python-docstring-mode" :main "python-docstring.el"))

(use-package clojure-mode
  :hook ((clojure-mode . smartparens-strict-mode)
         (clojure-mode . subword-mode)
         (clojure-mode . rainbow-delimiters-mode))
  :custom
  (clojure-indent-style 'always-align)
  (clojure-align-forms-automatically t)
  )

(use-package cider
  :after clojure-mode
  :ensure t
  :custom
  (cider-enrich-classpath t)
  (cider-connection-message-fn #'cider-random-tip)
  (cider-special-mode-truncate-lines nil)
  (cider-font-lock-dynamically '(macro core function var)))

;; Set a default Lisp: SBCL
(setq inferior-lisp-program "/opt/homebrew/bin/sbcl")

(use-package sly
  :defer t
  :custom
  (sly-lisp-implementations
   '((cumcl ("cumcl" "--quiet"))
     (sbcl ("/opt/homebrew/bin/sbcl") :coding-system utf-8-unix))))


;; Specify a different SBCL:
;; (sbcl-cvs ("/home/me/sbcl-cvs/src/runtime/sbcl"
;;            "--core" "/home/me/sbcl-cvs/output/sbcl.core")
;;           :env ("SBCL_HOME=/home/me/sbcl-cvs/contrib/"))

;; (defun sbcl-save-sly-and-die ()
;;   "Save a sbcl image, even when running from inside Sly.
;; This function should only be used in the *inferior-buffer* buffer,
;; inside emacs."
;;   (mapcar #'(lambda (x)
;;               (slynk::close-connection
;;                x nil nil))
;;           slynk::*connections*)
;;   (dolist (thread (remove
;;                    (slynk-backend::current-thread)
;;                    (slynk-backend::all-threads)))
;;     (slynk-backend::kill-thread thread))
;;   (sleep 1)
;;   (sb-ext:save-lisp-and-die #P"~/your-main-program.exe"
;;                             :toplevel #'your-main-function-here
;;                             :executable t
;;                             :compression t))
;;
;; in *sly-inferior-lisp* buffer
;; (sbcl-save-sly-and-die)

;; (defun my-sly-load-system-from-current-directory (directory)
;;   "Loads, via Quickload an ASDF system from a selectable directory.
;; Requires: Emacs package `sly-quicklisp' installed and an running SLY REPL."
;;   (interactive (list (read-directory-name
;;                       "directory to search for ASDF definition: "
;;                       default-directory)))
;;   ;; find first `*.asd' file in dir (code taken from sly-asdf)
;;   (let ((system-file (cl-find-if #'(lambda (file)
;;                                      (string-equal "asd" (file-name-extension file)))
;;                                  (directory-files directory))))
;;     (when system-file
;;       ;; publish directory
;;       (sly-eval
;;        `(slynk:eval-and-grab-output
;;          ,(concat "(pushnew \""
;;                   directory
;;                   "\"quicklisp:*local-project-directories* :test #'equalp)")))
;;       ;; load ASDF system
;;       (sly-quickload (file-name-base system-file)))))

(use-package csv-mode
  :defer t
  :commands (csv-mode csv-align-mode)
  :custom
  (csv-separators '("," ";" "    " "|"))
  :config
  (deftpunk-local-leader-def
    :keymaps 'csv-mode-map
    "a" '(csv-align-mode :which-key "CSV align columns.")
    "s" '(csv-sort-fields :which-key "Sort fields lexicographically.")
    "n" '(csv-sort-numeric-fields :which-key "Sort fields numerically.")))

(use-package dockerfile-mode
  :defer t
  :mode "Dockerfile.*\\'")

(use-package markdown-mode
  :defer t
  :after (magit lsp-mode)
  :commands (markdown-mode gfm-mode)
  :hook (markdown-mode . flyspell-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'"       . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :custom
  (markdown-command "/opt/homebrew/bin/multimarkdown")
  (markdown-header-scaling t))

(use-package yaml-mode
  :ensure t
  :defer t
  :mode "\\.y[a]ml\\'"
  :mode "\\.y[a]ml\\.j2\\'"
  :custom-face
  (font-lock-variable-name-face ((t (:foreground "#cba6f7"))))
  :config)

(use-package yaml-pro
  :defer t
  :hook (yaml-mode . yaml-ts-mode-hook)
  :config
  ;; the original bindings will work as well, these are shorter if you prefer them.
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-n" #'yaml-pro-ts-next-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-p" #'yaml-pro-ts-prev-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-u" #'yaml-pro-ts-up-level)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-d" #'yaml-pro-ts-down-level)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-k" #'yaml-pro-ts-kill-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-<backspace>" #'yaml-pro-ts-kill-subtree)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-a" #'yaml-pro-ts-first-sibling)
  ;;(keymap-set yaml-pro-ts-mode-map "C-M-e" #'yaml-pro-ts-last-sibling)

  (deftpunk-local-leader-def
    :keymaps 'yaml-pro-ts-mode-map
    "n" '(yaml-pro-ts-next-subtree :which-key "Next subtree")
    "p" '(yaml-pro-ts-prev-subtree :which-key "Previous subtree")
    "u" '(yaml-pro-ts-up-level :which-key "Up subtree")
    "d" '(yaml-pro-ts-down-level :which-key "Down subtree")
    "k" '(yaml-pro-ts-kill-subtree :which-key "Kill subtree")
    "<backspace>" '(yaml-pro-ts-kill-subtree :which-key "Kill subtree")
    "a" '(yaml-pro-ts-first-sibling :which-key "First sibling")
    "e" '(yaml-pro-ts-last-sibling :which-key "Last sibling")
    )

  (defvar-keymap my/yaml-pro/tree-repeat-map
    :repeat t
    "n" #'yaml-pro-ts-next-subtree
    "p" #'yaml-pro-ts-prev-subtree
    "u" #'yaml-pro-ts-up-level
    "d" #'yaml-pro-ts-down-level
    "m" #'yaml-pro-ts-mark-subtree
    "k" #'yaml-pro-ts-kill-subtree
    "a" #'yaml-pro-ts-first-sibling
    "e" #'yaml-pro-ts-last-sibling
    "SPC" #'my/yaml-pro/set-mark)

  (defun my/yaml-pro/set-mark ()
    (interactive)
    (my/region/set-mark 'my/yaml-pro/set-mark))

  (defun my/region/set-mark (command-name)
    (if (eq last-command command-name)
        (if (region-active-p)
            (progn
              (deactivate-mark)
              (message "Mark deactivated"))
          (activate-mark)
          (message "Mark activated"))
      (set-mark-command nil))))

(use-package vterm
  :ensure t
  :defer t
  :commands (vterm)
  :load-path  "~/Downloads/emacs-libvterm/"
  :hook
  ;; Change the face so its more obvious we are in an emulator.
  (vterm-mode . (lambda ()
                  (set (make-local-variable 'buffer-face-mode-face) 'fixed-pitch)
                  (buffer-face-mode t)))
  :custom
  (vterm-always-compile-module t)
  (vterm-max-scrollback 100000)               ; the max without changing vterm-module.h and re-compiling
  (vterm-copy-mode-remove-fake-newlines t)
  :config
  (setq vterm-timer-delay 0.01))

;; fix the following: "open terminal failed: can't use /dev/tty"
;; https://github.com/akermu/emacs-libvterm/issues/569#issuecomment-2244574273
(define-advice vterm--get-shell (:filter-return (vterm-shell) quote-remote)
  "Quote VTERM-SHELL if it's a remote shell."
  (if (and (ignore-errors (file-remote-p default-directory))
           (not (string-match-p "'.*'" vterm-shell)))
      (format "'%s'" vterm-shell)
    vterm-shell))

(defun run-in-vterm-kill (process event)
  "A process sentinel. Kills PROCESS's buffer if it is live."
  (let ((b (process-buffer process)))
    (and (buffer-live-p b)
         (kill-buffer b))))

(defun run-in-vterm (command)
  "Execute string COMMAND in a new vterm.

Interactively, prompt for COMMAND with the current buffer's file
name supplied. When called from Dired, supply the name of the
file at point.

Like `async-shell-command`, but run in a vterm for full terminal features.

The new vterm buffer is named in the form `*foo bar.baz*`, the
command and its arguments in earmuffs.

When the command terminates, the shell remains open, but when the
shell exits, the buffer is killed."
  (interactive
   (list
    (let* ((f (cond (buffer-file-name)
                    ((eq major-mode 'dired-mode)
                     (dired-get-filename nil t))))
           (filename (concat " " (shell-quote-argument (and f (file-relative-name f))))))
      (read-shell-command "Terminal command: "
                          (cons filename 0)
                          (cons 'shell-command-history 1)
                          (list filename)))))
  (with-current-buffer (vterm (concat "*" command "*"))
    (set-process-sentinel vterm--process #'run-in-vterm-kill)
    (vterm-send-string command)
    (vterm-send-return)))

(use-package multi-vterm
  :ensure t
  :defer t
  :general
  (:prefix "C-c t"
           "t" #'multi-vterm
           "d" #'multi-vterm-dedicated-toggle
           "n" #'multi-vterm-next
           "p" #'multi-vterm-previous))

(use-package google-this)

(use-package osx-trash
  :config
  (when (eq system-type 'darwin)
    (osx-trash-setup))
  (setq delete-by-moving-to-trash t))

(use-package page-break-lines
  :blackout t
  :hook (text-mode . page-break-lines-mode))

(setq auto-save-default nil) ; turn off the builtin auto-save
(use-package super-save
  :blackout t
  :custom
  (super-save-silent t)
  (super-save-delete-trailing-whitespace t)
  (super-save-remote-files nil)
  (super-save-auto-save-when-idle t)
  (super-save-exclude '(".gpg"))
  :config
  (add-to-list 'super-save-triggers 'ace-window)
  (add-to-list 'super-save-hook-triggers 'find-file-hook)
  (super-save-mode +1))

(use-package treemacs
  :ensure t
  :defer t
  :commands (treemacs
             treemacs-follow-mode
             treemacs-filewatch-mode
             treemacs-fringe-indicator-mode
             treemacs-git-mode)
  :init
  (setq treemacs-missing-project-action  'remove
        treemacs-sorting                 'alphabetic-asc
        treemacs-follow-after-init       t
        treemacs-width                   35)
  :config
  (treemacs-follow-mode t)
  (treemacs-filewatch-mode t))

(use-package treemacs-magit
  :ensure t
  :after magit
  :commands treemacs-magit--schedule-update
  :hook ((magit-post-commit
          git-commit-post-finish
          magit-post-stage
          magit-post-unstage)
         . treemacs-magit--schedule-update))

(global-unset-key (kbd "M-u"))
(use-package unfill
  :bind
  (("M-u" . unfill-toggle)))

;; Trying out matching parens
;; https://www.gnu.org/software/emacs/manual/html_node/efaq/Matching-parentheses.html
(defun match-paren (arg)
  "Go to the matching paren if on a paren; otherwise insert %."
  (interactive "p")
  (cond ((looking-at "\\s(") (forward-list 1) (backward-char 1))
        ((looking-at "\\s)") (forward-char 1) (backward-list 1))
        (t (self-insert-command (or arg 1)))))

(global-set-key "%" 'match-paren)

;; From https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
(defun prot/keyboard-quit-dwim ()
  "Do-What-I-Mean behaviour for a general `keyboard-quit'.

The generic `keyboard-quit' does not do the expected thing when
the minibuffer is open.  Whereas we want it to close the
minibuffer, even without explicitly focusing it.

The DWIM behaviour of this command is as follows:

- When the region is active, disable it.
- When a minibuffer is open, but not focused, close the minibuffer.
- When the Completions buffer is selected, close it.
- In every other case use the regular `keyboard-quit'."
  (interactive)
  (cond
   ((region-active-p)
    (keyboard-quit))
   ((derived-mode-p 'completion-list-mode)
    (delete-completion-window))
   ((> (minibuffer-depth) 0)
    (abort-recursive-edit))
   (t
    (keyboard-quit))))

(define-key global-map (kbd "C-g") #'prot/keyboard-quit-dwim)

;; Some final remapping of Escape to "Quit"

(global-set-key (kbd "<escape>") 'keyboard-quit)

;; When C-g gets rebound.
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))

(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)

(global-set-key (kbd "<pinch>") 'ignore)
(global-set-key (kbd "<C-wheel-up>") 'ignore)
(global-set-key (kbd "<C-wheel-down>") 'ignore)

;; Remove the  C-; key from the flyspell mode map.  We want to use it for our local-leader
;; Remove the C-; key so that we can use it for a local-leader
(general-define-key
 :keymaps 'flyspell-mode-map
 "C-;" nil)

;; https://www.reddit.com/r/emacs/comments/r7l3ar/comment/hn3kuwh/?utm_source=share&utm_medium=web2x&context=3
(defun my/scroll-down-half-page ()
  "scroll down half a page while keeping the cursor centered"
  (interactive)
  (let ((ln (line-number-at-pos (point)))
        (lmax (line-number-at-pos (point-max))))
    (cond ((= ln 1) (move-to-window-line nil))
          ((= ln lmax) (recenter (window-end)))
          (t (progn
               (move-to-window-line -1)
               (recenter))))))

(defun my/scroll-up-half-page ()
  "scroll up half a page while keeping the cursor centered"
  (interactive)
  (let ((ln (line-number-at-pos (point)))
        (lmax (line-number-at-pos (point-max))))
    (cond ((= ln 1) nil)
          ((= ln lmax) (move-to-window-line nil))
          (t (progn
               (move-to-window-line 0)
               (recenter))))))

;; TODO remap scroll half-page functions over the current scroll bindings/functions.

;; Figure out hippie-expand
;; From https://stackoverflow.com/a/43665319
(defun my-expand-lines ()
  "My old friend C-x C-l in Emacs"
  (interactive)
  (let ((hippie-expand-try-functions-list
         '(try-expand-line)))
    (call-interactively 'hippie-expand)))

(global-unset-key (kbd "C-x C-l")) ; I can downcase the region another way.
(global-set-key (kbd "C-x C-l") 'my-expand-lines)

;; Bind backward-kill-word to C-w like it is in Neovim/vim because I can kill the region other ways
(global-unset-key (kbd "C-w"))
(global-set-key (kbd "C-w") 'backward-kill-word)

;; Repeating
(global-unset-key (kbd "C-z"))
(global-set-key (kbd "C-.") 'repeat) ; repeats single command w/out minibuffer input, userful for deletions, instertions, movement keys
(global-set-key (kbd "C-z") 'repeat-complex-command) ; repeat complex commands that involve minibuffer input

(general-create-definer deftpunk-toggle-bindings
  :keymaps 'override
  :prefix "s-t")

(deftpunk-toggle-bindings
 "l" '("Flycheck overlay" . flycheck-overlay-toggle))

(deftpunk-leader-def
  ;; Source Control bindings.
  "gs" '("Magit Status" . magit-status)
  "gl" '("Git link" . git-link)
  )

(use-package key-chord
  :commands (key-chord-define-global)
  :init
  (key-chord-mode 1)
  :config
  (key-chord-define-global "jk" 'execute-extended-command)
  (key-chord-define-global "hh" 'split-window-below)
  (key-chord-define-global "vv" 'split-window-right))

;; (setq gc-cons-threshold 16777216) ; 16MB
(setq gc-cons-threshold most-positive-fixnum) ; 16MB
(run-with-idle-timer 1.2 t 'garbage-collect)

(server-start)
